// Category: fischkunde_und_hege — Fish science & care (1/2)
export const questions = [
  // --- anatomy ---
  ['bbg-001', 'fischkunde_und_hege',
    ['Welche Hauptfunktion hat die Schwimmblase der Fische?',
     'What is the main function of the swim bladder in fish?',
     'Qual é a principal função da bexiga natatória dos peixes?'],
    [['Sie verleiht dem Fisch Auftrieb in der gewünschten Wassertiefe', 'It gives the fish buoyancy at the desired water depth', 'Ela dá flutuabilidade ao peixe na profundidade desejada'],
     ['Sie dient der Atmung unter Wasser', 'It is used for breathing underwater', 'Ela serve para respirar debaixo d\u2019água'],
     ['Sie dient der Fortpflanzung', 'It is used for reproduction', 'Ela serve para a reprodução']],
    0,
    ['Die Schwimmblase ist ein gasgefülltes Organ, das dem Fisch den Auftrieb verleiht und ihm ermöglicht, ohne Muskelkraft in einer Wassertiefe zu verharren. Kiemen dienen der Atmung.',
     'The swim bladder is a gas-filled organ that gives the fish buoyancy and lets it hold a depth without muscular effort. Gills are used for breathing.',
     'A bexiga natatória é um órgão cheio de gás que dá flutuabilidade ao peixe e permite que ele permaneça em uma profundidade sem esforço muscular. As brânquias servem para respirar.'],
    ['anatomie', 'schwimmblase', 'biologie'], ['hecht', 'karpfen', 'zander']],

  ['bbg-002', 'fischkunde_und_hege',
    ['Womit atmen Fische unter Wasser?',
     'What do fish breathe with underwater?',
     'Com o que os peixes respiram debaixo d\u2019água?'],
    [['Mit der Schwimmblase', 'With the swim bladder', 'Com a bexiga natatória'],
     ['Mit den Kiemen', 'With the gills', 'Com as brânquias'],
     ['Mit der Seitenlinie', 'With the lateral line', 'Com a linha lateral']],
    1,
    ['Fische nehmen den im Wasser gelösten Sauerstoff über ihre Kiemen auf. Die Schwimmblase dient dem Auftrieb, die Seitenlinie der Wahrnehmung von Wasserbewegungen.',
     'Fish take up oxygen dissolved in the water through their gills. The swim bladder provides buoyancy and the lateral line senses water movements.',
     'Os peixes captam o oxigênio dissolvido na água através das brânquias. A bexiga natatória dá flutuabilidade e a linha lateral percebe movimentos da água.'],
    ['anatomie', 'atemsystem'], ['hecht', 'forelle', 'barsch']],

  ['bbg-003', 'fischkunde_und_hege',
    ['Wozu dient die Seitenlinie der Fische?',
     'What is the lateral line of fish used for?',
     'Para que serve a linha lateral dos peixes?'],
    [['Zur Wahrnehmung von Bewegungen und Druckwellen im Wasser', 'For sensing movements and pressure waves in the water', 'Para perceber movimentos e ondas de pressão na água'],
     ['Zur Regulierung des Auftriebs', 'For regulating buoyancy', 'Para regular a flutuabilidade'],
     ['Zur Aufnahme von Sauerstoff', 'For taking up oxygen', 'Para captar oxigênio']],
    0,
    ['Die Seitenlinie ist ein Sinnesorgan, das Druckunterschiede und Strömungen wahrnimmt. Damit spüren Fische Beute und Feinde auch bei schlechter Sicht.',
     'The lateral line is a sensory organ that detects pressure differences and currents. This way fish sense prey and predators even in poor visibility.',
     'A linha lateral é um órgão sensorial que detecta diferenças de pressão e correntes. Assim os peixes percebem presas e predadores mesmo com pouca visibilidade.'],
    ['anatomie', 'sinnesorgane'], ['hecht', 'zander']],

  ['bbg-004', 'fischkunde_und_hege',
    ['Welche Aufgabe haben die Brustflossen der Fische?',
     'What is the task of the pectoral fins of fish?',
     'Qual é a função das nadadeiras peitorais dos peixes?'],
    [['Sie dienen dem Antrieb im Wasser', 'They are used for propulsion in the water', 'Elas servem para a propulsão na água'],
     ['Sie dienen der Steuerung und dem Bremsen', 'They are used for steering and braking', 'Elas servem para direção e frenagem'],
     ['Sie dienen der Fortpflanzung', 'They are used for reproduction', 'Elas servem para a reprodução']],
    1,
    ['Die Brustflossen wirken wie Ruder: Sie dienen der Steuerung, dem Bremsen und feinen Manövrieren. Der Hauptantrieb kommt von der Schwanzflosse.',
     'The pectoral fins act like rudders: they are used for steering, braking and fine manoeuvring. The main propulsion comes from the tail fin.',
     'As nadadeiras peitorais funcionam como lemes: servem para direção, frenagem e manobras finas. A propulsão principal vem da nadadeira caudal.'],
    ['anatomie', 'flossen'], ['hecht', 'barsch']],

  ['bbg-005', 'fischkunde_und_hege',
    ['Welche Funktion hat die Rückenflosse der Fische?',
     'What is the function of the dorsal fin of fish?',
     'Qual é a função da nadadeira dorsal dos peixes?'],
    [['Sie stabilisiert den Fisch im Wasser', 'It stabilises the fish in the water', 'Ela estabiliza o peixe na água'],
     ['Sie dient als Hauptantrieb', 'It is the main source of propulsion', 'Ela é a principal fonte de propulsão'],
     ['Sie nimmt Sauerstoff aus dem Wasser auf', 'It takes up oxygen from the water', 'Ela capta oxigênio da água']],
    0,
    ['Die Rückenflosse verhindert ein Abrollen des Fisches zur Seite und wirkt stabilisierend. Der Antrieb erfolgt über die Schwanzflosse, die Atmung über die Kiemen.',
     'The dorsal fin prevents the fish from rolling to the side and has a stabilising effect. Propulsion comes from the tail fin and breathing from the gills.',
     'A nadadeira dorsal impede o peixe de rolar para o lado e tem efeito estabilizador. A propulsão vem da nadadeira caudal e a respiração, das brânquias.'],
    ['anatomie', 'flossen'], ['barsch', 'karpfen']],

  ['bbg-006', 'fischkunde_und_hege',
    ['Welche heimischen Fische besitzen eine Fettflosse?',
     'Which native fish have an adipose fin?',
     'Quais peixes nativos possuem nadadeira adiposa?'],
    [['Forellenartige, wie die Bachforelle', 'Salmonids such as the brown trout', 'Salmonídeos, como a truta-marrom'],
     ['Karpfenartige, wie der Karpfen', 'Cyprinids such as the carp', 'Ciprinídeos, como a carpa'],
     ['Barschartige, wie der Barsch', 'Perch-like fish such as the perch', 'Percídeos, como a perca']],
    0,
    ['Die kleine, fleischige Fettflosse hinter der Rückenflosse ist ein typisches Merkmal der Forellenartigen (Salmoniden), zum Beispiel der Bachforelle.',
     'The small fleshy adipose fin behind the dorsal fin is a typical feature of the salmonids, for example the brown trout.',
     'A pequena nadadeira adiposa e carnuda atrás da dorsal é uma característica típica dos salmonídeos, por exemplo da truta-marrom.'],
    ['anatomie', 'artenbestimmung'], ['forelle', 'asche']],

  ['bbg-007', 'fischkunde_und_hege',
    ['Womit ist der Körper der meisten Fische bedeckt?',
     'What covers the body of most fish?',
     'Com o que o corpo da maioria dos peixes é coberto?'],
    [['Mit einem Schleimüberzug über den Schuppen', 'With a slime coating over the scales', 'Com uma camada de muco sobre as escamas'],
     ['Mit einem harten Panzer', 'With a hard shell', 'Com uma carapaça dura'],
     ['Mit Fell', 'With fur', 'Com pelos']],
    0,
    ['Schuppen sind von einer dünnen Schleimschicht (Cuticula) bedeckt, die den Fisch vor Krankheiten schützt und den Wasserwiderstand verringert.',
     'Scales are covered by a thin slime layer (cuticle) that protects the fish from diseases and reduces water resistance.',
     'As escamas são cobertas por uma fina camada de muco (cutícula) que protege o peixe contra doenças e reduz a resistência da água.'],
    ['anatomie', 'schuppen'], ['karpfen', 'hecht']],

  ['bbg-008', 'fischkunde_und_hege',
    ['Wie erkennt ein Fisch Beute und Feinde auch bei trübem Wasser?',
     'How does a fish recognise prey and predators even in murky water?',
     'Como um peixe reconhece presas e predadores mesmo em água turva?'],
    [['Über das Seitenlinienorgan und die Geruchssinne', 'Through the lateral line organ and the sense of smell', 'Pelo órgão da linha lateral e pelo olfato'],
     ['Über die Schwimmblase', 'Through the swim bladder', 'Pela bexiga natatória'],
     ['Über die Schuppen', 'Through the scales', 'Pelas escamas']],
    0,
    ['Die Seitenlinie nimmt Druckwellen wahr, der Geruchssinn spielt eine große Rolle. So orientieren sich Fische auch bei schlechter Sicht sicher.',
     'The lateral line senses pressure waves and the sense of smell plays a big role. This is how fish orient themselves reliably even in poor visibility.',
     'A linha lateral percebe ondas de pressão e o olfato tem grande importância. Assim os peixes se orientam com segurança mesmo com pouca visibilidade.'],
    ['anatomie', 'sinnesorgane'], ['zander', 'wels']],

  ['bbg-009', 'fischkunde_und_hege',
    ['Welche Flosse erzeugt den Hauptvortrieb beim Schwimmen?',
     'Which fin produces the main thrust when swimming?',
     'Qual nadadeira produz o impulso principal na natação?'],
    [['Die Schwanzflosse', 'The tail (caudal) fin', 'A nadadeira caudal'],
     ['Die Bauchflossen', 'The pelvic fins', 'As nadadeiras pélvicas'],
     ['Die Afterflosse', 'The anal fin', 'A nadadeira anal']],
    0,
    ['Die Schwanzflosse ist das Hauptantriebsorgan. Bauch- und Afterflossen dienen der Stabilisierung und Steuerung.',
     'The tail fin is the main propulsion organ. The pelvic and anal fins are used for stabilisation and steering.',
     'A nadadeira caudal é o principal órgão de propulsão. As nadadeiras pélvicas e anal servem para estabilização e direção.'],
    ['anatomie', 'flossen'], ['hecht', 'forelle']],

  ['bbg-010', 'fischkunde_und_hege',
    ['Was versteht man unter der \u201eCuticula\u201c der Fische?',
     'What is meant by the \u201ccuticle\u201d of fish?',
     'O que se entende por \u201ccutícula\u201d dos peixes?'],
    [['Den schleimigen Überzug, der die Schuppen schützt', 'The slimy coating that protects the scales', 'A camada viscosa que protege as escamas'],
     ['Die Schwimmblase', 'The swim bladder', 'A bexiga natatória'],
     ['Die Fettflosse', 'The adipose fin', 'A nadadeira adiposa']],
    0,
    ['Die Cuticula ist die dünne Schleimschicht auf den Schuppen. Sie schützt vor Krankheitserregern, verringert den Strömungswiderstand und wird beim Anfassen mit trockenen Händen verletzt.',
     'The cuticle is the thin slime layer on the scales. It protects against pathogens, reduces drag and is damaged when the fish is touched with dry hands.',
     'A cutícula é a fina camada de muco sobre as escamas. Ela protege contra agentes patogênicos, reduz o atrito e é danificada quando o peixe é tocado com as mãos secas.'],
    ['anatomie', 'schleimschicht'], ['karpfen', 'hecht']],

  // --- species identification ---
  ['bbg-011', 'fischkunde_und_hege',
    ['Welcher Raubfisch hat einen lang gestreckten Körper und ein entenschnabelähnliches, breites Maul?',
     'Which predatory fish has an elongated body and a wide, duck-bill-like mouth?',
     'Qual peixe predador tem corpo alongado e boca larga semelhante a um bico de pato?'],
    [['Der Hecht', 'The pike', 'O lúcio'],
     ['Der Barsch', 'The perch', 'A perca'],
     ['Der Aal', 'The eel', 'A enguia']],
    0,
    ['Der Hecht (Esox lucius) besitzt einen lang gestreckten Körper und das typische entenschnabelartige Maul mit vielen scharfen Zähnen.',
     'The pike (Esox lucius) has an elongated body and the typical duck-bill mouth full of sharp teeth.',
     'O lúcio (Esox lucius) tem o corpo alongado e a típica boca em forma de bico de pato, cheia de dentes afiados.'],
    ['artenbestimmung', 'raubfisch'], ['hecht']],

  ['bbg-012', 'fischkunde_und_hege',
    ['Welcher Raubfisch hat zwei getrennte Rückenflossen und ein endständiges Maul mit großen Zähnen?',
     'Which predatory fish has two separate dorsal fins and a terminal mouth with large teeth?',
     'Qual peixe predador tem duas nadadeiras dorsais separadas e boca terminal com dentes grandes?'],
    [['Der Karpfen', 'The carp', 'A carpa'],
     ['Der Zander', 'The pikeperch', 'O lúcio-perca'],
     ['Die Schleie', 'The tench', 'A tenca']],
    1,
    ['Der Zander (Sander lucioperca) gehört zu den Barschartigen und hat zwei getrennte Rückenflossen. Sein endständiges Maul ist mit großen, kräftigen Zähnen bestückt.',
     'The pikeperch (Sander lucioperca) belongs to the perch family and has two separate dorsal fins. Its terminal mouth is equipped with large, strong teeth.',
     'O lúcio-perca (Sander lucioperca) pertence à família das percas e tem duas nadadeiras dorsais separadas. Sua boca terminal é provida de dentes grandes e fortes.'],
    ['artenbestimmung', 'raubfisch'], ['zander']],

  ['bbg-013', 'fischkunde_und_hege',
    ['Welcher Friedfisch hat zwei Barteln am Maul?',
     'Which coarse fish has two barbels at its mouth?',
     'Qual peixe não predador tem dois barbilhões na boca?'],
    [['Die Plötze', 'The roach', 'A barata'],
     ['Der Karpfen', 'The carp', 'A carpa'],
     ['Der Barsch', 'The perch', 'A perca']],
    1,
    ['Der Karpfen (Cyprinus carpio) besitzt an seinem vorstülpbaren Maul zwei Paar Barteln. Plötze und Barsch haben keine Barteln.',
     'The carp (Cyprinus carpio) has two pairs of barbels on its protractile mouth. Roach and perch have no barbels.',
     'A carpa (Cyprinus carpio) tem dois pares de barbilhões na boca protrátil. A barata e a perca não têm barbilhões.'],
    ['artenbestimmung', 'friedfisch'], ['karpfen']],

  ['bbg-014', 'fischkunde_und_hege',
    ['Welcher heimische Fisch hat einen schlangenförmigen Körper?',
     'Which native fish has a snake-like body?',
     'Qual peixe nativo tem corpo semelhante ao de uma cobra?'],
    [['Der Aal', 'The eel', 'A enguia'],
     ['Der Hecht', 'The pike', 'O lúcio'],
     ['Der Wels', 'The catfish', 'O siluro']],
    0,
    ['Der Aal (Anguilla anguilla) hat einen lang gestreckten, schlangenförmigen Körper ohne Bauchflossen. Hecht und Wels haben einen kräftigen, nicht schlangenförmigen Körperbau.',
     'The eel (Anguilla anguilla) has a long, snake-like body without pelvic fins. Pike and catfish have a sturdy build that is not snake-like.',
     'A enguia (Anguilla anguilla) tem corpo longo e serpentiforme, sem nadadeiras pélvicas. O lúcio e o siluro têm corpo robusto, não serpentiforme.'],
    ['artenbestimmung'], ['aal']],

  ['bbg-015', 'fischkunde_und_hege',
    ['Welcher Fisch besitzt eine sehr lange, hohe Rückenflosse und lebt bevorzugt in klaren, kühlen Fließgewässern?',
     'Which fish has a very long, tall dorsal fin and prefers clear, cool running waters?',
     'Qual peixe tem uma nadadeira dorsal muito longa e alta e prefere rios claros e frios?'],
    [['Die Äsche', 'The grayling', 'O timalo'],
     ['Der Karpfen', 'The carp', 'A carpa'],
     ['Der Kaulbarsch', 'The ruffe', 'O rufe']],
    0,
    ['Die Äsche (Thymallus thymallus) ist durch ihre lange, hohe Rückenflosse unverwechselbar. Sie lebt in sauberen, kühlen und sauerstoffreichen Fließgewässern.',
     'The grayling (Thymallus thymallus) is unmistakable because of its long, tall dorsal fin. It lives in clean, cool and oxygen-rich running waters.',
     'O timalo (Thymallus thymallus) é inconfundível pela nadadeira dorsal longa e alta. Vive em rios limpos, frios e ricos em oxigênio.'],
    ['artenbestimmung', 'fliesgewaesser'], ['asche']],

  ['bbg-016', 'fischkunde_und_hege',
    ['Welcher kleine Schwarmfisch hat einen grünlich glänzenden Längsstreifen an der Flanke?',
     'Which small shoaling fish has a greenish shining longitudinal stripe on its flank?',
     'Qual peixinho de cardume tem uma faixa longitudinal esverdeada e brilhante no flanco?'],
    [['Der Ukelei', 'The bleak', 'O alburno'],
     ['Die Rotfeder', 'The rudd', 'O rudinho'],
     ['Die Quappe', 'The burbot', 'A lota']],
    0,
    ['Der Ukelei (Alburnus alburnus) ist ein kleiner Schwarmfisch mit grünlich schimmerndem Seitenstreifen. Er kommt häufig an der Wasseroberfläche vor.',
     'The bleak (Alburnus alburnus) is a small shoaling fish with a greenish shimmering lateral stripe. It is often found near the water surface.',
     'O alburno (Alburnus alburnus) é um peixinho de cardume com faixa lateral esverdeada e brilhante. É comum perto da superfície da água.'],
    ['artenbestimmung', 'schwarmfisch'], ['ukelei']],

  ['bbg-017', 'fischkunde_und_hege',
    ['Welcher Friedfisch hat einen seitlich stark abgeflachten Körper und intensiv rote Flossen?',
     'Which coarse fish has a strongly flattened body and intensely red fins?',
     'Qual peixe não predador tem corpo bem achatado lateralmente e nadadeiras intensamente vermelhas?'],
    [['Die Rotfeder', 'The rudd', 'O rudinho'],
     ['Der Wels', 'The catfish', 'O siluro'],
     ['Der Hecht', 'The pike', 'O lúcio']],
    0,
    ['Die Rotfeder (Scardinius erythrophthalmus) hat einen hohen, seitlich abgeflachten Körper und leuchtend rote Flossen. Wels und Hecht sind Raubfische mit anderer Körperform.',
     'The rudd (Scardinius erythrophthalmus) has a deep, laterally flattened body and bright red fins. Catfish and pike are predatory fish with a different body shape.',
     'O rudinho (Scardinius erythrophthalmus) tem corpo alto e achatado lateralmente e nadadeiras vermelho-vivas. Siluro e lúcio são predadores com outro formato de corpo.'],
    ['artenbestimmung', 'friedfisch'], ['rotfeder']],

  ['bbg-018', 'fischkunde_und_hege',
    ['Welcher große Raubfisch hat einen breiten, flachen Kopf und ein sehr großes, bis hinter die Augen reichendes Maul?',
     'Which large predatory fish has a broad, flat head and a very large mouth that extends behind the eyes?',
     'Qual grande peixe predador tem cabeça larga e achatada e boca muito grande que se estende atrás dos olhos?'],
    [['Der Wels', 'The (wels) catfish', 'O siluro'],
     ['Der Hecht', 'The pike', 'O lúcio'],
     ['Der Zander', 'The pikeperch', 'O lúcio-perca']],
    0,
    ['Der Europäische Wels (Silurus glanis) hat einen breiten, abgeflachten Kopf und ein riesiges Maul mit feinen Zahnbürsten. Er ist der größte heimische Raubfisch.',
     'The wels catfish (Silurus glanis) has a broad, flat head and a huge mouth lined with fine teeth. It is the largest native predatory fish.',
     'O siluro (Silurus glanis) tem cabeça larga e achatada e boca enorme com dentes finos. É o maior peixe predador nativo.'],
    ['artenbestimmung', 'raubfisch'], ['wels']],

  ['bbg-019', 'fischkunde_und_hege',
    ['Welcher Friedfisch wird wegen seines hohen, seitlich abgeflachten Körpers auch \u201eBrachse\u201c genannt?',
     'Which coarse fish is also called \u201cbream\u201d because of its deep, flattened body?',
     'Qual peixe não predador também é chamado de \u201cbrema\u201d por causa do corpo alto e achatado?'],
    [['Der Blei', 'The bream', 'A brema'],
     ['Der Aal', 'The eel', 'A enguia'],
     ['Der Barsch', 'The perch', 'A perca']],
    0,
    ['Der Blei (Abramis brama), auch Brachse genannt, hat einen hohen, seitlich abgeflachten Körper und ein kleines, unterständiges Maul.',
     'The bream (Abramis brama), also called Brachse, has a deep, laterally flattened body and a small, inferior mouth.',
     'A brema (Abramis brama), também chamada de Brachse, tem corpo alto e achatado lateralmente e boca pequena e inferior.'],
    ['artenbestimmung', 'friedfisch'], ['blei']],

  ['bbg-020', 'fischkunde_und_hege',
    ['Welcher kleine Grundfisch hat eine stachelige Rückenflosse und lebt in Schwärmen am Gewässergrund?',
     'Which small bottom-dwelling fish has a spiny dorsal fin and lives in shoals near the bottom?',
     'Qual peixinho de fundo tem nadadeira dorsal espinhosa e vive em cardumes junto ao fundo?'],
    [['Der Kaulbarsch', 'The ruffe', 'O rufe'],
     ['Der Hecht', 'The pike', 'O lúcio'],
     ['Die Äsche', 'The grayling', 'O timalo']],
    0,
    ['Der Kaulbarsch (Gymnocephalus cernua) ist ein kleiner Grundfisch mit stacheliger Rückenflosse, der in Schwärmen lebt und sich von Kleintieren ernährt.',
     'The ruffe (Gymnocephalus cernua) is a small bottom fish with a spiny dorsal fin that lives in shoals and feeds on small animals.',
     'O rufe (Gymnocephalus cernua) é um peixinho de fundo com nadadeira dorsal espinhosa, que vive em cardumes e se alimenta de pequenos animais.'],
    ['artenbestimmung'], ['kaulbarsch']],

  ['bbg-021', 'fischkunde_und_hege',
    ['Welcher Fisch hat eine grünlich braune Färbung mit dunklen Punkten und wird auch \u201eBachforelle\u201c genannt?',
     'Which fish has a greenish brown colouring with dark spots and is also called \u201cbrown trout\u201d?',
     'Qual peixe tem coloração marrom-esverdeada com pontos escuros e também é chamado de \u201ctruta-marrom\u201d?'],
    [['Die Bachforelle', 'The brown trout', 'A truta-marrom'],
     ['Der Aal', 'The eel', 'A enguia'],
     ['Die Plötze', 'The roach', 'A barata']],
    0,
    ['Die Bachforelle (Salmo trutta fario) hat eine bräunliche Färbung mit roten und schwarzen Punkten. Sie lebt in sauerstoffreichen, kühlen Gewässern.',
     'The brown trout (Salmo trutta fario) has a brownish colouring with red and black spots. It lives in cool, oxygen-rich waters.',
     'A truta-marrom (Salmo trutta fario) tem coloração acastanhada com pontos vermelhos e pretos. Vive em águas frias e ricas em oxigênio.'],
    ['artenbestimmung'], ['forelle']],

  ['bbg-022', 'fischkunde_und_hege',
    ['Welcher Raubfisch hat dunkle Querbinden auf dem Körper und rötliche Bauchflossen?',
     'Which predatory fish has dark vertical bars on its body and reddish pelvic fins?',
     'Qual peixe predador tem faixas verticais escuras no corpo e nadadeiras pélvicas avermelhadas?'],
    [['Der Barsch', 'The perch', 'A perca'],
     ['Der Zander', 'The pikeperch', 'O lúcio-perca'],
     ['Der Karpfen', 'The carp', 'A carpa']],
    0,
    ['Der Flussbarsch (Perca fluviatilis) trägt dunkle Querbinden an den Flanken und rötliche Bauch- und Afterflossen. Er hat zwei getrennte Rückenflossen.',
     'The European perch (Perca fluviatilis) has dark vertical bars on its flanks and reddish pelvic and anal fins. It has two separate dorsal fins.',
     'A perca (Perca fluviatilis) tem faixas verticais escuras nos flancos e nadadeiras pélvicas e anal avermelhadas. Tem duas nadadeiras dorsais separadas.'],
    ['artenbestimmung', 'raubfisch'], ['barsch']],

  ['bbg-023', 'fischkunde_und_hege',
    ['Welcher Karpfenfisch hat nur wenige, große Schuppen und wird als \u201eSpiegelkarpfen\u201c bezeichnet?',
     'Which carp-like fish has only a few large scales and is called \u201cmirror carp\u201d?',
     'Qual peixe da família da carpa tem poucas escamas grandes e é chamado de \u201ccarpa-espelho\u201d?'],
    [['Der Spiegelkarpfen', 'The mirror carp', 'A carpa-espelho'],
     ['Die Rotfeder', 'The rudd', 'O rudinho'],
     ['Der Kaulbarsch', 'The ruffe', 'O rufe']],
    0,
    ['Beim Spiegelkarpfen sind die Schuppen stark reduziert; er trägt nur wenige große Schuppen. Die Rotfeder hat dagegen ein vollständiges Schuppenkleid.',
     'In the mirror carp the scales are strongly reduced; it carries only a few large scales. The rudd, in contrast, has a complete covering of scales.',
     'Na carpa-espelho as escamas são bastante reduzidas; ela tem apenas algumas escamas grandes. O rudinho, ao contrário, tem cobertura completa de escamas.'],
    ['artenbestimmung', 'friedfisch'], ['karpfen']],

  ['bbg-024', 'fischkunde_und_hege',
    ['Welcher Fisch hat ein unterständiges Maul, vier Barteln und einen lang gestreckten Körper?',
     'Which fish has an inferior mouth, four barbels and an elongated body?',
     'Qual peixe tem boca inferior, quatro barbilhões e corpo alongado?'],
    [['Die Barbe', 'The barbel', 'O barbo'],
     ['Der Hecht', 'The pike', 'O lúcio'],
     ['Die Äsche', 'The grayling', 'O timalo']],
    0,
    ['Die Barbe (Barbus barbus) hat ein unterständiges Maul mit vier Barteln und einen lang gestreckten Körper. Sie lebt in der Strömung von Fließgewässern.',
     'The barbel (Barbus barbus) has an inferior mouth with four barbels and an elongated body. It lives in the current of running waters.',
     'O barbo (Barbus barbus) tem boca inferior com quatro barbilhões e corpo alongado. Vive na correnteza de rios.'],
    ['artenbestimmung', 'fliesgewaesser'], ['barbe']],

  ['bbg-025', 'fischkunde_und_hege',
    ['Welcher Fisch hat einen keilförmigen Kopf, einen langen Körper und einen einzelnen Bartel am Kinn?',
     'Which fish has a wedge-shaped head, a long body and a single barbel on its chin?',
     'Qual peixe tem cabeça em forma de cunha, corpo longo e um único barbilhão no queixo?'],
    [['Die Quappe', 'The burbot', 'A lota'],
     ['Der Karpfen', 'The carp', 'A carpa'],
     ['Die Rotfeder', 'The rudd', 'O rudinho']],
    0,
    ['Die Quappe (Lota lota) ist die einzige heimische dorschartige Süßwasserfischart und besitzt einen einzelnen Bartel am Kinn. Sie laicht im Winter.',
     'The burbot (Lota lota) is the only native freshwater fish of the cod family and has a single chin barbel. It spawns in winter.',
     'A lota (Lota lota) é a única espécie nativa de água doce da família dos bacalhaus e tem um único barbilhão no queixo. Desova no inverno.'],
    ['artenbestimmung'], ['quappe']],

  ['bbg-026', 'fischkunde_und_hege',
    ['Welcher Raubfisch ähnelt dem Barsch, hat aber ein endständiges Maul und ist im Gegensatz zum Barsch meist größer und gestreckter?',
     'Which predatory fish resembles the perch but has a terminal mouth and is usually larger and more elongated than the perch?',
     'Qual peixe predador se parece com a perca, mas tem boca terminal e, ao contrário da perca, costuma ser maior e mais alongado?'],
    [['Der Zander', 'The pikeperch', 'O lúcio-perca'],
     ['Der Karpfen', 'The carp', 'A carpa'],
     ['Die Plötze', 'The roach', 'A barata']],
    0,
    ['Zander und Barsch gehören zu den Barschartigen. Der Zander ist jedoch größer, gestreckter und hat ein endständiges Maul mit großen Zähnen.',
     'Pikeperch and perch belong to the perch family. The pikeperch is larger and more elongated, however, and has a terminal mouth with large teeth.',
     'O lúcio-perca e a perca pertencem à mesma família. O lúcio-perca, porém, é maior e mais alongado e tem boca terminal com dentes grandes.'],
    ['artenbestimmung', 'raubfisch'], ['zander', 'barsch']],

  ['bbg-027', 'fischkunde_und_hege',
    ['Welcher Friedfisch hat große, silbrig glänzende Schuppen und ein endständiges Maul?',
     'Which coarse fish has large, silvery shining scales and a terminal mouth?',
     'Qual peixe não predador tem escamas grandes e brilhantes prateadas e boca terminal?'],
    [['Der Aland', 'The ide', 'O ide'],
     ['Die Quappe', 'The burbot', 'A lota'],
     ['Der Wels', 'The catfish', 'O siluro']],
    0,
    ['Der Aland (Leuciscus idus) hat große, silbrige Schuppen und ein endständiges Maul. Er kommt in Flüssen und großen Seen vor.',
     'The ide (Leuciscus idus) has large silvery scales and a terminal mouth. It occurs in rivers and large lakes.',
     'O ide (Leuciscus idus) tem escamas grandes e prateadas e boca terminal. Ocorre em rios e grandes lagos.'],
    ['artenbestimmung', 'friedfisch'], ['aland']],

  ['bbg-028', 'fischkunde_und_hege',
    ['Welcher Raubfisch mit tief gespaltenem, oberständigem Maul jagt bevorzugt an der Wasseroberfläche?',
     'Which predatory fish with a deeply cleft, superior mouth hunts preferably at the water surface?',
     'Qual peixe predador com boca superior e profundamente fendida caça preferencialmente na superfície da água?'],
    [['Der Rapfen', 'The asp', 'O asp'],
     ['Die Schleie', 'The tench', 'A tenca'],
     ['Der Kaulbarsch', 'The ruffe', 'O rufe']],
    0,
    ['Der Rapfen (Aspius aspius) hat ein oberständiges, tief gespaltenes Maul und jagt an der Oberfläche nach Schwarmfischen. Schleie und Kaulbarsch sind keine Oberflächenjäger.',
     'The asp (Aspius aspius) has a superior, deeply cleft mouth and hunts shoaling fish at the surface. Tench and ruffe are not surface hunters.',
     'O asp (Aspius aspius) tem boca superior e profundamente fendida e caça peixes de cardume na superfície. A tenca e o rufe não caçam na superfície.'],
    ['artenbestimmung', 'raubfisch'], ['rapfen']],

  ['bbg-029', 'fischkunde_und_hege',
    ['Welcher Friedfisch hat einen hohen Körper, kleine Schuppen und rötlich gefärbte Brustflossen?',
     'Which coarse fish has a deep body, small scales and reddish coloured pectoral fins?',
     'Qual peixe não predador tem corpo alto, escamas pequenas e nadadeiras peitorais avermelhadas?'],
    [['Die Güster', 'The white bream', 'A brema-branca'],
     ['Der Hecht', 'The pike', 'O lúcio'],
     ['Der Wels', 'The catfish', 'O siluro']],
    0,
    ['Die Güster (Blicca bjoerkna) hat einen hohen Körper mit kleinen Schuppen und rötliche Brustflossen. Sie ähnelt dem Blei, hat aber eine kürzere Afterflosse.',
     'The white bream (Blicca bjoerkna) has a deep body with small scales and reddish pectoral fins. It resembles the bream but has a shorter anal fin.',
     'A brema-branca (Blicca bjoerkna) tem corpo alto com escamas pequenas e nadadeiras peitorais avermelhadas. Parece a brema, mas tem nadadeira anal mais curta.'],
    ['artenbestimmung', 'friedfisch'], ['guster']],

  ['bbg-030', 'fischkunde_und_hege',
    ['Welcher heimische Fisch hat eine gelbgrüne bis bräunliche Färbung, kleine runde Schuppen und rötliche Augen?',
     'Which native fish has a yellowish green to brownish colouring, small round scales and reddish eyes?',
     'Qual peixe nativo tem coloração verde-amarelada a acastanhada, escamas pequenas e redondas e olhos avermelhados?'],
    [['Die Plötze', 'The roach', 'A barata'],
     ['Der Wels', 'The catfish', 'O siluro'],
     ['Der Hecht', 'The pike', 'O lúcio']],
    0,
    ['Die Plötze (Rutilus rutilus), auch Rotauge genannt, hat kleine Schuppen und rötliche Augen. Sie ist ein häufiger Schwarmfisch in vielen Gewässern.',
     'The roach (Rutilus rutilus) has small scales and reddish eyes. It is a common shoaling fish in many waters.',
     'A barata (Rutilus rutilus), também chamada de Rotauge, tem escamas pequenas e olhos avermelhados. É um peixe de cardume comum em muitas águas.'],
    ['artenbestimmung', 'friedfisch'], ['plotze']],
]
