// Category: fischkunde_und_hege — Fish science & care (2/2)
export const questions = [
  // --- biology ---
  ['bbg-031', 'fischkunde_und_hege',
    ['In welcher Jahreszeit laicht der Hecht in der Regel?',
     'In which season does the pike usually spawn?',
     'Em qual estação o lúcio normalmente desova?'],
    [['Im Frühjahr', 'In spring', 'Na primavera'],
     ['Im Hochsommer', 'In midsummer', 'No auge do verão'],
     ['Im Spätherbst', 'In late autumn', 'No final do outono']],
    0,
    ['Der Hecht laicht im zeitigen Frühjahr (etwa Februar bis April) in flachen, pflanzenreichen Uferzonen und überschwemmten Wiesen.',
     'The pike spawns in early spring (roughly February to April) in shallow, weed-rich shore zones and flooded meadows.',
     'O lúcio desova no início da primavera (cerca de fevereiro a abril) em zonas rasas e ricas em vegetação, e em prados alagados.'],
    ['biologie', 'laichzeit'], ['hecht']],

  ['bbg-032', 'fischkunde_und_hege',
    ['Welche der folgenden Fische zählen zu den Raubfischen?',
     'Which of the following fish are considered predatory fish?',
     'Quais dos seguintes peixes são considerados peixes predadores?'],
    [['Hecht, Zander, Wels', 'Pike, pikeperch, catfish', 'Lúcio, lúcio-perca, siluro'],
     ['Karpfen, Schleie, Plötze', 'Carp, tench, roach', 'Carpa, tenca, barata'],
     ['Blei, Rotfeder, Ukelei', 'Bream, rudd, bleak', 'Brema, rudinho, alburno']],
    0,
    ['Hecht, Zander und Wels jagen aktiv andere Fische und gelten als Raubfische. Karpfen, Schleie und Plötze sowie Blei, Rotfeder und Ukelei sind Friedfische.',
     'Pike, pikeperch and catfish actively hunt other fish and count as predatory fish. Carp, tench and roach as well as bream, rudd and bleak are coarse fish.',
     'O lúcio, o lúcio-perca e o siluro caçam ativamente outros peixes e são predadores. Carpa, tenca e barata, assim como brema, rudinho e alburno, são peixes não predadores.'],
    ['biologie', 'raubfisch'], ['hecht', 'zander', 'wels']],

  ['bbg-033', 'fischkunde_und_hege',
    ['Was bedeutet der Begriff \u201eFriedfisch\u201c?',
     'What does the term \u201ccoarse fish\u201c mean?',
     'O que significa o termo \u201cpeixe não predador\u201d?'],
    [['Ein Fisch, der sich überwiegend von Pflanzen und Kleintieren ernährt und nicht räuberisch lebt', 'A fish that feeds mainly on plants and small animals and does not live as a predator', 'Um peixe que se alimenta principalmente de plantas e pequenos animais e não vive como predador'],
     ['Ein Fisch, der ausschließlich andere Fische jagt', 'A fish that hunts only other fish', 'Um peixe que caça apenas outros peixes'],
     ['Ein Fisch, der nur in stillen Gewässern lebt', 'A fish that lives only in still waters', 'Um peixe que vive apenas em águas paradas']],
    0,
    ['Friedfische wie Karpfen, Plötze und Schleie ernähren sich überwiegend von pflanzlicher Kost und Kleintieren. Raubfische wie Hecht und Zander jagen dagegen aktiv andere Fische.',
     'Coarse fish such as carp, roach and tench feed mainly on plant food and small animals. Predatory fish such as pike and pikeperch, on the other hand, actively hunt other fish.',
     'Peixes não predadores como carpa, barata e tenca se alimentam principalmente de plantas e pequenos animais. Predadores como lúcio e lúcio-perca, ao contrário, caçam ativamente outros peixes.'],
    ['biologie', 'friedfisch'], ['karpfen', 'schleie', 'plotze']],

  ['bbg-034', 'fischkunde_und_hege',
    ['Wie oft laicht der Karpfen in unseren Breiten in der Regel pro Jahr?',
     'How often does the carp usually spawn in our latitudes per year?',
     'Quantas vezes por ano a carpa normalmente desova em nossas latitudes?'],
    [['Einmal pro Jahr', 'Once a year', 'Uma vez por ano'],
     ['Zweimal pro Jahr', 'Twice a year', 'Duas vezes por ano'],
     ['Mehrmals pro Monat', 'Several times a month', 'Várias vezes por mês']],
    0,
    ['Der Karpfen laicht in der Regel einmal pro Jahr, meist zwischen Mai und Juli, an flachen, pflanzenreichen Stellen.',
     'The carp usually spawns once a year, mostly between May and July, in shallow, weed-rich places.',
     'A carpa normalmente desova uma vez por ano, geralmente entre maio e julho, em locais rasos e ricos em vegetação.'],
    ['biologie', 'laichzeit'], ['karpfen']],

  ['bbg-035', 'fischkunde_und_hege',
    ['Was versteht man unter \u201eAufwuchs\u201c im Gewässer?',
     'What is meant by \u201cperiphyton\u201c (Aufwuchs) in a water body?',
     'O que se entende por \u201cAufwuchs\u201d (perifíton) em um corpo d\u2019água?'],
    [['Festsitzende Algen und Kleintiere auf Pflanzen und Steinen, die vielen Fischen als Nahrung dienen', 'Attached algae and small animals on plants and stones that serve as food for many fish', 'Algas e pequenos animais fixados em plantas e pedras, que servem de alimento para muitos peixes'],
     ['Schwebende Kleinstlebewesen im freien Wasser', 'Tiny organisms floating in open water', 'Pequenos organismos flutuando em águas abertas'],
     ['Abgestorbene Fische am Gewässerboden', 'Dead fish on the bottom', 'Peixes mortos no fundo']],
    0,
    ['Aufwuchs bezeichnet festsitzende Algen und Kleintiergemeinschaften an Pflanzen, Steinen und Holz. Er ist eine wichtige Nahrungsgrundlage vieler Friedfische.',
     'Periphyton (Aufwuchs) refers to attached algae and small animal communities on plants, stones and wood. It is an important food basis for many coarse fish.',
     'O perifíton (Aufwuchs) designa comunidades de algas e pequenos animais fixadas em plantas, pedras e madeira. É uma base alimentar importante para muitos peixes não predadores.'],
    ['biologie', 'nahrung'], ['karpfen', 'plotze']],

  ['bbg-036', 'fischkunde_und_hege',
    ['Wovon ernährt sich der Zander hauptsächlich?',
     'What does the pikeperch mainly feed on?',
     'Do que o lúcio-perca se alimenta principalmente?'],
    [['Von Schwarmfischen wie Plötze und Ukelei', 'Of shoaling fish such as roach and bleak', 'De peixes de cardume como barata e alburno'],
     ['Ausschließlich von Wasserpflanzen', 'Exclusively of water plants', 'Exclusivamente de plantas aquáticas'],
     ['Nur von Insekten an der Oberfläche', 'Only of insects at the surface', 'Apenas de insetos na superfície']],
    0,
    ['Der Zander ist ein Raubfisch, der sich vor allem von Schwarmfischen ernährt. Dank seiner guten Augen jagt er auch bei schlechter Sicht.',
     'The pikeperch is a predatory fish that feeds mainly on shoaling fish. Thanks to its good eyes it hunts even in poor visibility.',
     'O lúcio-perca é um predador que se alimenta principalmente de peixes de cardume. Graças à boa visão, caça mesmo com pouca visibilidade.'],
    ['biologie', 'ernaehrung'], ['zander', 'plotze', 'ukelei']],

  ['bbg-037', 'fischkunde_und_hege',
    ['Welche Fische sind typische Schwarmfische?',
     'Which fish are typical shoaling fish?',
     'Quais peixes são típicos de cardume?'],
    [['Plötze, Ukelei und Rotfeder', 'Roach, bleak and rudd', 'Barata, alburno e rudinho'],
     ['Hecht, Zander und Wels', 'Pike, pikeperch and catfish', 'Lúcio, lúcio-perca e siluro'],
     ['Quappe, Aal und Barbe', 'Burbot, eel and barbel', 'Lota, enguia e barbo']],
    0,
    ['Plötze, Ukelei und Rotfeder bilden große Schwärme. Raubfische wie Hecht, Zander und Wels leben dagegen einzelgängerisch.',
     'Roach, bleak and rudd form large shoals. Predatory fish such as pike, pikeperch and catfish, on the other hand, live solitarily.',
     'Barata, alburno e rudinho formam grandes cardumes. Predadores como lúcio, lúcio-perca e siluro, ao contrário, vivem solitários.'],
    ['biologie', 'schwarmfisch'], ['plotze', 'ukelei', 'rotfeder']],

  ['bbg-038', 'fischkunde_und_hege',
    ['Warum sind Wasserpflanzen für Jungfische so wichtig?',
     'Why are water plants so important for young fish?',
     'Por que as plantas aquáticas são tão importantes para os peixes jovens?'],
    [['Sie bieten Schutz vor Raubfischen und sind Laichsubstrat', 'They offer protection from predatory fish and serve as spawning substrate', 'Elas oferecem proteção contra peixes predadores e servem de substrato para desova'],
     ['Sie erzeugen nachts Sauerstoff', 'They produce oxygen at night', 'Elas produzem oxigênio à noite'],
     ['Sie verhindern die Vermehrung der Fische', 'They prevent the reproduction of fish', 'Elas impedem a reprodução dos peixes']],
    0,
    ['Pflanzenreiche Flachwasserzonen sind Kinderstube der Fische: Sie bieten Deckung vor Räubern und dienen vielen Arten als Laichsubstrat. Nachts verbrauchen Pflanzen Sauerstoff.',
     'Weed-rich shallow zones are the nursery of fish: they offer cover from predators and serve many species as spawning substrate. At night plants consume oxygen.',
     'As zonas rasas com vegetação são o berçário dos peixes: oferecem abrigo contra predadores e servem de substrato de desova para muitas espécies. À noite, as plantas consomem oxigênio.'],
    ['biologie', 'hege'], ['hecht', 'karpfen']],

  ['bbg-039', 'fischkunde_und_hege',
    ['Wo laicht der Hecht bevorzugt?',
     'Where does the pike preferably spawn?',
     'Onde o lúcio prefere desovar?'],
    [['In flachen, überschwemmten Wiesen und pflanzenreichen Uferzonen', 'In shallow flooded meadows and weed-rich shore zones', 'Em prados rasos alagados e zonas de margem ricas em vegetação'],
     ['In tiefen, strömungsreichen Flussmitten', 'In deep, fast-flowing river channels', 'No meio profundo e de forte correnteza dos rios'],
     ['Auf kiesigem Grund in großer Tiefe', 'On gravelly ground at great depth', 'Em fundo de cascalho em grande profundidade']],
    0,
    ['Der Hecht laicht im zeitigen Frühjahr in flachen, überströmten und pflanzenreichen Bereichen, häufig in Überschwemmungsgebieten. Diese Laichplätze sind für den Bestand entscheidend.',
     'The pike spawns in early spring in shallow, flooded and weed-rich areas, often in floodplains. These spawning grounds are crucial for the population.',
     'O lúcio desova no início da primavera em áreas rasas, alagadas e ricas em vegetação, frequentemente em planícies de inundação. Esses locais de desova são decisivos para a população.'],
    ['biologie', 'laichzeit', 'hege'], ['hecht']],

  ['bbg-040', 'fischkunde_und_hege',
    ['Was versteht man unter der \u201eLaichzeit\u201c eines Fisches?',
     'What is meant by the \u201cspawning season\u201c of a fish?',
     'O que se entende por \u201cépoca de desova\u201d de um peixe?'],
    [['Den Zeitraum, in dem die Fische ablaichen', 'The period in which the fish spawn', 'O período em que os peixes desovam'],
     ['Die Zeit, in der die Fische wachsen', 'The time in which the fish grow', 'O tempo em que os peixes crescem'],
     ['Die Zeit, in der die Fische überwintern', 'The time in which the fish hibernate', 'O tempo em que os peixes hibernam']],
    0,
    ['Die Laichzeit ist der jahreszeitlich feste Zeitraum, in dem die Fische ihre Eier ablegen. Viele Arten haben in dieser Zeit Schonzeit.',
     'The spawning season is the fixed seasonal period in which fish lay their eggs. Many species have a closed season during this time.',
     'A época de desova é o período sazonal fixo em que os peixes põem seus ovos. Muitas espécies têm defeso nesse período.'],
    ['biologie', 'laichzeit'], ['hecht', 'zander']],

  ['bbg-041', 'fischkunde_und_hege',
    ['Warum wachsen Fische in nährstoffreichen, warmen Gewässern oft schneller?',
     'Why do fish often grow faster in nutrient-rich, warm waters?',
     'Por que os peixes costumam crescer mais rápido em águas quentes e ricas em nutrientes?'],
    [['Weil mehr Nahrung vorhanden ist und der Stoffwechsel bei Wärme schneller läuft', 'Because more food is available and metabolism speeds up with warmth', 'Porque há mais alimento disponível e o metabolismo acelera com o calor'],
     ['Weil sie dort weniger Sauerstoff brauchen', 'Because they need less oxygen there', 'Porque precisam de menos oxigênio ali'],
     ['Weil warmes Wasser mehr Sauerstoff enthält', 'Because warm water contains more oxygen', 'Porque a água quente contém mais oxigênio']],
    0,
    ['Warmes, nährstoffreiches Wasser bietet reichlich Nahrung und beschleunigt den Stoffwechsel der Fische. Allerdings sinkt der Sauerstoffgehalt bei Wärme.',
     'Warm, nutrient-rich water offers abundant food and speeds up the metabolism of fish. However, the oxygen content drops with warmth.',
     'A água quente e rica em nutrientes oferece alimento abundante e acelera o metabolismo dos peixes. Porém, o teor de oxigênio cai com o calor.'],
    ['biologie', 'wachstum'], ['karpfen']],

  ['bbg-042', 'fischkunde_und_hege',
    ['Welcher Sinn ist bei vielen Raubfischen für die Jagd in trübem Wasser entscheidend?',
     'Which sense is crucial for many predatory fish when hunting in murky water?',
     'Qual sentido é decisivo para muitos peixes predadores caçarem em água turva?'],
    [['Das Seitenlinienorgan und der Geruchssinn', 'The lateral line organ and the sense of smell', 'O órgão da linha lateral e o olfato'],
     ['Das Gehör über die Ohrmuscheln', 'Hearing via the outer ears', 'A audição pelas orelhas'],
     ['Der Tastsinn der Schuppen', 'The sense of touch of the scales', 'O tato das escamas']],
    0,
    ['Fische besitzen kein äußeres Ohr, dafür ein hoch entwickeltes Seitenlinienorgan, das Druckwellen wahrnimmt. Zusammen mit dem Geruchssinn ermöglicht es die Jagd auch bei trübem Wasser.',
     'Fish have no outer ear but a highly developed lateral line organ that senses pressure waves. Together with the sense of smell it enables hunting even in murky water.',
     'Os peixes não têm orelha externa, mas possuem um órgão de linha lateral muito desenvolvido que percebe ondas de pressão. Junto com o olfato, permite caçar mesmo em água turva.'],
    ['biologie', 'sinnesorgane'], ['wels', 'zander']],

  ['bbg-043', 'fischkunde_und_hege',
    ['Welche Funktion hat die Fettflosse bei Forellen?',
     'What function does the adipose fin have in trout?',
     'Qual é a função da nadadeira adiposa nas trutas?'],
    [['Ihre genaue Funktion ist nicht vollständig geklärt; sie ist ein typisches Erkennungsmerkmal der Salmoniden', 'Its exact function is not fully understood; it is a typical identification feature of salmonids', 'Sua função exata não é totalmente conhecida; é uma característica típica dos salmonídeos'],
     ['Sie dient als Hauptantrieb', 'It serves as the main propulsion', 'Ela serve como propulsão principal'],
     ['Sie speichert Luft für tiefe Tauchgänge', 'It stores air for deep dives', 'Ela armazena ar para mergulhos profundos']],
    0,
    ['Die kleine Fettflosse hat vermutlich eine sensorische Funktion und ist ein typisches Merkmal der Salmoniden wie Bachforelle und Äsche. Der Antrieb erfolgt über die Schwanzflosse.',
     'The small adipose fin probably has a sensory function and is a typical feature of salmonids such as brown trout and grayling. Propulsion comes from the tail fin.',
     'A pequena nadadeira adiposa provavelmente tem função sensorial e é uma característica típica dos salmonídeos, como truta-marrom e timalo. A propulsão vem da nadadeira caudal.'],
    ['anatomie', 'artenbestimmung'], ['forelle', 'asche']],

  ['bbg-044', 'fischkunde_und_hege',
    ['Was versteht man unter dem Begriff \u201eStandorttreue\u201c bei Fischen?',
     'What is meant by \u201csite fidelity\u201d in fish?',
     'O que se entende por \u201cfidelidade ao local\u201d nos peixes?'],
    [['Dass Fische über längere Zeit an einem bestimmten Gewässerabschnitt bleiben', 'That fish stay in a particular stretch of water over a longer period', 'Que os peixes permanecem por um período prolongado em um determinado trecho da água'],
     ['Dass Fische ständig wandern', 'That fish migrate constantly', 'Que os peixes migram constantemente'],
     ['Dass Fische sich nur am Gewässergrund aufhalten', 'That fish only stay near the bottom', 'Que os peixes ficam apenas no fundo']],
    0,
    ['Viele Fische, zum Beispiel Hecht und Zander, sind standorttreu und bewohnen über längere Zeit denselben Gewässerabschnitt, sofern die Bedingungen passen.',
     'Many fish, for example pike and pikeperch, are site-faithful and inhabit the same stretch of water over a longer period, as long as the conditions fit.',
     'Muitos peixes, como lúcio e lúcio-perca, são fiéis ao local e habitam o mesmo trecho de água por um período prolongado, desde que as condições sejam adequadas.'],
    ['biologie', 'verhalten'], ['hecht', 'zander']],

  ['bbg-045', 'fischkunde_und_hege',
    ['Warum steht der Aal unter besonderem Schutz?',
     'Why is the eel under special protection?',
     'Por que a enguia está sob proteção especial?'],
    [['Weil sein Bestand stark zurückgegangen ist und die Art als gefährdet gilt', 'Because its population has declined sharply and the species is considered endangered', 'Porque sua população caiu fortemente e a espécie é considerada ameaçada'],
     ['Weil er sich sehr schnell vermehrt', 'Because it reproduces very quickly', 'Porque se reproduz muito rapidamente'],
     ['Weil er keine natürlichen Feinde hat', 'Because it has no natural enemies', 'Porque não tem inimigos naturais']],
    0,
    ['Der Bestand des Europäischen Aals ist durch Überfischung, Hindernisse bei der Wanderung und Lebensraumverlust stark gesunken. Deshalb gelten besondere Schutz- und Mindestmaßregeln.',
     'The European eel population has declined sharply due to overfishing, migration obstacles and habitat loss. Special protection and minimum size rules therefore apply.',
     'A população da enguia europeia caiu fortemente devido à sobrepesca, obstáculos na migração e perda de habitat. Por isso valem regras especiais de proteção e tamanho mínimo.'],
    ['biologie', 'artenschutz'], ['aal']],

  // --- hege / stocking ---
  ['bbg-046', 'fischkunde_und_hege',
    ['Was bedeutet \u201eHege\u201c in der Fischerei?',
     'What does \u201chege\u201c (stewardship) mean in fishing?',
     'O que significa \u201chege\u201c (manejo/guarda) na pesca?'],
    [['Die Pflege und Erhaltung der Fischbestände und ihrer Lebensräume', 'The care and preservation of fish stocks and their habitats', 'O cuidado e a preservação dos estoques de peixes e de seus habitats'],
     ['Das Fangen möglichst vieler Fische', 'Catching as many fish as possible', 'Pegar o máximo possível de peixes'],
     ['Das Verfüttern von Ködern an die Fische', 'Feeding bait to the fish', 'Dar iscas aos peixes']],
    0,
    ['Hege umfasst alle Maßnahmen, die der Erhaltung und Verbesserung der Fischbestände und ihrer Lebensräume dienen, zum Beispiel schonender Fang, Gewässerpflege und sinnvoller Besatz.',
     'Stewardship (Hege) covers all measures that serve to preserve and improve fish stocks and their habitats, for example sustainable fishing, water care and sensible stocking.',
     'O manejo (Hege) abrange todas as medidas que servem para preservar e melhorar os estoques de peixes e seus habitats, por exemplo pesca sustentável, cuidado das águas e povoamento sensato.'],
    ['hege'], ['hecht', 'karpfen']],

  ['bbg-047', 'fischkunde_und_hege',
    ['Wer darf in Brandenburg Fische in Gewässer einsetzen (Besatz)?',
     'Who is allowed to stock fish into waters in Brandenburg?',
     'Quem pode povoar peixes em águas em Brandemburgo?'],
    [['Der Fischereiausübungsberechtigte des Gewässers', 'The holder of the fishing right of the water', 'O titular do direito de pesca da água'],
     ['Jeder Angler nach eigenem Ermessen', 'Any angler at their own discretion', 'Qualquer pescador, a seu critério'],
     ['Nur die Feuerwehr', 'Only the fire brigade', 'Somente o corpo de bombeiros']],
    0,
    ['Das Besetzen von Gewässern ist dem Fischereiausübungsberechtigten (Eigentümer oder Pächter) vorbehalten. Angler dürfen nicht eigenmächtig Fische aussetzen.',
     'Stocking waters is reserved for the holder of the fishing right (owner or tenant). Anglers may not release fish into the water on their own authority.',
     'O povoamento de águas é reservado ao titular do direito de pesca (proprietário ou arrendatário). Pescadores não podem soltar peixes por conta própria.'],
    ['hege', 'besatz'], ['karpfen']],

  ['bbg-048', 'fischkunde_und_hege',
    ['Welche Fische eignen sich für einen sinnvollen Besatz in einem Brandenburger See?',
     'Which fish are suitable for sensible stocking in a Brandenburg lake?',
     'Quais peixes são adequados para um povoamento sensato em um lago de Brandemburgo?'],
    [['Heimische Arten, die zum Gewässer und zum Nahrungsangebot passen', 'Native species that fit the water and the food supply', 'Espécies nativas que se adequam à água e à oferta de alimento'],
     ['Immer exotische Arten, die es in Brandenburg nicht gibt', 'Always exotic species that do not occur in Brandenburg', 'Sempre espécies exóticas que não existem em Brandemburgo'],
     ['Nur Raubfische, niemals Friedfische', 'Only predatory fish, never coarse fish', 'Apenas peixes predadores, nunca não predadores']],
    0,
    ['Ein sinnvoller Besatz verwendet heimische, standortgerechte Arten in angepasster Dichte. Gebietsfremde Arten können das Ökosystem stören und heimische Fische verdrängen.',
     'Sensible stocking uses native species suited to the location at an adapted density. Non-native species can disturb the ecosystem and displace native fish.',
     'Um povoamento sensato usa espécies nativas adequadas ao local, em densidade ajustada. Espécies exóticas podem perturbar o ecossistema e deslocar peixes nativos.'],
    ['hege', 'besatz'], ['karpfen', 'zander', 'hecht']],

  ['bbg-049', 'fischkunde_und_hege',
    ['Warum ist der Besatz mit gebietsfremden Fischarten problematisch?',
     'Why is stocking with non-native fish species problematic?',
     'Por que o povoamento com espécies exóticas é problemático?'],
    [['Sie können heimische Arten verdrängen und das Ökosystem stören', 'They can displace native species and disturb the ecosystem', 'Elas podem deslocar espécies nativas e perturbar o ecossistema'],
     ['Sie wachsen immer schlechter als heimische Arten', 'They always grow worse than native species', 'Elas sempre crescem pior do que as espécies nativas'],
     ['Sie vermehren sich nie und sind nutzlos', 'They never reproduce and are useless', 'Elas nunca se reproduzem e são inúteis']],
    0,
    ['Gebietsfremde Arten haben oft keine natürlichen Feinde und können Nahrungskonkurrenz ausüben, Krankheiten einschleppen und heimische Arten verdrängen.',
     'Non-native species often have no natural enemies and can compete for food, introduce diseases and displace native species.',
     'Espécies exóticas frequentemente não têm inimigos naturais e podem competir por alimento, introduzir doenças e deslocar espécies nativas.'],
    ['hege', 'besatz', 'oekologie'], ['karpfen']],

  ['bbg-050', 'fischkunde_und_hege',
    ['Welche Aufgabe hat ein Angler im Sinne der Hege?',
     'What task does an angler have in the spirit of stewardship (Hege)?',
     'Qual é a tarefa de um pescador no espírito do manejo (Hege)?'],
    [['Schonend angeln, Schonzeiten einhalten und Müll aus dem Gewässer entfernen', 'Fish sustainably, respect closed seasons and remove litter from the water', 'Pescar de forma sustentável, respeitar os defesos e retirar lixo da água'],
     ['Möglichst viele Fische fangen, um den Bestand zu reduzieren', 'Catch as many fish as possible to reduce the stock', 'Pegar o máximo de peixes possível para reduzir o estoque'],
     ['Alle Fische unabhängig von der Größe mitnehmen', 'Take all fish regardless of size', 'Levar todos os peixes, independentemente do tamanho']],
    0,
    ['Hege beginnt beim einzelnen Angler: schonender Umgang mit den Fischen, Einhaltung von Schonzeiten und Mindestmaßen, ordentliche Entsorgung von Abfällen und Meldung von Störungen.',
     'Stewardship starts with the individual angler: careful handling of fish, respecting closed seasons and minimum sizes, proper disposal of waste and reporting of disturbances.',
     'O manejo começa com cada pescador: manejo cuidadoso dos peixes, respeito aos defesos e tamanhos mínimos, descarte correto do lixo e comunicação de irregularidades.'],
    ['hege'], ['hecht', 'zander']],

  ['bbg-051', 'fischkunde_und_hege',
    ['Was versteht man unter \u201eBestandsstützung\u201c?',
     'What is meant by \u201cstock support\u201c?',
     'O que se entende por \u201csustentação do estoque\u201d?'],
    [['Den Besatz mit Fischen, um einen schwachen Bestand zu stützen', 'Stocking with fish to support a weak population', 'O povoamento com peixes para sustentar uma população fraca'],
     ['Das Entnehmen aller Fische aus einem Gewässer', 'Removing all fish from a water body', 'A retirada de todos os peixes de um corpo d\u2019água'],
     ['Das Füttern der Fische im Winter', 'Feeding the fish in winter', 'A alimentação dos peixes no inverno']],
    0,
    ['Bestandsstützung bedeutet, einen geschwächten Bestand durch gezielten Besatz zu unterstützen, zum Beispiel nach einem Fischsterben oder bei fehlender natürlicher Vermehrung.',
     'Stock support means supporting a weakened population through targeted stocking, for example after a fish kill or when natural reproduction is lacking.',
     'Sustentação do estoque significa apoiar uma população enfraquecida por meio de povoamento direcionado, por exemplo após uma mortandade de peixes ou quando falta reprodução natural.'],
    ['hege', 'besatz'], ['karpfen', 'zander']],

  ['bbg-052', 'fischkunde_und_hege',
    ['Welche Fische gehören zu den heimischen Friedfischen Brandenburgs?',
     'Which fish belong to the native coarse fish of Brandenburg?',
     'Quais peixes pertencem aos peixes não predadores nativos de Brandemburgo?'],
    [['Karpfen, Schleie und Plötze', 'Carp, tench and roach', 'Carpa, tenca e barata'],
     ['Hecht, Zander und Wels', 'Pike, pikeperch and catfish', 'Lúcio, lúcio-perca e siluro'],
     ['Quappe, Barbe und Rapfen', 'Burbot, barbel and asp', 'Lota, barbo e asp']],
    0,
    ['Karpfen, Schleie und Plötze sind typische heimische Friedfische. Hecht, Zander und Wels sowie Quappe, Barbe und Rapfen sind dagegen Raubfische.',
     'Carp, tench and roach are typical native coarse fish. Pike, pikeperch and catfish as well as burbot, barbel and asp, on the other hand, are predatory fish.',
     'Carpa, tenca e barata são peixes não predadores nativos típicos. Lúcio, lúcio-perca e siluro, assim como lota, barbo e asp, ao contrário, são predadores.'],
    ['artenbestimmung', 'friedfisch'], ['karpfen', 'schleie', 'plotze']],

  ['bbg-053', 'fischkunde_und_hege',
    ['Warum ist die Entnahme von Raubfischen in überbesetzten Gewässern manchmal sinnvoll?',
     'Why is the removal of predatory fish sometimes sensible in overcrowded waters?',
     'Por que a retirada de peixes predadores às vezes é sensata em águas superpovoadas?'],
    [['Um eine Überpopulation zu verhindern und den Friedfischbestand zu stabilisieren', 'To prevent overpopulation and stabilise the coarse fish stock', 'Para evitar a superpopulação e estabilizar o estoque de peixes não predadores'],
     ['Um den Bestand der Raubfische vollständig auszurotten', 'To completely eradicate the predatory fish stock', 'Para erradicar completamente o estoque de predadores'],
     ['Um die Wasserpflanzen zu schützen', 'To protect the water plants', 'Para proteger as plantas aquáticas']],
    0,
    ['In überbesetzten Gewässern können zu viele Raubfische den Friedfischbestand übermäßig dezimieren. Eine kontrollierte Entnahme dient der Bestandsstabilisierung und ist Teil der Hege.',
     'In overcrowded waters too many predatory fish can decimate the coarse fish stock excessively. Controlled removal serves to stabilise the stock and is part of stewardship.',
     'Em águas superpovoadas, muitos predadores podem dizimar excessivamente o estoque de peixes não predadores. A retirada controlada serve para estabilizar o estoque e faz parte do manejo.'],
    ['hege'], ['hecht', 'zander', 'wels']],

  ['bbg-054', 'fischkunde_und_hege',
    ['Was ist ein \u201eHegeplan\u201c?',
     'What is a \u201cstewardship plan\u201c (Hegeplan)?',
     'O que é um \u201cplano de manejo\u201d (Hegeplan)?'],
    [['Ein Plan zur Bestandspflege und Nutzung eines Gewässers', 'A plan for the care and use of a water body\u2019s fish stocks', 'Um plano para o cuidado e o uso dos estoques de peixes de um corpo d\u2019água'],
     ['Ein Verzeichnis aller erlaubten Köder', 'A list of all permitted baits', 'Uma lista de todas as iscas permitidas'],
     ['Ein Plan für Angelwettbewerbe', 'A plan for fishing competitions', 'Um plano para competições de pesca']],
    0,
    ['Ein Hegeplan legt fest, wie ein Gewässer fischereilich bewirtschaftet wird: Besatz, Entnahme, Schonzeiten und Pflegemaßnahmen werden darin abgestimmt.',
     'A stewardship plan defines how a water body is managed for fishing: stocking, removal, closed seasons and care measures are coordinated in it.',
     'Um plano de manejo define como um corpo d\u2019água é administrado para a pesca: povoamento, retirada, defesos e medidas de cuidado são coordenados nele.'],
    ['hege'], ['karpfen', 'zander']],

  ['bbg-055', 'fischkunde_und_hege',
    ['Warum sollte man beim Besatz auf die Besatzdichte achten?',
     'Why should one pay attention to stocking density when stocking?',
     'Por que se deve prestar atenção à densidade de povoamento?'],
    [['Damit das Nahrungsangebot und der Lebensraum ausreichen', 'So that the food supply and habitat are sufficient', 'Para que a oferta de alimento e o habitat sejam suficientes'],
     ['Damit möglichst wenige Fische eingesetzt werden', 'So that as few fish as possible are stocked', 'Para que o mínimo possível de peixes seja introduzido'],
     ['Weil die Dichte gesetzlich immer gleich ist', 'Because the density is always the same by law', 'Porque a densidade é sempre igual por lei']],
    0,
    ['Zu hohe Besatzdichten führen zu Nahrungskonkurrenz, Wachstumsverlust und Krankheiten. Der Besatz muss an die Größe des Gewässers und sein Nahrungsangebot angepasst sein.',
     'Too high stocking densities lead to food competition, growth loss and disease. Stocking must be adapted to the size of the water and its food supply.',
     'Densidades de povoamento muito altas geram competição por alimento, perda de crescimento e doenças. O povoamento deve ser adaptado ao tamanho da água e à sua oferta de alimento.'],
    ['hege', 'besatz'], ['karpfen']],

  // --- diseases ---
  ['bbg-056', 'fischkunde_und_hege',
    ['Was ist die \u201ePockenkrankheit\u201c beim Karpfen?',
     'What is \u201ccarp pox\u201d?',
     'O que é a \u201cvariola da carpa\u201d?'],
    [['Eine Virusinfektion mit milchig-weißen, wachsartigen Flecken auf Haut und Flossen', 'A viral infection with milky white, waxy spots on the skin and fins', 'Uma infecção viral com manchas branco-leitosas e cerosas na pele e nas nadadeiras'],
     ['Eine Krankheit der Kiemen durch Sauerstoffmangel', 'A gill disease caused by oxygen deficiency', 'Uma doença das brânquias causada por falta de oxigênio'],
     ['Eine Vergiftung durch Pflanzenschutzmittel', 'Poisoning by pesticides', 'Um envenenamento por pesticidas']],
    0,
    ['Die Pockenkrankheit ist eine gutartige Viruserkrankung des Karpfens, die sich durch milchig-weiße, wachsartige Flecken zeigt. Sie ist nicht auf den Menschen übertragbar.',
     'Carp pox is a benign viral disease of carp that shows as milky white, waxy spots. It is not transmissible to humans.',
     'A varíola da carpa é uma doença viral benigna que se manifesta com manchas branco-leitosas e cerosas. Não é transmissível ao ser humano.'],
    ['krankheiten', 'gesundheit'], ['karpfen']],

  ['bbg-057', 'fischkunde_und_hege',
    ['Woran erkennt man einen kranken Fisch?',
     'How does one recognise a sick fish?',
     'Como se reconhece um peixe doente?'],
    [['An auffälligem Verhalten, verfärbten Flossen oder weißen Flecken', 'By unusual behaviour, discoloured fins or white spots', 'Por comportamento incomum, nadadeiras descoloridas ou manchas brancas'],
     ['An besonders schnellem Schwimmen', 'By particularly fast swimming', 'Por nadar especialmente rápido'],
     ['An einer besonders dunklen Färbung', 'By a particularly dark colouring', 'Por uma coloração especialmente escura']],
    0,
    ['Kranke Fische zeigen oft auffälliges Verhalten, fressen nicht, scheuern sich oder tragen sichtbare Veränderungen wie weiße Flecken, verfärbte Flossen oder aufgeblähte Bäuche.',
     'Sick fish often show unusual behaviour, stop feeding, rub themselves or carry visible changes such as white spots, discoloured fins or bloated bellies.',
     'Peixes doentes frequentemente mostram comportamento incomum, param de se alimentar, esfregam-se ou apresentam alterações visíveis como manchas brancas, nadadeiras descoloridas ou barriga inchada.'],
    ['krankheiten', 'gesundheit'], ['karpfen', 'hecht']],

  ['bbg-058', 'fischkunde_und_hege',
    ['Was ist beim Auffinden eines toten oder kranken Fisches zu tun?',
     'What should be done when finding a dead or sick fish?',
     'O que se deve fazer ao encontrar um peixe morto ou doente?'],
    [['Die zuständige Behörde oder den Fischereiausübungsberechtigten informieren', 'Inform the responsible authority or the holder of the fishing right', 'Informar a autoridade competente ou o titular do direito de pesca'],
     ['Den Fisch essen und nichts melden', 'Eat the fish and report nothing', 'Comer o peixe e não comunicar nada'],
     ['Den Fisch ins Wasser zurückwerfen', 'Throw the fish back into the water', 'Jogar o peixe de volta na água']],
    0,
    ['Tote oder kranke Fische sollten gemeldet werden, damit Ursachen wie Fischsterben oder Krankheiten erkannt werden. Man sollte sie wegen möglicher Erreger nicht ungeschützt anfassen.',
     'Dead or sick fish should be reported so that causes such as fish kills or diseases can be identified. They should not be touched unprotected because of possible pathogens.',
     'Peixes mortos ou doentes devem ser comunicados para que causas como mortandade ou doenças sejam identificadas. Não devem ser tocados sem proteção por causa de possíveis agentes patogênicos.'],
    ['krankheiten', 'gesundheit'], ['karpfen', 'hecht', 'zander']],

  ['bbg-059', 'fischkunde_und_hege',
    ['Welche Ursache haben viele Fischsterben in heißen Sommern?',
     'What causes many fish kills in hot summers?',
     'Qual é a causa de muitas mortandades de peixes em verões quentes?'],
    [['Sauerstoffmangel durch hohe Wassertemperaturen', 'Oxygen deficiency due to high water temperatures', 'Falta de oxigênio devido às altas temperaturas da água'],
     ['Zu viel Sonnenlicht für die Fische', 'Too much sunlight for the fish', 'Excesso de luz solar para os peixes'],
     ['Eine zu hohe Zahl an Wasserpflanzen', 'Too high a number of water plants', 'Um número excessivo de plantas aquáticas']],
    0,
    ['Warmes Wasser kann weniger Sauerstoff aufnehmen, gleichzeitig steigt der Sauerstoffverbrauch durch Abbauprozesse. Bei langer Hitze kommt es dadurch zu Sauerstoffmangel und Fischsterben.',
     'Warm water can hold less oxygen while oxygen consumption rises through decomposition processes. Prolonged heat therefore leads to oxygen deficiency and fish kills.',
     'A água quente retém menos oxigênio, enquanto o consumo de oxigênio aumenta com os processos de decomposição. Calor prolongado gera falta de oxigênio e mortandade de peixes.'],
    ['krankheiten', 'wasserqualitaet'], ['hecht', 'karpfen', 'zander']],

  ['bbg-060', 'fischkunde_und_hege',
    ['Warum darf man offensichtlich kranke Fische nicht zurücksetzen?',
     'Why must obviously sick fish not be released back into the water?',
     'Por que peixes visivelmente doentes não devem ser devolvidos à água?'],
    [['Weil sonst Krankheiten im Gewässer verbreitet werden', 'Because otherwise diseases would spread in the water', 'Porque senão doenças seriam espalhadas na água'],
     ['Weil sie dann schneller wachsen', 'Because they then grow faster', 'Porque então cresceriam mais rápido'],
     ['Weil sie das Wasser trüben', 'Because they cloud the water', 'Porque eles turvam a água']],
    0,
    ['Kranke Fische können Erreger im gesamten Gewässer verbreiten. Sie sollten entnommen und sachgerecht entsorgt oder der zuständigen Stelle gemeldet werden.',
     'Sick fish can spread pathogens throughout the water. They should be removed and disposed of properly or reported to the responsible authority.',
     'Peixes doentes podem espalhar agentes patogênicos por toda a água. Devem ser retirados e descartados adequadamente ou comunicados à autoridade responsável.'],
    ['krankheiten', 'gesundheit'], ['hecht', 'karpfen']],
]
