// Category: pflege_der_fischgewaesser — Care of fishing waters (2/2)
export const questions = [
  ['bbg-091', 'pflege_der_fischgewaesser',
    ['Welche Rolle spielen Kleinstlebewesen (Makrozoobenthos) am Gewässerboden?',
     'What role do tiny organisms (macrozoobenthos) on the bottom play?',
     'Qual é o papel dos pequenos organismos (macrozoobentos) no fundo da água?'],
    [['Sie sind Fischnahrung und zeigen die Wasserqualität an', 'They are fish food and indicate the water quality', 'Eles servem de alimento para os peixes e indicam a qualidade da água'],
     ['Sie verursachen Fischkrankheiten', 'They cause fish diseases', 'Eles causam doenças nos peixes'],
     ['Sie entziehen dem Wasser den gesamten Sauerstoff', 'They remove all the oxygen from the water', 'Eles retiram todo o oxigênio da água']],
    0,
    ['Kleinstlebewesen wie Insektenlarven, Würmer und Schnecken sind wichtige Fischnahrung. Ihr Artenspektrum zeigt die Gewässergüte: Viele empfindliche Arten bedeuten sauberes Wasser.',
     'Tiny organisms such as insect larvae, worms and snails are important fish food. Their species spectrum indicates the water quality: many sensitive species mean clean water.',
     'Pequenos organismos como larvas de insetos, vermes e caracóis são alimento importante para os peixes. Seu espectro de espécies indica a qualidade da água: muitas espécies sensíveis significam água limpa.'],
    ['wasserqualitaet', 'oekologie'], ['karpfen', 'barsch', 'forelle']],

  ['bbg-092', 'pflege_der_fischgewaesser',
    ['Was ist Plankton?',
     'What is plankton?',
     'O que é plâncton?'],
    [['Im Wasser schwebende, mit der Strömung treibende Kleinstorganismen', 'Tiny organisms floating in the water, drifting with the current', 'Pequenos organismos que flutuam na água, à deriva com a correnteza'],
     ['Festsitzende Pflanzen am Gewässergrund', 'Attached plants on the bottom', 'Plantas fixadas no fundo'],
     ['Steine und Kies am Gewässerboden', 'Stones and gravel on the bottom', 'Pedras e cascalho no fundo']],
    0,
    ['Plankton umfasst pflanzliches (Phytoplankton) und tierisches Plankton (Zooplankton), die frei im Wasser schweben. Es ist die Nahrungsgrundlage vieler Fische.',
     'Plankton includes plant plankton (phytoplankton) and animal plankton (zooplankton) that float freely in the water. It is the food basis of many fish.',
     'O plâncton inclui plâncton vegetal (fitoplâncton) e animal (zooplâncton) que flutua livremente na água. É a base alimentar de muitos peixes.'],
    ['wasserqualitaet', 'oekologie'], ['karpfen', 'plotze', 'ukelei']],

  ['bbg-093', 'pflege_der_fischgewaesser',
    ['Was versteht man unter der Gewässergüte?',
     'What is meant by the water quality class (Gewässergüte)?',
     'O que se entende por classe de qualidade da água (Gewässergüte)?'],
    [['Die Einstufung eines Gewässers nach seiner Belastung anhand der Lebewesen', 'The classification of a water body according to its pollution based on its organisms', 'A classificação de um corpo d\u2019água segundo sua poluição, com base nos organismos'],
     ['Die Tiefe des Gewässers', 'The depth of the water body', 'A profundidade do corpo d\u2019água'],
     ['Die Zahl der Angler am Gewässer', 'The number of anglers at the water', 'O número de pescadores na água']],
    0,
    ['Die Gewässergüte wird anhand der vorkommenden Organismen bestimmt. Saubere Gewässer beherbergen empfindliche Arten wie Bachforelle und Strudelwürmer, stark belastete nur robuste Arten.',
     'The water quality is determined by the organisms present. Clean waters host sensitive species such as brown trout and planarians, heavily polluted ones only robust species.',
     'A qualidade da água é determinada pelos organismos presentes. Águas limpas abrigam espécies sensíveis, como truta-marrom e planárias; águas muito poluídas, apenas espécies resistentes.'],
    ['wasserqualitaet', 'oekologie'], ['forelle', 'asche']],

  ['bbg-094', 'pflege_der_fischgewaesser',
    ['Welche Bedeutung haben Ufergehölze für ein Gewässer?',
     'What significance do bank trees and shrubs have for a water body?',
     'Qual é a importância das árvores e arbustos da margem para um corpo d\u2019água?'],
    [['Sie beschatten das Wasser, kühlen es und geben Struktur und Nahrung', 'They shade and cool the water and provide structure and food', 'Eles sombreiam e resfriam a água e fornecem estrutura e alimento'],
     ['Sie entziehen dem Wasser den gesamten Sauerstoff', 'They remove all the oxygen from the water', 'Eles retiram todo o oxigênio da água'],
     ['Sie verhindern das Wachstum aller Fische', 'They prevent the growth of all fish', 'Eles impedem o crescimento de todos os peixes']],
    0,
    ['Ufergehölze beschatten das Gewässer, verhindern Überhitzung und übermäßiges Algenwachstum. Laub, Äste und Wurzeln bieten Nahrung und Verstecke für Fische und Kleintiere.',
     'Bank trees shade the water, prevent overheating and excessive algal growth. Leaves, branches and roots provide food and shelter for fish and small animals.',
     'As árvores da margem sombreiam a água, evitam o superaquecimento e o crescimento excessivo de algas. Folhas, galhos e raízes oferecem alimento e abrigo a peixes e pequenos animais.'],
    ['ufer', 'oekologie'], ['forelle', 'hecht', 'zander']],

  ['bbg-095', 'pflege_der_fischgewaesser',
    ['Warum ist die Beschattung eines Gewässers wichtig?',
     'Why is the shading of a water body important?',
     'Por que o sombreamento de um corpo d\u2019água é importante?'],
    [['Sie verhindert Überhitzung und übermäßiges Algenwachstum', 'It prevents overheating and excessive algal growth', 'Ele evita o superaquecimento e o crescimento excessivo de algas'],
     ['Sie macht das Wasser trüber', 'It makes the water murkier', 'Ele deixa a água mais turva'],
     ['Sie erhöht den Nährstoffgehalt', 'It increases the nutrient content', 'Ele aumenta o teor de nutrientes']],
    0,
    ['Beschattete Gewässer erwärmen sich weniger, wodurch Sauerstoffmangel und Algenblüten seltener auftreten. Vor allem Forellenbäche profitieren von Ufergehölzen.',
     'Shaded waters warm up less, which makes oxygen deficiency and algal blooms rarer. Trout streams in particular benefit from bank trees.',
     'Águas sombreadas esquentam menos, o que torna a falta de oxigênio e as florações de algas mais raras. Riachos de trutas, em especial, se beneficiam das árvores da margem.'],
    ['ufer', 'temperatur'], ['forelle', 'asche']],

  ['bbg-096', 'pflege_der_fischgewaesser',
    ['Was versteht man unter Krautung?',
     'What is meant by weed cutting (Krautung)?',
     'O que se entende por corte de plantas aquáticas (Krautung)?'],
    [['Das Entfernen von Wasserpflanzen aus dem Gewässer', 'The removal of water plants from the water body', 'A remoção de plantas aquáticas do corpo d\u2019água'],
     ['Das Einbringen von Kies in den Gewässergrund', 'The introduction of gravel into the bottom', 'A introdução de cascalho no fundo'],
     ['Das Töten von Fischen durch Strom', 'The killing of fish by electricity', 'A matança de peixes por eletricidade']],
    0,
    ['Krautung ist die gezielte Entfernung von Wasserpflanzen, um Verkrautung und Nährstoffansammlungen zu begrenzen. Sie muss maßvoll und fischschonend erfolgen.',
     'Weed cutting is the targeted removal of water plants to limit overgrowth and nutrient accumulation. It must be moderate and fish-friendly.',
     'O corte de plantas é a remoção direcionada de plantas aquáticas para limitar o crescimento excessivo e o acúmulo de nutrientes. Deve ser moderado e respeitar os peixes.'],
    ['gewaesserpflege', 'wasserpflanzen'], ['karpfen', 'hecht']],

  ['bbg-097', 'pflege_der_fischgewaesser',
    ['Wann sollte gekrautet werden, um Fische möglichst wenig zu schädigen?',
     'When should weed cutting be done to harm fish as little as possible?',
     'Quando se deve cortar as plantas aquáticas para prejudicar o mínimo possível os peixes?'],
    [['Abschnittsweise und außerhalb der Hauptlaichzeiten', 'In sections and outside the main spawning seasons', 'Em trechos e fora das principais épocas de desova'],
     ['Während der Hauptlaichzeit im Frühjahr', 'During the main spawning season in spring', 'Durante a principal época de desova, na primavera'],
     ['Nur im Hochsommer bei voller Laichaktivität', 'Only in midsummer during full spawning activity', 'Somente no auge do verão, com total atividade de desova']],
    0,
    ['Krautung sollte abschnittsweise erfolgen, damit Rückzugsräume bleiben, und außerhalb der Laichzeiten, damit Eier und Jungfische nicht zerstört werden.',
     'Weed cutting should be done in sections so that retreat areas remain, and outside the spawning seasons so that eggs and young fish are not destroyed.',
     'O corte deve ser feito em trechos para que restem áreas de refúgio, e fora das épocas de desova para que ovos e filhotes não sejam destruídos.'],
    ['gewaesserpflege', 'wasserpflanzen'], ['hecht', 'karpfen']],

  ['bbg-098', 'pflege_der_fischgewaesser',
    ['Warum dürfen Ufer nicht flächendeckend betoniert oder mit Steinschüttungen verbaut werden?',
     'Why must banks not be concreted or built over with stone fill over wide areas?',
     'Por que as margens não podem ser concretadas ou revestidas com pedras em grandes áreas?'],
    [['Weil Lebensräume, Laichplätze und der Wasserwechsel zum Ufer zerstört werden', 'Because habitats, spawning grounds and the water exchange with the bank are destroyed', 'Porque habitats, locais de desova e a troca de água com a margem são destruídos'],
     ['Weil Beton die Fische ernährt', 'Because concrete feeds the fish', 'Porque o concreto alimenta os peixes'],
     ['Weil dadurch mehr Fische laichen', 'Because more fish spawn that way', 'Porque assim mais peixes desovam']],
    0,
    ['Verbaute Ufer verlieren ihre Funktion als Lebensraum, Laichplatz und Filter. Naturnahe Ufer mit Pflanzen und Strukturen sind für die Fischbestände unverzichtbar.',
     'Developed banks lose their function as habitat, spawning ground and filter. Natural banks with plants and structures are indispensable for fish stocks.',
     'Margens artificializadas perdem sua função de habitat, local de desova e filtro. Margens naturais com plantas e estruturas são indispensáveis para os estoques de peixes.'],
    ['ufer', 'gewaesserpflege'], ['hecht', 'zander']],

  ['bbg-099', 'pflege_der_fischgewaesser',
    ['Welche Bedeutung haben Flachwasserzonen für den Fischbestand?',
     'What significance do shallow water zones have for the fish stock?',
     'Qual é a importância das zonas de águas rasas para o estoque de peixes?'],
    [['Sie sind Aufwuchs- und Laichgebiet für viele Fischarten', 'They are nursery and spawning grounds for many fish species', 'Elas são áreas de criação e desova de muitas espécies de peixes'],
     ['Sie sind lebensfeindlich und ohne Funktion', 'They are hostile to life and without function', 'Elas são hostis à vida e sem função'],
     ['Sie verringern die Fischpopulation', 'They reduce the fish population', 'Elas reduzem a população de peixes']],
    0,
    ['Flache, pflanzenreiche Uferzonen erwärmen sich schnell, bieten reichlich Nahrung und Schutz vor Räubern. Hier wachsen die Jungfische der meisten Arten auf.',
     'Shallow, weed-rich bank zones warm up quickly, offer abundant food and protection from predators. Here the young of most species grow up.',
     'As zonas rasas e ricas em vegetação esquentam rápido, oferecem alimento abundante e proteção contra predadores. É onde os filhotes da maioria das espécies crescem.'],
    ['ufer', 'oekologie'], ['hecht', 'karpfen', 'plotze']],

  ['bbg-100', 'pflege_der_fischgewaesser',
    ['Welche Folge hat die Entwässerung von Feuchtgebieten und Überschwemmungsflächen?',
     'What is the consequence of draining wetlands and floodplains?',
     'Qual é a consequência da drenagem de áreas úmidas e planícies de inundação?'],
    [['Wichtige Laich- und Aufwuchsgebiete für Fische gehen verloren', 'Important spawning and nursery grounds for fish are lost', 'Importantes áreas de desova e criação dos peixes se perdem'],
     ['Die Fischbestände nehmen zu', 'The fish stocks increase', 'Os estoques de peixes aumentam'],
     ['Die Wasserqualität verbessert sich dauerhaft', 'The water quality improves permanently', 'A qualidade da água melhora permanentemente']],
    0,
    ['Überschwemmungsgebiete sind für Fische wie Hecht und Quappe wichtige Laichplätze. Ihre Entwässerung zerstört diese Funktion und gefährdet die Bestände.',
     'Floodplains are important spawning grounds for fish such as pike and burbot. Draining them destroys this function and endangers the stocks.',
     'As planícies de inundação são locais de desova importantes para peixes como lúcio e lota. Sua drenagem destrói essa função e ameaça os estoques.'],
    ['ufer', 'oekologie'], ['hecht', 'quappe']],

  ['bbg-101', 'pflege_der_fischgewaesser',
    ['Was versteht man unter naturnaher Gewässerunterhaltung?',
     'What is meant by nature-friendly water body maintenance?',
     'O que se entende por manutenção natural dos corpos d\u2019água?'],
    [['Pflegemaßnahmen, die die Lebensräume der Tiere und Pflanzen erhalten', 'Care measures that preserve the habitats of animals and plants', 'Medidas de cuidado que preservam os habitats de animais e plantas'],
     ['Die vollständige Beseitigung aller Pflanzen und Strukturen', 'The complete removal of all plants and structures', 'A remoção completa de todas as plantas e estruturas'],
     ['Das Betonieren aller Ufer', 'The concreting of all banks', 'A concretagem de todas as margens']],
    0,
    ['Naturnahe Unterhaltung erhält Strukturen wie Totholz, Röhricht und Kiesbänke, arbeitet abschnittsweise und zu fischschonenden Zeiten. So bleibt das Gewässer für Tiere bewohnbar.',
     'Nature-friendly maintenance preserves structures such as dead wood, reed belts and gravel bars, works in sections and at fish-friendly times. This keeps the water habitable for animals.',
     'A manutenção natural preserva estruturas como madeira morta, juncos e bancos de cascalho, trabalha em trechos e em horários que respeitam os peixes. Assim a água permanece habitável.'],
    ['gewaesserpflege', 'oekologie'], ['hecht', 'forelle']],

  ['bbg-102', 'pflege_der_fischgewaesser',
    ['Wer ist für die Unterhaltung eines Gewässers verantwortlich?',
     'Who is responsible for the maintenance of a water body?',
     'Quem é responsável pela manutenção de um corpo d\u2019água?'],
    [['Der Gewässerunterhaltungspflichtige, etwa das Land, Kommunen oder Verbände', 'The party obliged to maintain the water, such as the state, municipalities or associations', 'O obrigado à manutenção, como o estado, municípios ou associações'],
     ['Jeder Angler einzeln', 'Each angler individually', 'Cada pescador individualmente'],
     ['Niemand', 'No one', 'Ninguém']],
    0,
    ['Die Unterhaltungspflicht liegt bei den Trägern der Gewässerunterhaltung (Land, Verbände, Gemeinden). Angler können durch Meldungen und Mitarbeit unterstützen.',
     'The maintenance obligation lies with the bodies responsible for water maintenance (state, associations, municipalities). Anglers can help by reporting and taking part.',
     'A obrigação de manutenção cabe aos responsáveis (estado, associações, municípios). Os pescadores podem ajudar com comunicados e participação.'],
    ['gewaesserpflege'], ['hecht', 'zander']],

  ['bbg-103', 'pflege_der_fischgewaesser',
    ['Welche Aufgabe hat der Angler bei der Gewässerpflege?',
     'What task does the angler have in water body care?',
     'Qual é a tarefa do pescador no cuidado do corpo d\u2019água?'],
    [['Abfälle ordentlich entsorgen und Schäden oder Verschmutzungen melden', 'Dispose of waste properly and report damage or pollution', 'Descartar o lixo corretamente e comunicar danos ou poluições'],
     ['Müll ins Wasser werfen, um Fische anzulocken', 'Throw waste into the water to attract fish', 'Jogar lixo na água para atrair os peixes'],
     ['Verbotene Netze aufstellen, um den Bestand zu kontrollieren', 'Set illegal nets to control the stock', 'Instalar redes proibidas para controlar o estoque']],
    0,
    ['Jeder Angler trägt zur Gewässerpflege bei: Müll wird mitgenommen, Verschmutzungen, Fischsterben und Schäden werden gemeldet. So bleiben die Gewässer als Lebensraum erhalten.',
     'Every angler contributes to water care: waste is taken along, pollution, fish kills and damage are reported. This keeps the waters as habitat.',
     'Cada pescador contribui para o cuidado da água: o lixo é levado, e poluições, mortandades e danos são comunicados. Assim as águas permanecem como habitat.'],
    ['gewaesserpflege'], ['hecht', 'zander', 'karpfen']],

  ['bbg-104', 'pflege_der_fischgewaesser',
    ['Welche Bedeutung haben Tümpel und Altwasser für Fische?',
     'What significance do ponds and backwaters have for fish?',
     'Qual é a importância das lagoas e águas remansosas para os peixes?'],
    [['Sie dienen als Laich- und Aufwuchsgebiete sowie als Rückzugsräume', 'They serve as spawning and nursery grounds and as retreat areas', 'Elas servem como áreas de desova e criação e como refúgios'],
     ['Sie sind für Fische wertlos', 'They are worthless for fish', 'Elas não têm valor para os peixes'],
     ['Sie verringern die Artenvielfalt', 'They reduce biodiversity', 'Elas reduzem a biodiversidade']],
    0,
    ['Tümpel, Altwasser und Flutmulden sind wichtige Laich- und Jungfischhabitate. Sie bieten besonders in Flussauen Lebensraum für viele Arten.',
     'Ponds, backwaters and flood channels are important spawning and juvenile habitats. Especially in river floodplains they offer habitat for many species.',
     'Lagoas, águas remansosas e canais de inundação são habitats importantes de desova e criação. Especialmente em várzeas de rios, oferecem habitat para muitas espécies.'],
    ['oekologie', 'ufer'], ['hecht', 'karpfen']],

  ['bbg-105', 'pflege_der_fischgewaesser',
    ['Warum ist die Sauerstoffsättigung im Wasser begrenzt?',
     'Why is the oxygen saturation in water limited?',
     'Por que a saturação de oxigênio na água é limitada?'],
    [['Weil Wasser nur eine begrenzte Menge Sauerstoff lösen kann', 'Because water can only dissolve a limited amount of oxygen', 'Porque a água só consegue dissolver uma quantidade limitada de oxigênio'],
     ['Weil Fische keinen Sauerstoff brauchen', 'Because fish do not need oxygen', 'Porque os peixes não precisam de oxigênio'],
     ['Weil Sauerstoff im Wasser verboten ist', 'Because oxygen in water is forbidden', 'Porque o oxigênio na água é proibido']],
    0,
    ['Die Löslichkeit von Sauerstoff im Wasser ist begrenzt und sinkt mit steigender Temperatur. Warme Gewässer können daher weniger Sauerstoff speichern als kalte.',
     'The solubility of oxygen in water is limited and decreases with rising temperature. Warm waters can therefore store less oxygen than cold ones.',
     'A solubilidade do oxigênio na água é limitada e diminui com o aumento da temperatura. Águas quentes, portanto, podem armazenar menos oxigênio do que águas frias.'],
    ['wasserqualitaet', 'sauerstoff'], ['forelle', 'karpfen']],

  ['bbg-106', 'pflege_der_fischgewaesser',
    ['Was versteht man unter Sauerstoffzehrung?',
     'What is meant by oxygen depletion (Sauerstoffzehrung)?',
     'O que se entende por consumo de oxigênio (Sauerstoffzehrung)?'],
    [['Den Sauerstoffverbrauch durch Abbauprozesse von organischem Material', 'The consumption of oxygen by decomposition processes of organic material', 'O consumo de oxigênio pelos processos de decomposição de material orgânico'],
     ['Die Sauerstoffproduktion der Pflanzen', 'The oxygen production of the plants', 'A produção de oxigênio pelas plantas'],
     ['Das Aufsteigen von Sauerstoffblasen', 'The rising of oxygen bubbles', 'A subida de bolhas de oxigênio']],
    0,
    ['Organisches Material wie abgestorbene Algen oder Laub wird von Bakterien zersetzt, die dabei Sauerstoff verbrauchen. Hohe Zehrung kann zu Sauerstoffmangel führen.',
     'Organic material such as dead algae or leaves is decomposed by bacteria that consume oxygen in the process. High depletion can lead to oxygen deficiency.',
     'Material orgânico, como algas mortas ou folhas, é decomposto por bactérias que consomem oxigênio no processo. Alto consumo pode levar à falta de oxigênio.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'karpfen']],

  ['bbg-107', 'pflege_der_fischgewaesser',
    ['Warum ist eine hohe Sichttiefe (klares Wasser) meist ein Zeichen für ein gesundes Gewässer?',
     'Why is a high Secchi depth (clear water) usually a sign of a healthy water body?',
     'Por que uma alta transparência da água (água clara) costuma ser sinal de um corpo d\u2019água saudável?'],
    [['Weil wenig Schwebstoffe und keine Algenblüten das Wasser eintrüben', 'Because few suspended solids and no algal blooms cloud the water', 'Porque poucos sólidos em suspensão e nenhuma floração de algas turvam a água'],
     ['Weil klares Wasser mehr Nährstoffe enthält', 'Because clear water contains more nutrients', 'Porque a água clara contém mais nutrientes'],
     ['Weil klares Wasser immer kälter ist', 'Because clear water is always colder', 'Porque a água clara é sempre mais fria']],
    0,
    ['Klares Wasser zeigt, dass Schwebstoffe und Algenmassen fehlen. Häufig geht das mit guter Wasserqualität und ausreichend Sauerstoff einher.',
     'Clear water shows that suspended solids and algal masses are absent. This often goes hand in hand with good water quality and sufficient oxygen.',
     'A água clara mostra que faltam sólidos em suspensão e massas de algas. Isso costuma andar junto com boa qualidade da água e oxigênio suficiente.'],
    ['wasserqualitaet', 'oekologie'], ['forelle', 'zander']],

  ['bbg-108', 'pflege_der_fischgewaesser',
    ['Was kann eine plötzliche Trübung des Wassers anzeigen?',
     'What can a sudden turbidity of the water indicate?',
     'O que uma turvação repentina da água pode indicar?'],
    [['Eingespülte Sedimente, Algenblüten oder eine Verschmutzung', 'Washed-in sediments, algal blooms or pollution', 'Sedimentos arrastados, florações de algas ou uma poluição'],
     ['Eine Zunahme der Fischbestände', 'An increase of the fish stocks', 'Um aumento dos estoques de peixes'],
     ['Eine Verbesserung der Wasserqualität', 'An improvement of the water quality', 'Uma melhora da qualidade da água']],
    0,
    ['Trübung entsteht durch Schwebstoffe, aufgewirbelte Sedimente, Algenblüten oder Schadstoffeinträge. Angler sollten auffällige Trübungen und Gerüche melden.',
     'Turbidity arises from suspended solids, stirred-up sediments, algal blooms or pollutant inputs. Anglers should report conspicuous turbidity and odours.',
     'A turvação surge de sólidos em suspensão, sedimentos revolvidos, florações de algas ou entrada de poluentes. Pescadores devem comunicar turvações e odores suspeitos.'],
    ['wasserqualitaet', 'verschmutzung'], ['hecht', 'zander']],

  ['bbg-109', 'pflege_der_fischgewaesser',
    ['Welche Tiere deuten auf ein sehr sauberes, unbelastetes Gewässer hin?',
     'Which animals indicate a very clean, unpolluted water body?',
     'Quais animais indicam um corpo d\u2019água muito limpo e sem poluição?'],
    [['Bachforelle, Strudelwürmer und Steinfliegenlarven', 'Brown trout, planarians and stonefly larvae', 'Truta-marrom, planárias e larvas de perlídeos'],
     ['Schlammröhrenwürmer und Ratten', 'Sludge worms and rats', 'Vermes de lodo e ratos'],
     ['Nur Karpfen in großen Mengen', 'Only carp in large numbers', 'Apenas carpas em grande quantidade']],
    0,
    ['Empfindliche Arten wie Bachforelle, Strudelwürmer und Steinfliegenlarven kommen nur in sauerstoffreichen, sauberen Gewässern vor. Sie gelten als Zeigerorganismen für gute Wasserqualität.',
     'Sensitive species such as brown trout, planarians and stonefly larvae occur only in oxygen-rich, clean waters. They count as indicator organisms for good water quality.',
     'Espécies sensíveis como truta-marrom, planárias e larvas de perlídeos só ocorrem em águas limpas e ricas em oxigênio. Elas são organismos indicadores de boa qualidade da água.'],
    ['wasserqualitaet', 'oekologie'], ['forelle', 'asche']],

  ['bbg-110', 'pflege_der_fischgewaesser',
    ['Was kann ein Angler bei einem akuten Fischsterben tun?',
     'What can an angler do in the event of an acute fish kill?',
     'O que um pescador pode fazer em caso de mortandade aguda de peixes?'],
    [['Die zuständige Behörde oder den Fischereiausübungsberechtigten sofort informieren', 'Immediately inform the responsible authority or the holder of the fishing right', 'Informar imediatamente a autoridade competente ou o titular do direito de pesca'],
     ['Die Fische einsammeln und verkaufen', 'Collect the fish and sell them', 'Recolher os peixes e vendê-los'],
     ['Nichts tun, da es sich von selbst löst', 'Do nothing because it resolves itself', 'Não fazer nada, pois se resolve sozinho']],
    0,
    ['Fischsterben müssen sofort gemeldet werden, damit die Ursache geklärt und Gegenmaßnahmen eingeleitet werden können. Das Mitnehmen toter Fische ist nicht erlaubt.',
     'Fish kills must be reported immediately so that the cause can be clarified and countermeasures initiated. Taking dead fish is not allowed.',
     'Mortandades devem ser comunicadas imediatamente para que a causa seja esclarecida e contramedidas sejam iniciadas. Levar peixes mortos não é permitido.'],
    ['gewaesserpflege', 'wasserqualitaet'], ['hecht', 'zander', 'karpfen']],

  ['bbg-111', 'pflege_der_fischgewaesser',
    ['Warum sind Altarme und ruhige Buchten wichtige Lebensräume?',
     'Why are backwaters and quiet bays important habitats?',
     'Por que águas remansosas e baías calmas são habitats importantes?'],
    [['Sie bieten ruhiges, pflanzenreiches Wasser als Laich- und Aufwuchsgebiet', 'They offer calm, weed-rich water as spawning and nursery grounds', 'Elas oferecem água calma e rica em vegetação como área de desova e criação'],
     ['Sie enthalten keinerlei Fische', 'They contain no fish at all', 'Elas não contêm nenhum peixe'],
     ['Sie senken die Wassertemperatur dauerhaft', 'They permanently lower the water temperature', 'Elas baixam permanentemente a temperatura da água']],
    0,
    ['Ruhige, pflanzenreiche Bereiche erwärmen sich schnell und bieten Deckung. Viele Friedfische laichen dort und Jungfische finden Schutz vor der Strömung.',
     'Calm, weed-rich areas warm up quickly and offer cover. Many coarse fish spawn there and young fish find protection from the current.',
     'Áreas calmas e ricas em vegetação esquentam rápido e oferecem abrigo. Muitos peixes não predadores desovam ali e os filhotes encontram proteção contra a correnteza.'],
    ['oekologie', 'ufer'], ['karpfen', 'hecht', 'plotze']],

  ['bbg-112', 'pflege_der_fischgewaesser',
    ['Welche Auswirkung hat ein übermäßiger Besatz mit Karpfen auf das Gewässer?',
     'What effect does excessive stocking with carp have on the water body?',
     'Qual é o efeito do povoamento excessivo com carpas no corpo d\u2019água?'],
    [['Trübung des Wassers und Schädigung der Wasserpflanzen durch Wühlen', 'Turbidity of the water and damage to the water plants through rooting', 'Turvação da água e danos às plantas aquáticas pelo revolvimento'],
     ['Eine dauerhafte Verbesserung der Wasserqualität', 'A permanent improvement of the water quality', 'Uma melhora permanente da qualidade da água'],
     ['Eine Zunahme der Sauerstoffproduktion', 'An increase in oxygen production', 'Um aumento da produção de oxigênio']],
    0,
    ['Karpfen wühlen bei der Nahrungssuche am Grund, trüben das Wasser und entwurzeln Pflanzen. Ein zu dichter Bestand kann ein Gewässer dadurch deutlich verschlechtern.',
     'Carp root around on the bottom while feeding, cloud the water and uproot plants. A stock that is too dense can noticeably worsen the water.',
     'As carpas revolvem o fundo em busca de alimento, turvam a água e arrancam as plantas. Um estoque muito denso pode piorar visivelmente a água.'],
    ['gewaesserpflege', 'besatz'], ['karpfen']],

  ['bbg-113', 'pflege_der_fischgewaesser',
    ['Welche Rolle spielen Wasserinsekten im Ökosystem Gewässer?',
     'What role do aquatic insects play in the water ecosystem?',
     'Qual é o papel dos insetos aquáticos no ecossistema aquático?'],
    [['Sie sind Fischnahrung und zeigen die Gewässergüte an', 'They are fish food and indicate the water quality', 'Eles servem de alimento para os peixes e indicam a qualidade da água'],
     ['Sie ernähren sich von Fischen', 'They feed on fish', 'Eles se alimentam de peixes'],
     ['Sie zerstören die Wasserpflanzen vollständig', 'They completely destroy the water plants', 'Eles destroem completamente as plantas aquáticas']],
    0,
    ['Wasserinsekten und ihre Larven sind eine wichtige Nahrungsquelle für Fische, besonders für Forellen. Ihr Vorkommen erlaubt Rückschlüsse auf die Wasserqualität.',
     'Aquatic insects and their larvae are an important food source for fish, especially trout. Their occurrence allows conclusions about the water quality.',
     'Os insetos aquáticos e suas larvas são uma fonte importante de alimento para os peixes, especialmente trutas. Sua ocorrência permite concluir sobre a qualidade da água.'],
    ['oekologie', 'wasserqualitaet'], ['forelle', 'asche']],

  ['bbg-114', 'pflege_der_fischgewaesser',
    ['Warum sind ausreichend große Wasservolumen und Tiefe für Fische im Winter wichtig?',
     'Why are sufficiently large water volumes and depth important for fish in winter?',
     'Por que volume e profundidade suficientes da água são importantes para os peixes no inverno?'],
    [['Weil tiefe Bereiche stabilere Temperaturen und mehr Sauerstoff bieten', 'Because deep areas offer more stable temperatures and more oxygen', 'Porque as áreas profundas oferecem temperaturas mais estáveis e mais oxigênio'],
     ['Weil Fische im Winter nur an der Oberfläche leben', 'Because fish live only at the surface in winter', 'Porque no inverno os peixes vivem apenas na superfície'],
     ['Weil flaches Wasser im Winter wärmer ist', 'Because shallow water is warmer in winter', 'Porque a água rasa é mais quente no inverno']],
    0,
    ['Tiefe Wasserschichten kühlen langsamer aus und speichern mehr Sauerstoff. Bei langer Eisbedeckung können flache Gewässer durch Sauerstoffmangel kippen.',
     'Deep water layers cool down more slowly and store more oxygen. With long ice cover, shallow waters can tip over due to oxygen deficiency.',
     'As camadas profundas esfriam mais devagar e armazenam mais oxigênio. Com cobertura de gelo prolongada, águas rasas podem entrar em colapso por falta de oxigênio.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'karpfen', 'zander']],

  ['bbg-115', 'pflege_der_fischgewaesser',
    ['Was versteht man unter einer \u201eFischwechselzone\u201c in einem Fließgewässer?',
     'What is meant by a \u201cfish exchange zone\u201c in a running water?',
     'O que se entende por \u201czona de troca de peixes\u201c em um rio?'],
    [['Den Übergangsbereich zwischen Strömung und ruhigem Wasser, in dem Fische rasten und jagen', 'The transition area between current and calm water where fish rest and hunt', 'A área de transição entre a correnteza e a água calma, onde os peixes descansam e caçam'],
     ['Einen Bereich ohne jegliches Leben', 'An area without any life', 'Uma área sem nenhuma vida'],
     ['Die tiefste Stelle des Flusses', 'The deepest point of the river', 'O ponto mais profundo do rio']],
    0,
    ['An Strömungsrändern finden Fische Schutz vor der Strömung und zugleich Zugang zu Nahrung. Solche Wechselzonen sind wichtige Aufenthaltsorte, besonders für Forellen und Äschen.',
     'At current edges fish find protection from the flow and access to food at the same time. Such exchange zones are important resting places, especially for trout and grayling.',
     'Nas bordas da correnteza, os peixes encontram proteção contra o fluxo e, ao mesmo tempo, acesso ao alimento. Essas zonas de troca são locais importantes, especialmente para trutas e timalos.'],
    ['fliesgewaesser', 'oekologie'], ['forelle', 'asche']],

  ['bbg-116', 'pflege_der_fischgewaesser',
    ['Warum sind Kiesbänke in Fließgewässern für Fische wichtig?',
     'Why are gravel bars important for fish in running waters?',
     'Por que os bancos de cascalho são importantes para os peixes nos rios?'],
    [['Sie dienen vielen Arten als Laichplatz, zum Beispiel der Äsche', 'They serve many species as spawning grounds, for example the grayling', 'Eles servem de local de desova para muitas espécies, por exemplo o timalo'],
     ['Sie verhindern jede Fortpflanzung', 'They prevent all reproduction', 'Eles impedem toda reprodução'],
     ['Sie entziehen dem Wasser Sauerstoff', 'They remove oxygen from the water', 'Eles retiram oxigênio da água']],
    0,
    ['Kiesbänke in sauberem, sauerstoffreichem Wasser sind klassische Laichplätze von Äsche, Forelle und anderen Kieslaichern. Ihre Zerstörung gefährdet die natürliche Vermehrung.',
     'Gravel bars in clean, oxygen-rich water are classic spawning grounds of grayling, trout and other gravel spawners. Destroying them endangers natural reproduction.',
     'Bancos de cascalho em água limpa e rica em oxigênio são locais clássicos de desova do timalo, da truta e de outros desovadores em cascalho. Sua destruição ameaça a reprodução natural.'],
    ['fliesgewaesser', 'oekologie'], ['asche', 'forelle']],

  ['bbg-117', 'pflege_der_fischgewaesser',
    ['Welche Wirkung hat ein zu hoher Nährstoffeintrag auf die Wasserpflanzen?',
     'What effect does an excessive nutrient input have on the water plants?',
     'Qual é o efeito do excesso de nutrientes sobre as plantas aquáticas?'],
    [['Das Wachstum von Algen nimmt explosionsartig zu, Wasserpflanzen werden verdrängt', 'The growth of algae increases explosively and water plants are displaced', 'O crescimento de algas aumenta de forma explosiva e as plantas aquáticas são deslocadas'],
     ['Die Wasserpflanzen wachsen langsamer', 'The water plants grow more slowly', 'As plantas aquáticas crescem mais devagar'],
     ['Die Wasserpflanzen verschwinden vollständig ohne Folgen', 'The water plants disappear completely without consequences', 'As plantas aquáticas desaparecem completamente sem consequências']],
    0,
    ['Hohe Nährstoffmengen fördern vor allem das Algenwachstum. Dichte Algenmassen trüben das Wasser, sodass Unterwasserpflanzen zu wenig Licht erhalten und zurückgehen.',
     'High nutrient amounts mainly promote algal growth. Dense algal masses cloud the water so that underwater plants receive too little light and decline.',
     'Grandes quantidades de nutrientes favorecem sobretudo o crescimento de algas. Massas densas de algas turvam a água, de modo que as plantas submersas recebem pouca luz e diminuem.'],
    ['eutrophierung', 'wasserpflanzen'], ['karpfen', 'hecht']],

  ['bbg-118', 'pflege_der_fischgewaesser',
    ['Warum ist es wichtig, dass Fische zu ihren Laichplätzen wandern können?',
     'Why is it important that fish can migrate to their spawning grounds?',
     'Por que é importante que os peixes possam migrar até seus locais de desova?'],
    [['Weil viele Arten ohne geeignete Laichplätze keine Nachkommen bekommen', 'Because many species produce no offspring without suitable spawning grounds', 'Porque muitas espécies não geram filhotes sem locais de desova adequados'],
     ['Weil sie sonst zu groß werden', 'Because they otherwise become too large', 'Porque senão ficam grandes demais'],
     ['Weil sie sonst die Ufer zerstören', 'Because they otherwise destroy the banks', 'Porque senão destroem as margens']],
    0,
    ['Viele Fische wandern zum Laichen in flache Uferzonen oder flussaufwärts. Sind diese Wege durch Wehre versperrt, fehlt die natürliche Vermehrung und der Bestand ist gefährdet.',
     'Many fish migrate to shallow bank zones or upstream to spawn. If these routes are blocked by weirs, natural reproduction is missing and the stock is endangered.',
     'Muitos peixes migram para zonas rasas da margem ou rio acima para desovar. Se essas rotas são bloqueadas por açudes, falta a reprodução natural e o estoque fica ameaçado.'],
    ['fliesgewaesser', 'oekologie'], ['hecht', 'asche', 'forelle']],

  ['bbg-119', 'pflege_der_fischgewaesser',
    ['Welche Gefahr besteht bei sehr niedrigem Wasserstand im Sommer?',
     'What danger exists with very low water levels in summer?',
     'Qual é o perigo com níveis de água muito baixos no verão?'],
    [['Überhitzung, Sauerstoffmangel und höhere Schadstoffkonzentrationen', 'Overheating, oxygen deficiency and higher pollutant concentrations', 'Superaquecimento, falta de oxigênio e maiores concentrações de poluentes'],
     ['Eine dauerhafte Abkühlung des Wassers', 'A permanent cooling of the water', 'Um resfriamento permanente da água'],
     ['Eine Zunahme des Fischbestands', 'An increase of the fish stock', 'Um aumento do estoque de peixes']],
    0,
    ['Niedrige Wasserstände erwärmen das Wasser schneller, verringern den Sauerstoffgehalt und konzentrieren Schadstoffe. Fische geraten in Stress und können sterben.',
     'Low water levels warm the water faster, reduce the oxygen content and concentrate pollutants. Fish come under stress and can die.',
     'Níveis baixos de água aquecem a água mais rápido, reduzem o teor de oxigênio e concentram poluentes. Os peixes entram em estresse e podem morrer.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'forelle', 'zander']],

  ['bbg-120', 'pflege_der_fischgewaesser',
    ['Warum sollte ein Angler auf das Ufer und den Gewässergrund Rücksicht nehmen?',
     'Why should an angler be considerate of the bank and the bottom of the water?',
     'Por que um pescador deve respeitar a margem e o fundo da água?'],
    [['Weil empfindliche Lebensräume sonst zerstört und Fische unnötig gestört werden', 'Because sensitive habitats would otherwise be destroyed and fish disturbed unnecessarily', 'Porque habitats sensíveis seriam destruídos e os peixes perturbados desnecessariamente'],
     ['Weil das Ufer dem Angler nicht gehört', 'Because the bank does not belong to the angler', 'Porque a margem não pertence ao pescador'],
     ['Weil der Boden dadurch fester wird', 'Because the ground becomes firmer that way', 'Porque o solo fica mais firme assim']],
    0,
    ['Betreten von Laichplätzen, Zerstören von Wasserpflanzen oder Zurücklassen von Müll schädigen den Lebensraum. Ein schonender Umgang mit Ufer und Gewässer ist Teil der Hege.',
     'Trampling spawning grounds, destroying water plants or leaving litter damages the habitat. Treating the bank and the water with care is part of stewardship.',
     'Pisar locais de desova, destruir plantas aquáticas ou deixar lixo danifica o habitat. Tratar margem e água com cuidado faz parte do manejo.'],
    ['gewaesserpflege', 'hege'], ['hecht', 'zander']],
]
