// Category: pflege_der_fischgewaesser — Care of fishing waters (1/2)
export const questions = [
  // --- water quality / oxygen / pH ---
  ['bbg-061', 'pflege_der_fischgewaesser',
    ['Welcher Sauerstoffgehalt ist für die meisten Fische in unseren Gewässern in der Regel ausreichend?',
     'Which oxygen content is usually sufficient for most fish in our waters?',
     'Qual teor de oxigênio geralmente é suficiente para a maioria dos peixes em nossas águas?'],
    [['Über 5 mg Sauerstoff pro Liter Wasser', 'Over 5 mg of oxygen per litre of water', 'Acima de 5 mg de oxigênio por litro de água'],
     ['Unter 1 mg Sauerstoff pro Liter Wasser', 'Under 1 mg of oxygen per litre of water', 'Abaixo de 1 mg de oxigênio por litro de água'],
     ['Genau 0,5 mg Sauerstoff pro Liter Wasser', 'Exactly 0.5 mg of oxygen per litre of water', 'Exatamente 0,5 mg de oxigênio por litro de água']],
    0,
    ['Für die meisten Fische sind Sauerstoffgehalte von mehr als 5 mg/l ausreichend. Unter etwa 3 mg/l geraten viele Fische in Stress, bei weniger droht Erstickung.',
     'Oxygen levels above 5 mg/l are sufficient for most fish. Below about 3 mg/l many fish come under stress, and with less there is a risk of suffocation.',
     'Teores de oxigênio acima de 5 mg/l são suficientes para a maioria dos peixes. Abaixo de cerca de 3 mg/l muitos peixes entram em estresse e, com menos, há risco de asfixia.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'karpfen', 'zander']],

  ['bbg-062', 'pflege_der_fischgewaesser',
    ['Wann ist der Sauerstoffgehalt im Wasser in der Regel am niedrigsten?',
     'When is the oxygen content in the water usually at its lowest?',
     'Quando o teor de oxigênio na água geralmente está mais baixo?'],
    [['Frühmorgens nach einer warmen Sommernacht', 'Early in the morning after a warm summer night', 'De manhã cedo, após uma noite quente de verão'],
     ['Mittags bei vollem Sonnenschein', 'At noon in full sunshine', 'Ao meio-dia, com sol pleno'],
     ['An frostigen Wintertagen', 'On frosty winter days', 'Em dias frios de inverno']],
    0,
    ['Nachts verbrauchen Wasserpflanzen und Kleinstlebewesen Sauerstoff, ohne dass Photosynthese stattfindet. Deshalb ist der Sauerstoffgehalt frühmorgens am niedrigsten.',
     'At night water plants and tiny organisms consume oxygen without photosynthesis taking place. That is why the oxygen content is lowest in the early morning.',
     'À noite, as plantas aquáticas e os pequenos organismos consomem oxigênio sem que haja fotossíntese. Por isso, o teor de oxigênio é mais baixo de manhã cedo.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'karpfen']],

  ['bbg-063', 'pflege_der_fischgewaesser',
    ['Warum kommt es im Hochsommer häufiger zu Sauerstoffmangel?',
     'Why does oxygen deficiency occur more often in midsummer?',
     'Por que a falta de oxigênio ocorre com mais frequência no auge do verão?'],
    [['Weil warmes Wasser weniger Sauerstoff aufnehmen kann und Abbauprozesse schneller laufen', 'Because warm water can hold less oxygen and decomposition processes run faster', 'Porque a água quente retém menos oxigênio e os processos de decomposição são mais rápidos'],
     ['Weil die Fische im Sommer mehr fressen', 'Because the fish eat more in summer', 'Porque os peixes comem mais no verão'],
     ['Weil die Pflanzen im Sommer keinen Sauerstoff produzieren', 'Because the plants produce no oxygen in summer', 'Porque as plantas não produzem oxigênio no verão']],
    0,
    ['Mit steigender Temperatur sinkt die Löslichkeit von Sauerstoff im Wasser, während der Sauerstoffverbrauch durch Fische und Abbauprozesse steigt. Das begünstigt Sauerstoffmangel.',
     'As temperature rises, the solubility of oxygen in water drops while oxygen consumption by fish and decomposition processes rises. This favours oxygen deficiency.',
     'Com o aumento da temperatura, a solubilidade do oxigênio na água cai, enquanto o consumo por peixes e processos de decomposição aumenta. Isso favorece a falta de oxigênio.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'zander', 'karpfen']],

  ['bbg-064', 'pflege_der_fischgewaesser',
    ['Welcher pH-Wert ist für die meisten heimischen Fische geeignet?',
     'Which pH value is suitable for most native fish?',
     'Qual valor de pH é adequado para a maioria dos peixes nativos?'],
    [['Ein neutraler bis leicht basischer Bereich von etwa 6,5 bis 8,5', 'A neutral to slightly alkaline range of about 6.5 to 8.5', 'Uma faixa neutra a levemente alcalina, de cerca de 6,5 a 8,5'],
     ['Ein stark saurer Bereich um pH 3', 'A strongly acidic range around pH 3', 'Uma faixa fortemente ácida em torno de pH 3'],
     ['Ein stark basischer Bereich um pH 12', 'A strongly alkaline range around pH 12', 'Uma faixa fortemente alcalina em torno de pH 12']],
    0,
    ['Die meisten heimischen Fische bevorzugen pH-Werte zwischen etwa 6,5 und 8,5. Extreme pH-Werte schädigen die Kiemen und führen zu Fischsterben.',
     'Most native fish prefer pH values between about 6.5 and 8.5. Extreme pH values damage the gills and lead to fish kills.',
     'A maioria dos peixes nativos prefere valores de pH entre cerca de 6,5 e 8,5. Valores extremos de pH danificam as brânquias e causam mortandade.'],
    ['wasserqualitaet', 'ph-wert'], ['hecht', 'karpfen']],

  ['bbg-065', 'pflege_der_fischgewaesser',
    ['Was passiert bei einer starken Versauerung eines Gewässers?',
     'What happens when a water body becomes strongly acidified?',
     'O que acontece quando um corpo d\u2019água fica fortemente acidificado?'],
    [['Die Kiemen der Fische werden geschädigt, es kann zu Fischsterben kommen', 'The gills of the fish are damaged and fish kills can occur', 'As brânquias dos peixes são danificadas e pode ocorrer mortandade'],
     ['Die Fische wachsen schneller', 'The fish grow faster', 'Os peixes crescem mais rápido'],
     ['Der Sauerstoffgehalt steigt stark an', 'The oxygen content rises sharply', 'O teor de oxigênio aumenta fortemente']],
    0,
    ['Stark saures Wasser greift die empfindlichen Kiemen an und stört den Mineralhaushalt der Fische. Viele Arten sterben bei pH-Werten deutlich unter 6.',
     'Strongly acidic water attacks the sensitive gills and disturbs the mineral balance of the fish. Many species die at pH values well below 6.',
     'A água fortemente ácida ataca as brânquias sensíveis e perturba o equilíbrio mineral dos peixes. Muitas espécies morrem em valores de pH bem abaixo de 6.'],
    ['wasserqualitaet', 'ph-wert'], ['forelle', 'hecht']],

  ['bbg-066', 'pflege_der_fischgewaesser',
    ['Was versteht man unter Eutrophierung?',
     'What is meant by eutrophication?',
     'O que se entende por eutrofização?'],
    [['Die Überdüngung eines Gewässers durch übermäßige Nährstoffe wie Phosphat und Nitrat', 'The over-fertilisation of a water body by excessive nutrients such as phosphate and nitrate', 'A superfertilização de um corpo d\u2019água por nutrientes excessivos, como fosfato e nitrato'],
     ['Die Abkühlung des Wassers im Winter', 'The cooling of the water in winter', 'O resfriamento da água no inverno'],
     ['Die natürliche Vermehrung der Fische', 'The natural reproduction of the fish', 'A reprodução natural dos peixes']],
    0,
    ['Eutrophierung ist die Überversorgung eines Gewässers mit Nährstoffen. Die Folge sind starkes Algenwachstum, Trübung und beim Absterben der Algen Sauerstoffmangel.',
     'Eutrophication is the over-supply of nutrients to a water body. The result is heavy algal growth, turbidity and oxygen deficiency when the algae die off.',
     'Eutrofização é o excesso de nutrientes em um corpo d\u2019água. A consequência é o forte crescimento de algas, turbidez e falta de oxigênio quando as algas morrem.'],
    ['wasserqualitaet', 'eutrophierung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-067', 'pflege_der_fischgewaesser',
    ['Welche Folge hat eine starke Algenblüte im Sommer?',
     'What is a consequence of a strong algal bloom in summer?',
     'Qual é a consequência de uma forte floração de algas no verão?'],
    [['Sauerstoffmangel, wenn die Algen absterben und zersetzt werden', 'Oxygen deficiency when the algae die and decompose', 'Falta de oxigênio quando as algas morrem e se decompõem'],
     ['Eine dauerhafte Zunahme der Fischbestände', 'A permanent increase of the fish stocks', 'Um aumento permanente dos estoques de peixes'],
     ['Eine Abkühlung des Gewässers', 'A cooling of the water body', 'Um resfriamento do corpo d\u2019água']],
    0,
    ['Wenn Algenmassen absterben, verbraucht ihre Zersetzung viel Sauerstoff. Das kann zu Sauerstoffmangel, dem sogenannten Umkippen des Gewässers und Fischsterben führen.',
     'When masses of algae die, their decomposition consumes a lot of oxygen. This can lead to oxygen deficiency, the so-called tipping of the water, and fish kills.',
     'Quando massas de algas morrem, sua decomposição consome muito oxigênio. Isso pode levar à falta de oxigênio, ao chamado colapso da água e à mortandade de peixes.'],
    ['wasserqualitaet', 'eutrophierung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-068', 'pflege_der_fischgewaesser',
    ['Was versteht man unter dem \u201eUmkippen\u201c eines Gewässers?',
     'What is meant by the \u201ctipping\u201d of a water body?',
     'O que se entende por \u201ccolapso\u201d de um corpo d\u2019água?'],
    [['Den plötzlichen Sauerstoffmangel durch Abbauprozesse nach einer Algenblüte', 'The sudden oxygen deficiency caused by decomposition processes after an algal bloom', 'A falta súbita de oxigênio causada pelos processos de decomposição após uma floração de algas'],
     ['Das Überlaufen des Gewässers bei Regen', 'The overflowing of the water body in rain', 'O transbordamento do corpo d\u2019água na chuva'],
     ['Die vollständige Austrocknung im Sommer', 'Complete drying out in summer', 'A secagem completa no verão']],
    0,
    ['Beim Umkippen bricht der Sauerstoffhaushalt zusammen: Absterbende Algen werden von Bakterien zersetzt, die dabei fast den gesamten Sauerstoff verbrauchen. Fische ersticken.',
     'When a water tips, the oxygen balance collapses: dying algae are decomposed by bacteria that consume almost all the oxygen. Fish suffocate.',
     'No colapso da água, o equilíbrio de oxigênio entra em colapso: algas mortas são decompostas por bactérias que consomem quase todo o oxigênio. Os peixes sufocam.'],
    ['wasserqualitaet', 'sauerstoff'], ['hecht', 'zander', 'karpfen']],

  ['bbg-069', 'pflege_der_fischgewaesser',
    ['Welche Nährstoffe führen hauptsächlich zur Eutrophierung von Gewässern?',
     'Which nutrients mainly lead to the eutrophication of waters?',
     'Quais nutrientes levam principalmente à eutrofização das águas?'],
    [['Phosphor (Phosphat) und Stickstoff (Nitrat)', 'Phosphorus (phosphate) and nitrogen (nitrate)', 'Fósforo (fosfato) e nitrogênio (nitrato)'],
     ['Sauerstoff und Kohlendioxid', 'Oxygen and carbon dioxide', 'Oxigênio e dióxido de carbono'],
     ['Salz und Zucker', 'Salt and sugar', 'Sal e açúcar']],
    0,
    ['Phosphat und Nitrat sind die wichtigsten Pflanzennährstoffe. Gelangen sie im Übermaß in Gewässer, etwa aus der Landwirtschaft oder aus Abwässern, wachsen Algen explosionsartig.',
     'Phosphate and nitrate are the most important plant nutrients. When they enter waters in excess, for example from agriculture or wastewater, algae grow explosively.',
     'Fosfato e nitrato são os nutrientes vegetais mais importantes. Quando entram em excesso nas águas, por exemplo da agricultura ou de esgotos, as algas crescem de forma explosiva.'],
    ['wasserqualitaet', 'eutrophierung'], ['hecht', 'karpfen']],

  ['bbg-070', 'pflege_der_fischgewaesser',
    ['Woher stammen übermäßige Nährstoffe in Gewässern häufig?',
     'Where do excessive nutrients in waters often come from?',
     'De onde vêm com frequência os nutrientes em excesso nas águas?'],
    [['Aus Düngemitteln der Landwirtschaft und aus Abwässern', 'From agricultural fertilisers and from wastewater', 'De fertilizantes agrícolas e de esgotos'],
     ['Aus dem Regenwasser im Winter', 'From rainwater in winter', 'Da água da chuva no inverno'],
     ['Aus der natürlichen Futteraufnahme der Fische', 'From the natural feeding of the fish', 'Da alimentação natural dos peixes']],
    0,
    ['Hauptquellen für Nährstoffüberschüsse sind landwirtschaftliche Düngung, Gülle, Kläranlagenabläufe und Oberflächenabflüsse. Sie fördern Algenwachstum und Sauerstoffmangel.',
     'Main sources of nutrient surpluses are agricultural fertilising, slurry, sewage plant outflows and surface runoff. They promote algal growth and oxygen deficiency.',
     'As principais fontes de excesso de nutrientes são a fertilização agrícola, o esterco líquido, os efluentes de estações de tratamento e o escoamento superficial. Eles promovem o crescimento de algas e a falta de oxigênio.'],
    ['wasserqualitaet', 'eutrophierung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-071', 'pflege_der_fischgewaesser',
    ['Welche Funktion haben Wasserpflanzen in einem gesunden Gewässer?',
     'What function do water plants have in a healthy water body?',
     'Qual é a função das plantas aquáticas em um corpo d\u2019água saudável?'],
    [['Sie produzieren tagsüber Sauerstoff und bieten Fischen Laichplatz und Schutz', 'They produce oxygen during the day and offer fish spawning sites and shelter', 'Elas produzem oxigênio durante o dia e oferecem aos peixes locais de desova e abrigo'],
     ['Sie verbrauchen tagsüber den gesamten Sauerstoff', 'They consume all the oxygen during the day', 'Elas consomem todo o oxigênio durante o dia'],
     ['Sie trüben das Wasser dauerhaft', 'They permanently cloud the water', 'Elas turvam a água permanentemente']],
    0,
    ['Wasserpflanzen erzeugen bei Licht Photosynthese und damit Sauerstoff. Sie dienen als Laichsubstrat, Versteck und Nahrung. Nachts verbrauchen sie allerdings Sauerstoff.',
     'Water plants carry out photosynthesis in the light and thus produce oxygen. They serve as spawning substrate, shelter and food. At night, however, they consume oxygen.',
     'As plantas aquáticas fazem fotossíntese na luz e, assim, produzem oxigênio. Servem de substrato de desova, abrigo e alimento. À noite, porém, consomem oxigênio.'],
    ['wasserpflanzen', 'oekologie'], ['hecht', 'karpfen']],

  ['bbg-072', 'pflege_der_fischgewaesser',
    ['Warum können zu viele Wasserpflanzen problematisch sein?',
     'Why can too many water plants be problematic?',
     'Por que o excesso de plantas aquáticas pode ser problemático?'],
    [['Weil sie nachts Sauerstoff verbrauchen und beim Absterben die Zersetzung Sauerstoff bindet', 'Because they consume oxygen at night and decomposition binds oxygen when they die off', 'Porque consomem oxigênio à noite e, ao morrerem, a decomposição consome oxigênio'],
     ['Weil sie den Fischen das Fressen erschweren', 'Because they make it harder for the fish to feed', 'Porque dificultam a alimentação dos peixes'],
     ['Weil sie das Wasser zu sehr abkühlen', 'Because they cool the water too much', 'Porque esfriam demais a água']],
    0,
    ['Ein Übermaß an Wasserpflanzen führt nachts zu starkem Sauerstoffverbrauch. Sterben die Pflanzen ab, verbraucht ihre Zersetzung zusätzlich Sauerstoff und es droht Sauerstoffmangel.',
     'An excess of water plants leads to strong oxygen consumption at night. When the plants die, their decomposition uses additional oxygen and oxygen deficiency threatens.',
     'O excesso de plantas aquáticas gera forte consumo de oxigênio à noite. Quando as plantas morrem, sua decomposição consome oxigênio adicional e ameaça a falta de oxigênio.'],
    ['wasserpflanzen', 'sauerstoff'], ['karpfen', 'hecht']],

  ['bbg-073', 'pflege_der_fischgewaesser',
    ['Welche Bedeutung hat das Schilf (Röhricht) am Ufer?',
     'What significance does the reed belt at the shore have?',
     'Qual é a importância do junco (canavial) na margem?'],
    [['Es schützt das Ufer, filtert Nährstoffe und bietet Fischen Laichplatz und Schutz', 'It protects the bank, filters nutrients and offers fish spawning sites and shelter', 'Ele protege a margem, filtra nutrientes e oferece aos peixes locais de desova e abrigo'],
     ['Es verhindert jede Fischvermehrung', 'It prevents all fish reproduction', 'Ele impede toda reprodução dos peixes'],
     ['Es entzieht dem Wasser sämtlichen Sauerstoff', 'It removes all oxygen from the water', 'Ele retira todo o oxigênio da água']],
    0,
    ['Der Schilfgürtel stabilisiert das Ufer gegen Erosion, filtert Nährstoffe aus dem Wasser und ist Lebensraum sowie Laichplatz für viele Fischarten und deren Jungfische.',
     'The reed belt stabilises the bank against erosion, filters nutrients from the water and is habitat and spawning site for many fish species and their young.',
     'A faixa de junco estabiliza a margem contra a erosão, filtra nutrientes da água e é habitat e local de desova de muitas espécies de peixes e de seus filhotes.'],
    ['ufer', 'wasserpflanzen', 'oekologie'], ['hecht', 'karpfen']],

  ['bbg-074', 'pflege_der_fischgewaesser',
    ['Warum ist ein naturnahes Ufer für Fische wichtig?',
     'Why is a natural bank important for fish?',
     'Por que uma margem natural é importante para os peixes?'],
    [['Weil es Laichplätze, Deckung und Nahrung bietet und Erosion verhindert', 'Because it offers spawning sites, cover and food and prevents erosion', 'Porque oferece locais de desova, abrigo e alimento e evita a erosão'],
     ['Weil es die Wassertiefe vergrößert', 'Because it increases the water depth', 'Porque aumenta a profundidade da água'],
     ['Weil es den Fischbestand automatisch erhöht', 'Because it automatically increases the fish stock', 'Porque aumenta automaticamente o estoque de peixes']],
    0,
    ['Naturnahe Ufer mit Pflanzen, Totholz und Flachwasserzonen sind die Kinderstube der Fische. Betonierte und ausgebaute Ufer zerstören diese Lebensräume.',
     'Natural banks with plants, dead wood and shallow zones are the nursery of the fish. Concrete and engineered banks destroy these habitats.',
     'Margens naturais com plantas, madeira morta e zonas rasas são o berçário dos peixes. Margens concretadas e artificializadas destroem esses habitats.'],
    ['ufer', 'oekologie'], ['hecht', 'karpfen', 'zander']],

  ['bbg-075', 'pflege_der_fischgewaesser',
    ['Was passiert, wenn der Schilfgürtel eines Sees vollständig entfernt wird?',
     'What happens when the reed belt of a lake is completely removed?',
     'O que acontece quando a faixa de junco de um lago é completamente removida?'],
    [['Das Ufer wird erodiert und wichtige Laich- und Aufwuchsplätze gehen verloren', 'The bank erodes and important spawning and nursery grounds are lost', 'A margem sofre erosão e importantes locais de desova e criação se perdem'],
     ['Der Sauerstoffgehalt steigt dauerhaft an', 'The oxygen content rises permanently', 'O teor de oxigênio aumenta permanentemente'],
     ['Die Fische werden größer', 'The fish become larger', 'Os peixes ficam maiores']],
    0,
    ['Ohne Schilfgürtel fehlt dem Ufer der Wellenschutz. Die Erosion nimmt zu, trübes Wasser entsteht und Laich- sowie Aufwuchsplätze vieler Fischarten verschwinden.',
     'Without the reed belt the bank lacks wave protection. Erosion increases, murky water develops and spawning and nursery grounds of many fish species disappear.',
     'Sem a faixa de junco, a margem perde a proteção contra ondas. A erosão aumenta, a água fica turva e somem os locais de desova e criação de muitas espécies.'],
    ['ufer', 'wasserpflanzen'], ['hecht', 'zander']],

  // --- habitat measures / renaturation ---
  ['bbg-076', 'pflege_der_fischgewaesser',
    ['Welche Maßnahmen verbessern den Lebensraum von Fischen in einem Gewässer?',
     'Which measures improve the habitat of fish in a water body?',
     'Quais medidas melhoram o habitat dos peixes em um corpo d\u2019água?'],
    [['Naturnahe Ufer anlegen, Totholz einbringen und Flachwasserzonen erhalten', 'Create natural banks, introduce dead wood and preserve shallow zones', 'Criar margens naturais, introduzir madeira morta e preservar zonas rasas'],
     ['Den Gewässergrund vollständig betonieren', 'Completely concrete the bottom of the water', 'Concretar completamente o fundo da água'],
     ['Alle Wasserpflanzen entfernen', 'Remove all water plants', 'Remover todas as plantas aquáticas']],
    0,
    ['Strukturverbessernde Maßnahmen wie Totholz, naturnahe Ufer, Flachwasserzonen und Kiesbänke schaffen Verstecke, Laichplätze und Nahrung und fördern so den Fischbestand.',
     'Structure-improving measures such as dead wood, natural banks, shallow zones and gravel bars create shelter, spawning sites and food and thus promote the fish stock.',
     'Medidas de melhoria estrutural, como madeira morta, margens naturais, zonas rasas e bancos de cascalho, criam abrigos, locais de desova e alimento e promovem o estoque de peixes.'],
    ['hege', 'gewaesserpflege'], ['hecht', 'zander', 'forelle']],

  ['bbg-077', 'pflege_der_fischgewaesser',
    ['Warum ist Totholz in einem Gewässer wertvoll?',
     'Why is dead wood valuable in a water body?',
     'Por que a madeira morta é valiosa em um corpo d\u2019água?'],
    [['Es bietet Verstecke, Struktur und Nahrungsgrundlage für viele Lebewesen', 'It offers shelter, structure and a food basis for many organisms', 'Ela oferece abrigo, estrutura e base alimentar para muitos organismos'],
     ['Es verbraucht den gesamten Sauerstoff', 'It consumes all the oxygen', 'Ela consome todo o oxigênio'],
     ['Es macht das Wasser trüb', 'It makes the water murky', 'Ela deixa a água turva']],
    0,
    ['Totholz schafft Struktur im Wasser: Es bietet Fischen und Kleintieren Verstecke und Sitzplätze, ist Nahrungsgrundlage und belebt den Gewässerboden.',
     'Dead wood creates structure in the water: it offers fish and small animals shelter and resting places, is a food basis and enlivens the bottom.',
     'A madeira morta cria estrutura na água: oferece abrigo e locais de descanso a peixes e pequenos animais, é base alimentar e enriquece o fundo.'],
    ['gewaesserpflege', 'oekologie'], ['hecht', 'zander', 'barsch']],

  ['bbg-078', 'pflege_der_fischgewaesser',
    ['Was versteht man unter Gewässerunterhaltung?',
     'What is meant by water body maintenance?',
     'O que se entende por manutenção de corpos d\u2019água?'],
    [['Pflegemaßnahmen zur Erhaltung der Leistungs- und Funktionsfähigkeit des Gewässers', 'Care measures to preserve the performance and function of the water body', 'Medidas de cuidado para preservar o desempenho e a funcionalidade do corpo d\u2019água'],
     ['Das vollständige Austrocknen des Gewässers', 'The complete drying out of the water body', 'A secagem completa do corpo d\u2019água'],
     ['Das Fangen aller Fische', 'Catching all the fish', 'A captura de todos os peixes']],
    0,
    ['Gewässerunterhaltung umfasst Pflege- und Instandhaltungsmaßnahmen wie die Erhaltung der Abflussfähigkeit, die Pflege von Ufern und das Entfernen von Hindernissen, stets mit Rücksicht auf die Lebewesen.',
     'Water body maintenance comprises care and upkeep measures such as preserving flow capacity, maintaining banks and removing obstacles, always with consideration for the organisms.',
     'A manutenção de corpos d\u2019água abrange medidas de cuidado e conservação, como preservar a capacidade de escoamento, cuidar das margens e remover obstáculos, sempre respeitando os organismos.'],
    ['gewaesserpflege'], ['hecht', 'zander']],

  ['bbg-079', 'pflege_der_fischgewaesser',
    ['Warum ist eine zu intensive Krautung (Entfernung der Wasserpflanzen) schädlich?',
     'Why is too intensive weed cutting (removal of water plants) harmful?',
     'Por que o corte excessivo de plantas aquáticas é prejudicial?'],
    [['Weil Lebensraum, Laichplätze und Deckung der Fische zerstört werden', 'Because the habitat, spawning sites and cover of the fish are destroyed', 'Porque o habitat, os locais de desova e o abrigo dos peixes são destruídos'],
     ['Weil die Fische dann zu viel Futter finden', 'Because the fish then find too much food', 'Porque os peixes então encontram comida demais'],
     ['Weil das Wasser dadurch zu kalt wird', 'Because the water becomes too cold', 'Porque a água fica fria demais']],
    0,
    ['Wasserpflanzen sind Lebensraum, Laichsubstrat und Deckung. Eine vollständige, intensive Krautung zerstört diese Funktionen und setzt die Fische Räubern aus.',
     'Water plants are habitat, spawning substrate and cover. Complete, intensive weed cutting destroys these functions and exposes the fish to predators.',
     'As plantas aquáticas são habitat, substrato de desova e abrigo. O corte completo e intensivo destrói essas funções e expõe os peixes aos predadores.'],
    ['gewaesserpflege', 'wasserpflanzen'], ['hecht', 'karpfen']],

  ['bbg-080', 'pflege_der_fischgewaesser',
    ['Was versteht man unter der Durchgängigkeit eines Fließgewässers?',
     'What is meant by the connectivity (passability) of a running water?',
     'O que se entende por conectividade (passabilidade) de um rio?'],
    [['Dass Fische und andere Lebewesen das Gewässer ungehindert auf- und abwärts durchwandern können', 'That fish and other organisms can move freely up and down the water', 'Que peixes e outros organismos possam percorrer livremente o rio para cima e para baixo'],
     ['Dass das Wasser vollständig verschmutzt ist', 'That the water is completely polluted', 'Que a água esteja totalmente poluída'],
     ['Dass das Gewässer für den Schiffsverkehr gesperrt ist', 'That the water is closed to shipping', 'Que o rio esteja fechado para a navegação']],
    0,
    ['Durchgängigkeit bedeutet, dass Fische zum Laichen, zur Nahrungssuche und zu den Winterquartieren wandern können. Wehre und Stauanlagen ohne Fischpass unterbrechen diese Wanderungen.',
     'Connectivity means that fish can migrate to spawn, find food and reach winter quarters. Weirs and dams without a fish pass interrupt these migrations.',
     'Conectividade significa que os peixes podem migrar para desovar, buscar alimento e alcançar os locais de invernada. Açudes e barragens sem escada de peixes interrompem essas migrações.'],
    ['fliesgewaesser', 'oekologie'], ['forelle', 'asche', 'barbe']],

  ['bbg-081', 'pflege_der_fischgewaesser',
    ['Welche Bauwerke behindern die Fischwanderung in Flüssen?',
     'Which structures hinder fish migration in rivers?',
     'Quais estruturas dificultam a migração dos peixes nos rios?'],
    [['Wehre und Stauanlagen ohne funktionierenden Fischpass', 'Weirs and dams without a functioning fish pass', 'Açudes e barragens sem escada de peixes funcional'],
     ['Natürliche Kiesbänke', 'Natural gravel bars', 'Bancos naturais de cascalho'],
     ['Pflanzenbewachsene Ufer', 'Weed-covered banks', 'Margens cobertas de vegetação']],
    0,
    ['Querbauwerke wie Wehre, Staustufen und Abstürze versperren Fischen den Weg zu ihren Laichplätzen. Fischpässe oder Fischtreppen ermöglichen die Umgehung.',
     'Transverse structures such as weirs, barrages and drops block the way of fish to their spawning grounds. Fish passes or fish ladders allow them to bypass these.',
     'Estruturas transversais como açudes, barragens e quedas bloqueiam o caminho dos peixes até seus locais de desova. Escadas de peixes ou passagens para peixes permitem contorná-las.'],
    ['fliesgewaesser', 'oekologie'], ['forelle', 'asche', 'zander']],

  ['bbg-082', 'pflege_der_fischgewaesser',
    ['Was ist ein Fischpass (Fischtreppe)?',
     'What is a fish pass (fish ladder)?',
     'O que é uma escada de peixes (passagem para peixes)?'],
    [['Eine Anlage, die Fischen die Umgehung von Stauanlagen ermöglicht', 'A facility that allows fish to bypass dams and barrages', 'Uma instalação que permite aos peixes contornar barragens e açudes'],
     ['Ein Netz zum Fang wandernder Fische', 'A net for catching migrating fish', 'Uma rede para capturar peixes migradores'],
     ['Ein Fütterungsplatz für Fische', 'A feeding place for fish', 'Um local de alimentação para peixes']],
    0,
    ['Ein Fischpass ist eine meist stufenförmig angelegte Umgehung, durch die Fische Wehre und Stauanlagen auf- und abwärts überwinden können. So bleibt das Gewässer durchgängig.',
     'A fish pass is a usually step-like bypass through which fish can overcome weirs and barrages in both directions. This keeps the water passable.',
     'Uma escada de peixes é uma passagem em forma de degraus pela qual os peixes podem transpor açudes e barragens nos dois sentidos. Assim o rio permanece passável.'],
    ['fliesgewaesser', 'oekologie'], ['forelle', 'asche']],

  ['bbg-083', 'pflege_der_fischgewaesser',
    ['Welche Folgen hat der Ausbau (die Begradigung) eines Flusses für die Fische?',
     'What consequences does the straightening (engineering) of a river have for the fish?',
     'Quais consequências a retificação de um rio tem para os peixes?'],
    [['Lebensräume und Laichplätze gehen verloren, die Strömung wird gleichförmig', 'Habitats and spawning grounds are lost and the current becomes uniform', 'Habitats e locais de desova se perdem e a correnteza se torna uniforme'],
     ['Die Fischbestände nehmen automatisch zu', 'The fish stocks automatically increase', 'Os estoques de peixes aumentam automaticamente'],
     ['Der Sauerstoffgehalt steigt dauerhaft', 'The oxygen content rises permanently', 'O teor de oxigênio aumenta permanentemente']],
    0,
    ['Begradigte Flüsse verlieren Struktur, Strömungsvielfalt, Flachwasserzonen und Überschwemmungsflächen. Das reduziert die Artenvielfalt und die natürliche Vermehrung der Fische.',
     'Straightened rivers lose structure, current diversity, shallow zones and floodplains. This reduces biodiversity and the natural reproduction of fish.',
     'Rios retificados perdem estrutura, diversidade de correnteza, zonas rasas e áreas de inundação. Isso reduz a biodiversidade e a reprodução natural dos peixes.'],
    ['fliesgewaesser', 'oekologie'], ['forelle', 'asche', 'barbe']],

  ['bbg-084', 'pflege_der_fischgewaesser',
    ['Was versteht man unter Renaturierung eines Gewässers?',
     'What is meant by the renaturation of a water body?',
     'O que se entende por renaturalização de um corpo d\u2019água?'],
    [['Die Rückführung eines ausgebauten Gewässers in einen naturnahen Zustand', 'The restoration of an engineered water body to a near-natural state', 'A restauração de um corpo d\u2019água artificializado a um estado próximo do natural'],
     ['Das Betonieren der Ufer', 'Concreting the banks', 'A concretagem das margens'],
     ['Das vollständige Entfernen aller Wasserpflanzen', 'The complete removal of all water plants', 'A remoção completa de todas as plantas aquáticas']],
    0,
    ['Bei der Renaturierung werden Ufer abgeflacht, Strukturen wie Totholz und Kies eingebracht und die Strömung variiert. Ziel ist ein naturnaher Lebensraum für Tiere und Pflanzen.',
     'In renaturation, banks are flattened, structures such as dead wood and gravel are introduced and the current is varied. The goal is a near-natural habitat for animals and plants.',
     'Na renaturalização, as margens são suavizadas, estruturas como madeira morta e cascalho são introduzidas e a correnteza é variada. O objetivo é um habitat próximo do natural para animais e plantas.'],
    ['gewaesserpflege', 'oekologie'], ['forelle', 'asche', 'hecht']],

  ['bbg-085', 'pflege_der_fischgewaesser',
    ['Warum bevorzugen Forellen kühles Wasser?',
     'Why do trout prefer cool water?',
     'Por que as trutas preferem água fria?'],
    [['Weil kühles Wasser mehr Sauerstoff enthält und Forellen einen hohen Sauerstoffbedarf haben', 'Because cool water holds more oxygen and trout have a high oxygen demand', 'Porque a água fria contém mais oxigênio e as trutas têm alta demanda de oxigênio'],
     ['Weil sie sich nur in kaltem Wasser fortpflanzen', 'Because they only reproduce in cold water', 'Porque só se reproduzem em água fria'],
     ['Weil sie warmes Wasser nicht vertragen', 'Because they cannot tolerate warm water at all', 'Porque não toleram água morna']],
    0,
    ['Forellen leben in sauerstoffreichen, kühlen Gewässern. Warmes Wasser enthält weniger Sauerstoff und setzt die empfindlichen Salmoniden unter Stress.',
     'Trout live in oxygen-rich, cool waters. Warm water holds less oxygen and puts the sensitive salmonids under stress.',
     'As trutas vivem em águas frias e ricas em oxigênio. A água morna contém menos oxigênio e estressa os sensíveis salmonídeos.'],
    ['wasserqualitaet', 'temperatur'], ['forelle', 'asche']],

  ['bbg-086', 'pflege_der_fischgewaesser',
    ['Welche Fische bevorzugen wärmere, sommerwarme Gewässer?',
     'Which fish prefer warmer, summer-warm waters?',
     'Quais peixes preferem águas mais quentes, quentes no verão?'],
    [['Karpfen und Wels', 'Carp and catfish', 'Carpa e siluro'],
     ['Bachforelle und Äsche', 'Brown trout and grayling', 'Truta-marrom e timalo'],
     ['Quappe und Barbe', 'Burbot and barbel', 'Lota e barbo']],
    0,
    ['Karpfen und Wels sind wärmeliebende Arten, die sommerwarme Seen und Altarme bevorzugen. Forellenartige wie Bachforelle und Äsche brauchen dagegen kühles, sauerstoffreiches Wasser.',
     'Carp and catfish are warmth-loving species that prefer summer-warm lakes and backwaters. Salmonids such as brown trout and grayling, on the other hand, need cool, oxygen-rich water.',
     'Carpa e siluro são espécies que gostam de calor e preferem lagos e braços de rio quentes no verão. Salmonídeos como truta-marrom e timalo, ao contrário, precisam de água fria e rica em oxigênio.'],
    ['wasserqualitaet', 'temperatur'], ['karpfen', 'wels', 'forelle', 'asche']],

  ['bbg-087', 'pflege_der_fischgewaesser',
    ['Wie kann man den Sauerstoffgehalt eines Gewässers erhöhen?',
     'How can the oxygen content of a water body be increased?',
     'Como se pode aumentar o teor de oxigênio de um corpo d\u2019água?'],
    [['Durch Durchlüftung, Wasserzirkulation und den Erhalt von Wasserpflanzen', 'By aeration, water circulation and preserving water plants', 'Por aeração, circulação da água e preservação das plantas aquáticas'],
     ['Durch das Einleiten von Abwasser', 'By discharging wastewater', 'Pelo lançamento de esgoto'],
     ['Durch das Entfernen aller Pflanzen', 'By removing all plants', 'Pela remoção de todas as plantas']],
     0,
    ['Belüftungsanlagen, bewegtes Wasser und intakte Pflanzenbestände erhöhen den Sauerstoffeintrag. Ein gesundes Gewässer reguliert seinen Sauerstoffhaushalt weitgehend selbst.',
     'Aeration systems, moving water and intact plant stocks increase the oxygen input. A healthy water body largely regulates its own oxygen balance.',
     'Sistemas de aeração, água em movimento e estoques de plantas intactos aumentam a entrada de oxigênio. Um corpo d\u2019água saudável regula em grande parte seu próprio equilíbrio de oxigênio.'],
    ['wasserqualitaet', 'sauerstoff'], ['karpfen', 'hecht']],

  ['bbg-088', 'pflege_der_fischgewaesser',
    ['Welche Gefahr geht von der Einleitung von Gülle in ein Gewässer aus?',
     'What danger arises from the discharge of slurry into a water body?',
     'Qual perigo advém do lançamento de esterco líquido em um corpo d\u2019água?'],
    [['Nährstoffüberlast, Sauerstoffmangel und Fischsterben', 'Nutrient overload, oxygen deficiency and fish kills', 'Excesso de nutrientes, falta de oxigênio e mortandade de peixes'],
     ['Eine dauerhafte Abkühlung des Wassers', 'A permanent cooling of the water', 'Um resfriamento permanente da água'],
     ['Eine Zunahme der Wasserpflanzen ohne Folgen', 'An increase of water plants without consequences', 'Um aumento das plantas aquáticas sem consequências']],
    0,
    ['Gülle bringt große Mengen an Nährstoffen ein, die zu Algenblüten führen. Beim Abbau der Algen wird Sauerstoff verbraucht, was zu Fischsterben führen kann.',
     'Slurry introduces large amounts of nutrients that lead to algal blooms. When the algae decompose, oxygen is consumed, which can lead to fish kills.',
     'O esterco líquido introduz grandes quantidades de nutrientes que geram florações de algas. Na decomposição das algas, o oxigênio é consumido, o que pode causar mortandade.'],
    ['wasserqualitaet', 'verschmutzung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-089', 'pflege_der_fischgewaesser',
    ['Welche Schadstoffe sind für Fische besonders gefährlich?',
     'Which pollutants are especially dangerous for fish?',
     'Quais poluentes são especialmente perigosos para os peixes?'],
    [['Pestizide, Schwermetalle und Öl', 'Pesticides, heavy metals and oil', 'Pesticidas, metais pesados e óleo'],
     ['Sand und Kies', 'Sand and gravel', 'Areia e cascalho'],
     ['Natürliches Laub im Herbst', 'Natural leaves in autumn', 'Folhas naturais no outono']],
    0,
    ['Pestizide können Fische akut vergiften, Schwermetalle reichern sich im Gewebe an und Öl zerstört die Kiemenfunktion und verschmutzt die Ufer.',
     'Pesticides can poison fish acutely, heavy metals accumulate in the tissue and oil destroys the gill function and pollutes the banks.',
     'Pesticidas podem envenenar os peixes de forma aguda, metais pesados se acumulam nos tecidos e o óleo destrói a função das brânquias e polui as margens.'],
    ['wasserqualitaet', 'verschmutzung'], ['hecht', 'zander', 'karpfen']],

  ['bbg-090', 'pflege_der_fischgewaesser',
    ['Was sollte man bei einer Ölverschmutzung eines Gewässers tun?',
     'What should one do in the event of oil pollution of a water body?',
     'O que se deve fazer em caso de poluição por óleo de um corpo d\u2019água?'],
    [['Die zuständige Behörde oder Feuerwehr informieren', 'Inform the responsible authority or the fire brigade', 'Informar a autoridade competente ou o corpo de bombeiros'],
     ['Das Öl selbst mit Tüchern aufwischen', 'Wipe up the oil yourself with cloths', 'Limpar o óleo sozinho com panos'],
     ['Nichts tun und weiterangeln', 'Do nothing and keep fishing', 'Não fazer nada e continuar pescando']],
    0,
    ['Ölverschmutzungen müssen umgehend der zuständigen Stelle gemeldet werden, da sie Fische und Wasservögel akut gefährden. Eigenmächtige Großaktionen richten oft mehr Schaden an.',
     'Oil pollution must be reported immediately to the responsible authority because it acutely endangers fish and water birds. Unauthorised large-scale actions often cause more damage.',
     'Poluições por óleo devem ser comunicadas imediatamente à autoridade responsável, pois ameaçam agudamente peixes e aves aquáticas. Ações por conta própria geralmente causam mais danos.'],
    ['wasserqualitaet', 'verschmutzung'], ['hecht', 'zander', 'wels']],
]
