// Category: fanggeraete_und_deren_gebrauch — Fishing gear & use (2/2)
export const questions = [
  // --- lures ---
  ['bbg-146', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Blinker?',
     'What is a spoon lure (Blinker)?',
     'O que é uma colher (blinker)?'],
    [['Ein metallener Kunstköder in Löffelform, der beim Einholen blitzt und blinkt', 'A metal artificial lure in spoon shape that flashes and glints when retrieved', 'Uma isca artificial de metal em forma de colher que reluz e brilha ao ser recolhida'],
     ['Ein Schwimmer aus Holz', 'A float made of wood', 'Uma boia de madeira'],
     ['Ein Haken ohne Widerhaken', 'A barbless hook', 'Um anzol sem farpa']],
    0,
    ['Der Blinker ist ein löffelförmiger Metallköder, der beim Einholen taumelt und Licht reflektiert. Er eignet sich besonders für Hecht und Barsch.',
     'The spoon is a spoon-shaped metal lure that wobbles and reflects light when retrieved. It is especially suitable for pike and perch.',
     'A colher é uma isca de metal em forma de colher que oscila e reflete luz ao ser recolhida. É especialmente adequada para lúcio e perca.'],
    ['koeder', 'kunstkoeder'], ['hecht', 'barsch']],

  ['bbg-147', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Wobbler?',
     'What is a wobbler (crankbait)?',
     'O que é um wobbler (plug)?'],
    [['Ein Kunstköder aus Holz oder Kunststoff, der beim Einholen wie ein Fisch wackelt', 'An artificial lure made of wood or plastic that wobbles like a fish when retrieved', 'Uma isca artificial de madeira ou plástico que balança como um peixe ao ser recolhida'],
     ['Ein Blei für die Grundmontage', 'A sinker for the bottom rig', 'Uma chumbada para a montagem de fundo'],
     ['Ein Netz zum Landen von Fischen', 'A net for landing fish', 'Uma rede para aterrissar peixes']],
    0,
    ['Der Wobbler imitiert mit seiner Taumelbewegung einen kleinen Fisch. Je nach Bauart schwimmt er in verschiedenen Tiefen und eignet sich für Hecht, Zander und Barsch.',
     'With its wobbling motion the wobbler imitates a small fish. Depending on its design it swims at different depths and suits pike, pikeperch and perch.',
     'Com seu movimento oscilante, o wobbler imita um peixinho. Conforme o modelo, nada em diferentes profundidades e serve para lúcio, lúcio-perca e perca.'],
    ['koeder', 'kunstkoeder'], ['hecht', 'zander', 'barsch']],

  ['bbg-148', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Gummifisch (Softbait)?',
     'What is a soft bait?',
     'O que é uma isca de borracha (soft bait)?'],
    [['Ein weicher Kunststoffköder, der einen Fisch, Wurm oder Krebs imitiert', 'A soft plastic lure that imitates a fish, worm or crayfish', 'Uma isca de plástico macio que imita peixe, verme ou lagostim'],
     ['Ein Schwimmer aus Gummi', 'A float made of rubber', 'Uma boia de borracha'],
     ['Ein Metallköder in Löffelform', 'A metal lure in spoon shape', 'Uma isca de metal em forma de colher']],
    0,
    ['Gummifische sind weiche Kunststoffköder, die oft mit einem Bleikopf (Jigkopf) geführt werden. Sie sind besonders erfolgreich auf Zander und Barsch.',
     'Soft baits are soft plastic lures that are often worked with a jig head. They are especially successful on pikeperch and perch.',
     'As iscas de borracha são iscas de plástico macio, geralmente trabalhadas com cabeça de chumbo (jig). São especialmente eficazes para lúcio-perca e perca.'],
    ['koeder', 'kunstkoeder'], ['zander', 'barsch', 'hecht']],

  ['bbg-149', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Spinner?',
     'What is a spinner (spinnerbait)?',
     'O que é um spinner (spinnerbait)?'],
    [['Ein Kunstköder mit rotierendem Metallblatt, das beim Einholen dreht und blinkt', 'An artificial lure with a rotating metal blade that spins and flashes when retrieved', 'Uma isca artificial com lâmina de metal rotativa que gira e reluz ao ser recolhida'],
     ['Eine Pose mit zwei Haken', 'A float with two hooks', 'Uma boia com dois anzóis'],
     ['Ein Haken aus Edelstahl', 'A hook made of stainless steel', 'Um anzol de aço inoxidável']],
    0,
    ['Der Spinner besitzt ein rotierendes Blatt, das beim Einholen Lichtblitze und Vibrationen erzeugt. Er ist ein klassischer Köder für Barsch und Hecht.',
     'The spinner has a rotating blade that produces flashes of light and vibrations when retrieved. It is a classic lure for perch and pike.',
     'O spinner tem uma lâmina rotativa que produz relâmpagos de luz e vibrações ao ser recolhido. É uma isca clássica para perca e lúcio.'],
    ['koeder', 'kunstkoeder'], ['barsch', 'hecht']],

  ['bbg-150', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Twister?',
     'What is a twister tail?',
     'O que é um twister (cauda torcida)?'],
    [['Ein Gummiköder mit gedrehtem Schwanz, der beim Einholen schlägt und vibriert', 'A soft plastic lure with a twisted tail that thrashes and vibrates when retrieved', 'Uma isca de borracha com cauda torcida que vibra e se agita ao ser recolhida'],
     ['Ein Holzschwimmer', 'A wooden float', 'Uma boia de madeira'],
     ['Ein Blei in Kegelform', 'A cone-shaped sinker', 'Uma chumbada em forma de cone']],
    0,
    ['Der Twister ist ein weicher Gummiköder, dessen gedrehter Schwanz beim Einholen stark vibriert. Er wird meist mit einem Jigkopf geführt und eignet sich für Zander und Barsch.',
     'The twister is a soft plastic lure whose twisted tail vibrates strongly when retrieved. It is usually worked with a jig head and suits pikeperch and perch.',
     'O twister é uma isca de borracha macia cuja cauda torcida vibra fortemente ao ser recolhida. Geralmente é trabalhado com cabeça de jig e serve para lúcio-perca e perca.'],
    ['koeder', 'kunstkoeder'], ['zander', 'barsch']],

  // --- bait ---
  ['bbg-151', 'fanggeraete_und_deren_gebrauch',
    ['Welche Köder eignen sich besonders für Friedfische wie Plötze und Karpfen?',
     'Which baits are especially suitable for coarse fish such as roach and carp?',
     'Quais iscas são especialmente adequadas para peixes não predadores como barata e carpa?'],
    [['Mais, Würmer, Brot und Teig', 'Corn, worms, bread and dough', 'Milho, minhocas, pão e massa'],
     ['Blinker und Wobbler', 'Spoons and wobblers', 'Colheres e wobblers'],
     ['Gummifische und Twister', 'Soft baits and twisters', 'Soft baits e twisters']],
    0,
    ['Friedfische nehmen pflanzliche und tierische Naturköder wie Mais, Würmer, Brot oder Teig. Kunstköder wie Blinker und Wobbler zielen dagegen auf Raubfische.',
     'Coarse fish take plant and animal natural baits such as corn, worms, bread or dough. Artificial lures such as spoons and wobblers, on the other hand, target predatory fish.',
     'Peixes não predadores aceitam iscas naturais vegetais e animais, como milho, minhocas, pão ou massa. Iscas artificiais como colheres e wobblers, ao contrário, visam predadores.'],
    ['koeder', 'friedfisch'], ['karpfen', 'plotze']],

  ['bbg-152', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter Anfüttern?',
     'What is meant by groundbaiting?',
     'O que se entende por iscagem de fundo (anfüttern)?'],
    [['Das Einbringen von Futter ins Wasser, um Fische an die Angelstelle zu locken', 'Introducing feed into the water to attract fish to the fishing spot', 'A introdução de alimento na água para atrair os peixes ao local de pesca'],
     ['Das Töten von Fischen mit Strom', 'Killing fish with electricity', 'A matança de peixes com eletricidade'],
     ['Das Fangen von Köderfischen mit dem Kescher', 'Catching bait fish with a landing net', 'A captura de peixes-isca com a rede']],
    0,
    ['Beim Anfüttern wird Futter wie Mais, Boilies oder Grundfutter an der Angelstelle verteilt. Es lockt Fische an und hält sie am Platz.',
     'When groundbaiting, feed such as corn, boilies or groundbait is spread at the fishing spot. It attracts fish and keeps them in place.',
     'Na iscagem, alimento como milho, boilies ou massa de fundo é espalhado no local de pesca. Ele atrai os peixes e os mantém no lugar.'],
    ['koeder', 'technik'], ['karpfen', 'plotze']],

  ['bbg-153', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Boilie?',
     'What is a boilie?',
     'O que é um boilie?'],
    [['Ein fester, runder Köderball aus Futterteig für das Karpfenangeln', 'A firm, round bait ball made of feed paste for carp fishing', 'Uma bola firme e redonda de massa alimentar para a pesca de carpas'],
     ['Ein Schwimmer aus Kork', 'A float made of cork', 'Uma boia de cortiça'],
     ['Ein Blei in Kugelform', 'A ball-shaped sinker', 'Uma chumbada em forma de bola']],
    0,
    ['Boilies sind gekochte, feste Köderkugeln aus Mehl, Eiern und Zusätzen. Sie werden beim Karpfenangeln an der Grundmontage angeboten.',
     'Boilies are boiled, firm bait balls made of flour, eggs and additives. They are offered on the bottom rig when carp fishing.',
     'Boilies são bolas de isca firmes e cozidas, feitas de farinha, ovos e aditivos. São oferecidas na montagem de fundo na pesca de carpas.'],
    ['koeder', 'karpfen'], ['karpfen']],

  ['bbg-154', 'fanggeraete_und_deren_gebrauch',
    ['Welche Köder eignen sich besonders für den Hecht?',
     'Which baits are especially suitable for pike?',
     'Quais iscas são especialmente adequadas para o lúcio?'],
    [['Toter Köderfisch, Blinker und Gummifisch', 'Dead bait fish, spoons and soft baits', 'Peixe-isca morto, colheres e soft baits'],
     ['Mais und Boilies', 'Corn and boilies', 'Milho e boilies'],
     ['Brot und Teig', 'Bread and dough', 'Pão e massa']],
    0,
    ['Der Hecht ist ein Raubfisch und bevorzugt fischige Köder: tote Köderfische, Blinker, Wobbler und Gummifische. Pflanzliche Köder ignoriert er.',
     'The pike is a predatory fish and prefers fishy baits: dead bait fish, spoons, wobblers and soft baits. It ignores plant baits.',
     'O lúcio é um predador e prefere iscas de peixe: peixe-isca morto, colheres, wobblers e soft baits. Ele ignora iscas vegetais.'],
    ['koeder', 'raubfisch'], ['hecht']],

  ['bbg-155', 'fanggeraete_und_deren_gebrauch',
    ['Welche Köder eignen sich besonders für den Zander?',
     'Which baits are especially suitable for pikeperch?',
     'Quais iscas são especialmente adequadas para o lúcio-perca?'],
    [['Gummifisch, Wobbler und toter Köderfisch', 'Soft baits, wobblers and dead bait fish', 'Soft baits, wobblers e peixe-isca morto'],
     ['Mais und Boilies', 'Corn and boilies', 'Milho e boilies'],
     ['Brot und Teig', 'Bread and dough', 'Pão e massa']],
    0,
    ['Der Zander jagt Fische und nimmt daher Gummifische, Wobbler und tote Köderfische. Auf pflanzliche Köder geht er in der Regel nicht.',
     'The pikeperch hunts fish and therefore takes soft baits, wobblers and dead bait fish. It usually does not go for plant baits.',
     'O lúcio-perca caça peixes e, por isso, aceita soft baits, wobblers e peixe-isca morto. Normalmente não pega iscas vegetais.'],
    ['koeder', 'raubfisch'], ['zander']],

  ['bbg-156', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein toter Köderfisch?',
     'What is a dead bait fish?',
     'O que é um peixe-isca morto?'],
    [['Ein toter Fisch, der als Köder auf Raubfische wie Hecht oder Zander angeboten wird', 'A dead fish offered as bait for predatory fish such as pike or pikeperch', 'Um peixe morto oferecido como isca para predadores como lúcio ou lúcio-perca'],
     ['Ein lebender Fisch als Lockmittel', 'A live fish as attractant', 'Um peixe vivo como atrativo'],
     ['Ein Kunststoffnachbild eines Fisches', 'A plastic imitation of a fish', 'Uma imitação de plástico de um peixe']],
    0,
    ['Tote Köderfische werden an der Grund- oder Posenmontage für Raubfische angeboten. Lebende Fische als Köder sind nach der BbgFischO verboten.',
     'Dead bait fish are offered on bottom or float rigs for predatory fish. Live fish as bait are prohibited under the BbgFischO.',
     'Peixes-isca mortos são oferecidos em montagens de fundo ou com boia para predadores. Peixes vivos como isca são proibidos pela BbgFischO.'],
    ['koeder', 'raubfisch'], ['hecht', 'zander']],

  // --- nets / handling gear ---
  ['bbg-157', 'fanggeraete_und_deren_gebrauch',
    ['Wozu dient der Kescher beim Angeln?',
     'What is the landing net used for when fishing?',
     'Para que serve a rede de aterrissagem na pesca?'],
    [['Zum schonenden Landen gefangener Fische', 'For gently landing caught fish', 'Para aterrissar com cuidado os peixes capturados'],
     ['Zum Fangen von Köderfischen in großen Mengen', 'For catching bait fish in large quantities', 'Para capturar peixes-isca em grandes quantidades'],
     ['Zum Anfüttern des Gewässers', 'For groundbaiting the water', 'Para iscar o fundo da água']],
    0,
    ['Der Kescher wird zum Landen des gedrillten Fisches unter Wasser geführt. Er schont den Fisch, wenn er ausreichend groß und knotenlos ist.',
     'The landing net is guided under the water to land the played fish. It protects the fish when it is large enough and knotless.',
     'A rede de aterrissagem é passada sob a água para aterrissar o peixe brincado. Ela protege o peixe quando é grande o suficiente e sem nós.'],
    ['netz', 'geraete'], ['hecht', 'karpfen', 'zander']],

  ['bbg-158', 'fanggeraete_und_deren_gebrauch',
    ['Worauf sollte man beim Kauf eines Keschers achten?',
     'What should one look for when buying a landing net?',
     'O que se deve observar ao comprar uma rede de aterrissagem?'],
    [['Auf ein knotenloses, großes Netz und eine stabile, ausreichend lange Rute', 'On a knotless, large net and a sturdy, sufficiently long handle', 'Em uma rede sem nós e grande, e em um cabo resistente e suficientemente longo'],
     ['Auf ein möglichst kleines, engmaschiges Netz', 'On the smallest possible, fine-meshed net', 'Em uma rede o menor possível e de malha fina'],
     ['Auf ein Netz aus Metall', 'On a metal net', 'Em uma rede de metal']],
    0,
    ['Knotenlose Netze schonen die Schleimhaut und die Schuppen des Fisches. Das Netz sollte groß genug sein, damit auch größere Fische geschont landen.',
     'Knotless nets protect the slime coat and the scales of the fish. The net should be large enough for larger fish to be landed gently too.',
     'Redes sem nós protegem o muco e as escamas do peixe. A rede deve ser grande o suficiente para aterrissar com cuidado também peixes maiores.'],
    ['netz', 'geraete'], ['hecht', 'karpfen']],

  ['bbg-159', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Setzkescher?',
     'What is a keep net?',
     'O que é um covão (rede de espera)?'],
    [['Ein Netzbehälter, der gefangene Fische vorübergehend im Wasser hält', 'A net container that holds caught fish temporarily in the water', 'Um recipiente de rede que mantém temporariamente os peixes capturados na água'],
     ['Ein Netz zum Landen von Fischen', 'A net for landing fish', 'Uma rede para aterrissar peixes'],
     ['Ein Behälter für Köder', 'A container for bait', 'Um recipiente para iscas']],
    0,
    ['Der Setzkescher hält gefangene Fische bis zum Ende der Angelsitzung im Wasser. Er muss groß genug sein, damit die Fische genügend Platz und Sauerstoff haben.',
     'The keep net holds caught fish in the water until the end of the fishing session. It must be large enough for the fish to have enough space and oxygen.',
     'O covão mantém os peixes capturados na água até o fim da sessão de pesca. Deve ser grande o suficiente para que os peixes tenham espaço e oxigênio suficientes.'],
    ['netz', 'geraete'], ['karpfen', 'plotze']],

  ['bbg-160', 'fanggeraete_und_deren_gebrauch',
    ['Warum muss ein Setzkescher groß genug sein?',
     'Why must a keep net be large enough?',
     'Por que um covão deve ser grande o suficiente?'],
    [['Damit die Fische genügend Platz haben und nicht verletzt werden oder ersticken', 'So that the fish have enough space and are not injured or suffocate', 'Para que os peixes tenham espaço suficiente e não se machuquem nem sufoquem'],
     ['Damit mehr Fische hineinpassen', 'So that more fish fit in', 'Para que caibam mais peixes'],
     ['Damit er schwerer zu stehlen ist', 'So that it is harder to steal', 'Para que seja mais difícil de roubar']],
    0,
    ['In einem zu kleinen Setzkescher liegen die Fische gedrängt, verletzen sich und bekommen zu wenig Sauerstoff. Ein großer Setzkescher ist tierschutzgerecht.',
     'In a keep net that is too small, the fish lie crowded, injure themselves and get too little oxygen. A large keep net is animal-friendly.',
     'Em um covão pequeno demais, os peixes ficam amontoados, se machucam e recebem pouco oxigênio. Um covão grande é respeitoso com os animais.'],
    ['netz', 'tierschutz'], ['karpfen', 'plotze']],

  ['bbg-161', 'fanggeraete_und_deren_gebrauch',
    ['Welche Fanggeräte sind dem Angler in Brandenburg grundsätzlich erlaubt?',
     'Which fishing gear is basically permitted for anglers in Brandenburg?',
     'Quais equipamentos de pesca são basicamente permitidos aos pescadores em Brandemburgo?'],
    [['Die Handangel mit Rute, Schnur und Haken', 'The hand line rod with rod, line and hook', 'A vara de mão com vara, linha e anzol'],
     ['Netze und Reusen aller Art', 'Nets and traps of all kinds', 'Redes e covos de todos os tipos'],
     ['Elektrische Fanggeräte', 'Electric fishing gear', 'Equipamentos de pesca elétricos']],
    0,
    ['Dem Angler ist in Brandenburg die Handangel erlaubt. Netze, Reusen und elektrische Geräte sind Angelfangmethoden, die nicht zugelassen sind.',
     'In Brandenburg the hand line rod is permitted for anglers. Nets, traps and electric devices are angling methods that are not allowed.',
     'Em Brandemburgo, a vara de mão é permitida ao pescador. Redes, covos e equipamentos elétricos são métodos de pesca não permitidos.'],
    ['recht', 'geraete'], ['hecht', 'karpfen']],

  ['bbg-162', 'fanggeraete_und_deren_gebrauch',
    ['Wie viele Handangeln darf eine Person beim Angeln in Brandenburg höchstens verwenden?',
     'How many hand line rods may a person use at most when angling in Brandenburg?',
     'Quantas varas de mão uma pessoa pode usar no máximo ao pescar em Brandemburgo?'],
    [['Zwei Handangeln', 'Two hand line rods', 'Duas varas de mão'],
     ['Fünf Handangeln', 'Five hand line rods', 'Cinco varas de mão'],
     ['Unbegrenzt viele', 'An unlimited number', 'Um número ilimitado']],
    0,
    ['Nach der BbgFischO darf beim Angeln je Person höchstens mit zwei Handangeln gefischt werden. Weitere Ruten wären eine Ordnungswidrigkeit.',
     'Under the BbgFischO a person may fish with at most two hand line rods. Additional rods would be an administrative offence.',
     'Pela BbgFischO, cada pessoa pode pescar com no máximo duas varas de mão. Varas adicionais constituiriam infração administrativa.'],
    ['recht', 'geraete'], ['hecht', 'karpfen']],

  ['bbg-163', 'fanggeraete_und_deren_gebrauch',
    ['Ist das Angeln mit lebenden Fischen als Köder erlaubt?',
     'Is fishing with live fish as bait permitted?',
     'É permitido pescar com peixes vivos como isca?'],
    [['Nein, das Angeln mit lebenden Köderfischen ist verboten', 'No, fishing with live bait fish is prohibited', 'Não, a pesca com peixes-isca vivos é proibida'],
     ['Ja, ohne Einschränkungen', 'Yes, without restrictions', 'Sim, sem restrições'],
     ['Ja, aber nur nachts', 'Yes, but only at night', 'Sim, mas somente à noite']],
    0,
    ['Nach §4 BbgFischO ist das Angeln mit lebenden Fischen als Köder verboten. Erlaubt ist die Verwendung toter Köderfische.',
     'Under section 4 of the BbgFischO, fishing with live fish as bait is prohibited. The use of dead bait fish is permitted.',
     'Pelo §4 da BbgFischO, a pesca com peixes vivos como isca é proibida. É permitido o uso de peixes-isca mortos.'],
    ['recht', 'koeder'], ['hecht', 'zander']],

  ['bbg-164', 'fanggeraete_und_deren_gebrauch',
    ['Was ist beim Angeln mit toten Köderfischen zu beachten?',
     'What should be observed when fishing with dead bait fish?',
     'O que se deve observar ao pescar com peixes-isca mortos?'],
    [['Die Köderfische müssen aus erlaubten Quellen stammen und dürfen keine geschützten Arten sein', 'The bait fish must come from permitted sources and must not be protected species', 'Os peixes-isca devem vir de fontes permitidas e não podem ser espécies protegidas'],
     ['Es dürfen beliebig viele lebende Köderfische verwendet werden', 'Any number of live bait fish may be used', 'Pode-se usar qualquer número de peixes-isca vivos'],
     ['Tote Köderfische sind immer verboten', 'Dead bait fish are always prohibited', 'Peixes-isca mortos são sempre proibidos']],
    0,
    ['Tote Köderfische sind in Brandenburg grundsätzlich erlaubt. Lebende Fische als Köder sind nach §4 BbgFischO verboten, und geschützte Arten dürfen nicht verwendet werden.',
     'Dead bait fish are basically permitted in Brandenburg. Live fish as bait are prohibited under section 4 of the BbgFischO, and protected species must not be used.',
     'Peixes-isca mortos são basicamente permitidos em Brandemburgo. Peixes vivos como isca são proibidos pelo §4 da BbgFischO, e espécies protegidas não podem ser usadas.'],
    ['recht', 'koeder'], ['hecht', 'zander']],

  ['bbg-165', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter Spinnfischen?',
     'What is meant by spinning?',
     'O que se entende por pesca de arremesso (spinning)?'],
    [['Das Angeln mit Kunstködern, die geworfen und eingekurbelt werden', 'Fishing with artificial lures that are cast and reeled in', 'A pesca com iscas artificiais que são lançadas e recolhidas'],
     ['Das Angeln mit lebenden Fischen', 'Fishing with live fish', 'A pesca com peixes vivos'],
     ['Das Angeln ohne Rute', 'Fishing without a rod', 'A pesca sem vara']],
    0,
    ['Beim Spinnfischen werden Kunstköder wie Blinker, Wobbler oder Gummifische ausgeworfen und aktiv geführt. Es zielt vor allem auf Raubfische.',
     'In spinning, artificial lures such as spoons, wobblers or soft baits are cast and actively worked. It targets predatory fish above all.',
     'Na pesca de arremesso, iscas artificiais como colheres, wobblers ou soft baits são lançadas e trabalhadas ativamente. Visa sobretudo peixes predadores.'],
    ['technik', 'raubfisch'], ['hecht', 'zander', 'barsch']],

  ['bbg-166', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter Fliegenfischen?',
     'What is meant by fly fishing?',
     'O que se entende por pesca com mosca?'],
    [['Das Angeln mit künstlichen Fliegen und einer speziellen Fliegenschnur', 'Fishing with artificial flies and a special fly line', 'A pesca com moscas artificiais e uma linha especial de mosca'],
     ['Das Angeln mit schweren Bleien', 'Fishing with heavy sinkers', 'A pesca com chumbadas pesadas'],
     ['Das Angeln mit dem Netz', 'Fishing with a net', 'A pesca com rede']],
    0,
    ['Beim Fliegenfischen wird eine leichte Kunstfliege mit einer gewichteten Fliegenschnur gezielt platziert. Es ist eine anspruchsvolle Technik, besonders für Forellen.',
     'In fly fishing a light artificial fly is placed precisely with a weighted fly line. It is a demanding technique, especially for trout.',
     'Na pesca com mosca, uma mosca artificial leve é colocada com precisão usando uma linha de mosca ponderada. É uma técnica exigente, especialmente para trutas.'],
    ['technik'], ['forelle', 'asche']],

  ['bbg-167', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter \u201eDrillen\u201c eines Fisches?',
     'What is meant by \u201cplaying\u201d a fish?',
     'O que se entende por \u201cbrigar com\u201d um peixe?'],
    [['Den kontrollierten Kampf mit einem gehaktem Fisch, bis er ermüdet ist', 'The controlled fight with a hooked fish until it is tired', 'A luta controlada com um peixe fisgado até que ele se canse'],
     ['Das schnelle Einholen ohne Rücksicht', 'The fast reeling in without consideration', 'O recolhimento rápido sem consideração'],
     ['Das Töten des Fisches mit einem Schlag', 'Killing the fish with a blow', 'A matança do peixe com um golpe']],
    0,
    ['Beim Drillen wird der Fisch durch dosierten Schnurzug und Rutenhaltung ermüdet, ohne ihn zu überlasten. Erst danach wird er gekeschert.',
     'When playing, the fish is tired through dosed line tension and rod position without overloading it. Only then is it netted.',
     'Ao brigar, o peixe é cansado por tensão controlada da linha e posição da vara, sem sobrecarga. Só então é aterrissado com a rede.'],
    ['technik'], ['hecht', 'karpfen', 'wels']],

  ['bbg-168', 'fanggeraete_und_deren_gebrauch',
    ['Wie drillt man einen großen Fisch richtig?',
     'How does one play a large fish correctly?',
     'Como se briga corretamente com um peixe grande?'],
    [['Mit eingestellter Bremse, gebogener Rute und seitlichem Zug', 'With the drag set, the rod bent and side pressure', 'Com o freio ajustado, a vara curvada e pressão lateral'],
     ['Mit straff gesperrter Rolle und senkrechtem Rutenhalt', 'With the reel locked tight and the rod held vertically', 'Com o molinete travado e a vara vertical'],
     ['Durch sofortiges Herausziehen des Fisches', 'By immediately yanking the fish out', 'Puxando o peixe imediatamente para fora']],
    0,
    ['Beim Drillen großer Fische gibt die eingestellte Bremse dosiert Schnur ab, die Rute federt und seitlicher Zug ermüdet den Fisch. Hektik führt zu Schnurrissen.',
     'When playing large fish, the set drag releases line in doses, the rod flexes and side pressure tires the fish. Haste leads to line breaks.',
     'Ao brigar com peixes grandes, o freio ajustado libera linha em doses, a vara flexiona e a pressão lateral cansa o peixe. Pressa causa quebras de linha.'],
    ['technik'], ['karpfen', 'hecht', 'wels']],

  ['bbg-169', 'fanggeraete_und_deren_gebrauch',
    ['Welches Zubehör gehört zur Grundausstattung eines Anglers?',
     'Which accessories belong to the basic equipment of an angler?',
     'Quais acessórios fazem parte do equipamento básico de um pescador?'],
    [['Rute, Rolle, Schnur, Haken, Kescher und Pose', 'Rod, reel, line, hooks, landing net and float', 'Vara, molinete, linha, anzóis, rede de aterrissagem e boia'],
     ['Nur ein Messer', 'Only a knife', 'Apenas uma faca'],
     ['Nur ein Netz', 'Only a net', 'Apenas uma rede']],
    0,
    ['Zur Grundausstattung gehören Rute, Rolle, Schnur, Haken, Bleie, Posen, Kescher und geeignete Köder sowie Werkzeuge wie Hakenlöser und Betäubungsstock.',
     'Basic equipment includes rod, reel, line, hooks, sinkers, floats, landing net and suitable baits as well as tools such as hook removers and a priest.',
     'O equipamento básico inclui vara, molinete, linha, anzóis, chumbadas, boias, rede de aterrissagem e iscas adequadas, além de ferramentas como removedor de anzol e bastão de atordoamento.'],
    ['geraete'], ['hecht', 'karpfen', 'plotze']],

  ['bbg-170', 'fanggeraete_und_deren_gebrauch',
    ['Wie sollte die Angelschnur nach dem Angeln gepflegt werden?',
     'How should the fishing line be cared for after fishing?',
     'Como a linha de pesca deve ser cuidada após a pesca?'],
    [['Sie sollte getrocknet und auf Beschädigungen geprüft werden', 'It should be dried and checked for damage', 'Ela deve ser seca e verificada quanto a danos'],
     ['Sie sollte in der prallen Sonne gelagert werden', 'It should be stored in full sun', 'Ela deve ser guardada sob sol forte'],
     ['Sie muss nicht gepflegt werden', 'It does not need care', 'Ela não precisa de cuidados']],
    0,
    ['Nach dem Angeln wird die Schnur getrocknet, auf Scheuerstellen und Knoten geprüft und vor UV-Licht geschützt gelagert. So behält sie ihre Tragkraft.',
     'After fishing, the line is dried, checked for chafe and knots and stored protected from UV light. This keeps its breaking strength.',
     'Após a pesca, a linha é seca, verificada quanto a atritos e nós e guardada protegida da luz UV. Assim ela mantém sua resistência.'],
    ['schnur', 'pflege'], ['hecht', 'karpfen']],

  ['bbg-171', 'fanggeraete_und_deren_gebrauch',
    ['Warum sollte man beim Raubfischangeln eine stabilere Schnur wählen?',
     'Why should one choose a stronger line when fishing for predatory fish?',
     'Por que se deve escolher uma linha mais resistente na pesca de predadores?'],
    [['Weil Raubfische kräftige Zähne haben und heftige Fluchten machen', 'Because predatory fish have strong teeth and make violent runs', 'Porque os predadores têm dentes fortes e fazem fugas violentas'],
     ['Weil sie dann weniger sichtbar ist', 'Because it is then less visible', 'Porque então ela é menos visível'],
     ['Weil sie dann mehr Bisse zeigt', 'Because it then shows more bites', 'Porque então ela mostra mais mordidas']],
    0,
    ['Raubfische wie Hecht, Zander und Wels haben kräftige Zähne und können starke Fluchten ziehen. Eine stabile Schnur und ein Vorfach verhindern Verluste.',
     'Predatory fish such as pike, pikeperch and catfish have strong teeth and can make powerful runs. A strong line and a leader prevent losses.',
     'Predadores como lúcio, lúcio-perca e siluro têm dentes fortes e podem fazer fugas poderosas. Uma linha resistente e um líder evitam perdas.'],
    ['schnur', 'raubfisch'], ['hecht', 'zander', 'wels']],

  ['bbg-172', 'fanggeraete_und_deren_gebrauch',
    ['Welche Bedeutung hat die Wurfweite beim Angeln?',
     'What significance does casting distance have when fishing?',
     'Qual é a importância da distância de lançamento na pesca?'],
    [['Sie ermöglicht es, Fische zu erreichen, die weit vom Ufer stehen', 'It makes it possible to reach fish that hold far from the bank', 'Ela permite alcançar peixes que estão longe da margem'],
     ['Sie ist völlig bedeutungslos', 'It is completely irrelevant', 'Ela é totalmente irrelevante'],
     ['Sie vergrößert immer die Zahl der Fische im Gewässer', 'It always increases the number of fish in the water', 'Ela sempre aumenta o número de peixes na água']],
    0,
    ['Eine gute Wurfweite erweitert die angelbaren Bereiche, besonders an großen Seen oder Flüssen. Sie hängt von Rute, Rolle, Schnur und Technik ab.',
     'A good casting distance expands the fishable areas, especially on large lakes or rivers. It depends on rod, reel, line and technique.',
     'Uma boa distância de lançamento amplia as áreas pescáveis, especialmente em grandes lagos ou rios. Ela depende da vara, do molinete, da linha e da técnica.'],
    ['technik'], ['karpfen', 'zander']],

  ['bbg-173', 'fanggeraete_und_deren_gebrauch',
    ['Welchen Zweck hat das Anfüttern mit erlaubten Futtermitteln?',
     'What purpose does groundbaiting with permitted feed have?',
     'Qual é o objetivo da iscagem de fundo com alimentos permitidos?'],
    [['Fische an die Angelstelle zu locken und dort zu halten', 'To attract fish to the fishing spot and keep them there', 'Atrair os peixes ao local de pesca e mantê-los lá'],
     ['Fische zu betäuben', 'To stun the fish', 'Atordoar os peixes'],
     ['Das Wasser zu erwärmen', 'To warm up the water', 'Aquecer a água']],
    0,
    ['Durch Anfüttern wird die Angelstelle attraktiver. Es ist erlaubt, solange nur zulässige Futtermittel verwendet und die Gewässervorschriften beachtet werden.',
     'Groundbaiting makes the fishing spot more attractive. It is permitted as long as only admissible feed is used and the water regulations are observed.',
     'A iscagem torna o local de pesca mais atraente. É permitida desde que sejam usados apenas alimentos admissíveis e as regras do corpo d\u2019água sejam observadas.'],
    ['koeder', 'technik'], ['karpfen', 'plotze']],

  ['bbg-174', 'fanggeraete_und_deren_gebrauch',
    ['Warum sollte ein Angler Ersatzhaken und Zubehör mitführen?',
     'Why should an angler carry spare hooks and accessories?',
     'Por que um pescador deve levar anzóis e acessórios reservas?'],
    [['Weil Haken brechen oder ausreißen und Montagen verloren gehen können', 'Because hooks can break or tear out and rigs can be lost', 'Porque anzóis podem quebrar ou arrebentar e montagens podem se perder'],
     ['Weil man damit Fische fangen kann, ohne zu angeln', 'Because one can catch fish with them without fishing', 'Porque com eles se captura peixes sem pescar'],
     ['Weil sie als Köder dienen', 'Because they serve as bait', 'Porque eles servem de isca']],
    0,
    ['Verlorene oder beschädigte Haken und Montagen sind beim Angeln normal. Ersatzmaterial sorgt dafür, dass die Angeltour nicht abgebrochen werden muss.',
     'Lost or damaged hooks and rigs are normal when fishing. Spare material ensures that the fishing trip does not have to be abandoned.',
     'Anzóis e montagens perdidos ou danificados são normais na pesca. Material reserva garante que a pescaria não precise ser interrompida.'],
    ['geraete'], ['hecht', 'karpfen']],

  ['bbg-175', 'fanggeraete_und_deren_gebrauch',
    ['Worauf muss man beim Angeln mit der Posenmontage in der Strömung achten?',
     'What must one pay attention to when float fishing in the current?',
     'O que se deve observar ao pescar com boia na correnteza?'],
    [['Die Pose und die Bleimenge müssen an die Strömung angepasst werden', 'The float and the amount of shot must be adapted to the current', 'A boia e a quantidade de chumbo devem ser adaptadas à correnteza'],
     ['Die Pose muss immer ohne Blei verwendet werden', 'The float must always be used without shot', 'A boia deve ser sempre usada sem chumbo'],
     ['In der Strömung darf nie mit Pose geangelt werden', 'Float fishing is never allowed in the current', 'Nunca se pode pescar com boia na correnteza']],
    0,
    ['In strömendem Wasser treibt die Pose ab. Durch angepasste Bleimenge und Posenwahl bleibt der Köder am gewünschten Platz, ohne unkontrolliert abzutreiben.',
     'In flowing water the float drifts away. With an adapted amount of shot and float choice, the bait stays in the desired place without drifting uncontrolled.',
     'Em água corrente, a boia deriva. Com quantidade de chumbo e boia adequadas, a isca permanece no lugar desejado sem derivar descontroladamente.'],
    ['pose', 'montage'], ['plotze', 'karpfen']],

  ['bbg-176', 'fanggeraete_und_deren_gebrauch',
    ['Welche Gefahr besteht beim Angeln mit zu dünner Schnur auf große Fische?',
     'What danger exists when fishing for large fish with too thin a line?',
     'Qual é o perigo de pescar peixes grandes com linha fina demais?'],
    [['Die Schnur kann beim Drillen reißen', 'The line can break when playing the fish', 'A linha pode arrebentar ao brigar com o peixe'],
     ['Der Fisch wird zu schnell müde', 'The fish tires too quickly', 'O peixe se cansa rápido demais'],
     ['Der Haken wird zu groß', 'The hook becomes too large', 'O anzol fica grande demais']],
    0,
    ['Eine zu dünne Schnur ist der Größe des Zielfisches nicht gewachsen. Beim Drillen übersteigt der Zug des Fisches die Tragkraft, und die Schnur reißt.',
     'A line that is too thin is no match for the size of the target fish. When playing, the pull of the fish exceeds the breaking strength and the line breaks.',
     'Uma linha fina demais não suporta o tamanho do peixe alvo. Ao brigar, o puxão do peixe supera a resistência e a linha arrebenta.'],
    ['schnur', 'technik'], ['karpfen', 'hecht', 'wels']],

  ['bbg-177', 'fanggeraete_und_deren_gebrauch',
    ['Welche Funktion haben Haken mit großem Öhr?',
     'What function do hooks with a large eye have?',
     'Qual é a função dos anzóis com olhal grande?'],
    [['Sie lassen sich auch mit dicken Schnüren oder Vorfächern leicht befestigen', 'They can be attached easily even to thick lines or leaders', 'Eles podem ser presos facilmente mesmo a linhas grossas ou líderes'],
     ['Sie fangen mehr Fische', 'They catch more fish', 'Eles capturam mais peixes'],
     ['Sie dienen als Bissanzeiger', 'They serve as bite indicators', 'Eles servem de indicadores de mordida']],
    0,
    ['Ein großes Öhr erleichtert das Anknoten dicker Schnüre und Vorfächer. Das ist besonders beim Raubfischangeln mit kräftigen Schnüren wichtig.',
     'A large eye makes it easier to tie thick lines and leaders. This is especially important when predatory fishing with strong lines.',
     'Um olhal grande facilita dar nós em linhas grossas e líderes. Isso é especialmente importante na pesca de predadores com linhas fortes.'],
    ['haken', 'geraete'], ['hecht', 'zander', 'wels']],

  ['bbg-178', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter einer \u201eBleifreien Montage\u201c?',
     'What is meant by a \u201clead-free rig\u201c?',
     'O que se entende por \u201cmontagem sem chumbo\u201d?'],
    [['Eine Montage, die statt Blei unbedenkliche Materialien wie Wolfram oder Stahl verwendet', 'A rig that uses harmless materials such as tungsten or steel instead of lead', 'Uma montagem que usa materiais inofensivos, como tungstênio ou aço, em vez de chumbo'],
     ['Eine Montage ohne Haken', 'A rig without a hook', 'Uma montagem sem anzol'],
     ['Eine Montage nur für den Winter', 'A rig only for winter', 'Uma montagem somente para o inverno']],
    0,
    ['Bleifreie Montagen ersetzen Bleigeschosse durch umweltfreundlichere Materialien. So wird die Belastung des Gewässers mit Blei verringert.',
     'Lead-free rigs replace lead weights with more environmentally friendly materials. This reduces the lead load on the water.',
     'Montagens sem chumbo substituem as chumbadas por materiais mais ecológicos. Assim, a carga de chumbo na água é reduzida.'],
    ['montage', 'umwelt'], ['hecht', 'karpfen']],

  ['bbg-179', 'fanggeraete_und_deren_gebrauch',
    ['Warum ist Blei in Gewässern problematisch?',
     'Why is lead problematic in waters?',
     'Por que o chumbo é problemático nas águas?'],
    [['Weil sich Blei im Wasser und in den Lebewesen anreichern kann', 'Because lead can accumulate in the water and in the organisms', 'Porque o chumbo pode se acumular na água e nos organismos'],
     ['Weil es die Schnur färbt', 'Because it colours the line', 'Porque ele tinge a linha'],
     ['Weil es den Fisch anlockt', 'Because it attracts the fish', 'Porque ele atrai os peixes']],
    0,
    ['Verlorene Bleie verbleiben im Gewässer und können von Tieren aufgenommen werden. Deshalb werden bleifreie Alternativen immer häufiger eingesetzt.',
     'Lost sinkers remain in the water and can be taken up by animals. That is why lead-free alternatives are increasingly used.',
     'Chumbadas perdidas permanecem na água e podem ser ingeridas por animais. Por isso, alternativas sem chumbo são cada vez mais usadas.'],
    ['umwelt', 'montage'], ['hecht', 'karpfen']],

  ['bbg-180', 'fanggeraete_und_deren_gebrauch',
    ['Welche Ködergröße passt zu großen Raubfischen?',
     'Which bait size suits large predatory fish?',
     'Qual tamanho de isca combina com grandes predadores?'],
    [['Große Köderfische und große Kunstköder', 'Large bait fish and large artificial lures', 'Peixes-isca grandes e iscas artificiais grandes'],
     ['Immer winzige Köder', 'Always tiny baits', 'Sempre iscas minúsculas'],
     ['Nur pflanzliche Köder', 'Only plant baits', 'Somente iscas vegetais']],
    0,
    ['Große Raubfische wie große Hechte und Welse bevorzugen große Beute. Ein großer Köder reduziert die Zahl kleiner Bisse und zielt auf große Fische.',
     'Large predatory fish such as big pike and catfish prefer large prey. A large bait reduces the number of small bites and targets large fish.',
     'Grandes predadores, como lúcios e siluros grandes, preferem presas grandes. Uma isca grande reduz as mordidas pequenas e visa peixes grandes.'],
    ['koeder', 'raubfisch'], ['hecht', 'wels', 'zander']],
]
