// Category: fanggeraete_und_deren_gebrauch — Fishing gear & use (1/2)
export const questions = [
  // --- rods / reels / lines ---
  ['bbg-121', 'fanggeraete_und_deren_gebrauch',
    ['Wofür verwendet man eine Spinnrute?',
     'What is a spinning rod used for?',
     'Para que serve uma vara de arremesso (spinning)?'],
    [['Zum Werfen und Führen von Kunstködern beim Raubfischangeln', 'For casting and working artificial lures when fishing for predatory fish', 'Para lançar e trabalhar iscas artificiais na pesca de peixes predadores'],
     ['Nur zum Grundangeln auf Karpfen', 'Only for bottom fishing for carp', 'Somente para pesca de fundo de carpas'],
     ['Nur als Dekoration', 'Only as decoration', 'Somente como decoração']],
    0,
    ['Die Spinnrute ist eine relativ steife Rute mit Führungsringen, mit der Kunstköder wie Blinker, Wobbler oder Gummifische geworfen und geführt werden.',
     'The spinning rod is a relatively stiff rod with line guides used to cast and work artificial lures such as spoons, wobblers or soft baits.',
     'A vara de arremesso é uma vara relativamente rígida com passadores, usada para lançar e trabalhar iscas artificiais como colheres, wobblers ou soft baits.'],
    ['rute', 'geraete'], ['hecht', 'zander', 'barsch']],

  ['bbg-122', 'fanggeraete_und_deren_gebrauch',
    ['Wozu dient die Fliegenrute?',
     'What is the fly rod used for?',
     'Para que serve a vara de mosca (fly fishing)?'],
    [['Zum Fliegenfischen mit künstlichen Fliegen', 'For fly fishing with artificial flies', 'Para pesca com mosca, usando moscas artificiais'],
     ['Zum Werfen schwerer Bleie', 'For casting heavy sinkers', 'Para lançar chumbadas pesadas'],
     ['Zum Angeln mit dem Köderfisch', 'For fishing with bait fish', 'Para pescar com peixe-isca']],
    0,
    ['Die Fliegenrute ist eine sehr weiche, lange Rute, mit der leichte, künstliche Fliegen präzise platziert werden. Das Gewicht der Schnur treibt dabei die Fliege.',
     'The fly rod is a very soft, long rod with which light artificial flies are placed precisely. The weight of the line drives the fly.',
     'A vara de mosca é uma vara longa e muito flexível, com a qual moscas artificiais leves são colocadas com precisão. O peso da linha impulsiona a mosca.'],
    ['rute', 'geraete'], ['forelle', 'asche']],

  ['bbg-123', 'fanggeraete_und_deren_gebrauch',
    ['Welche Aufgabe hat die Rute beim Drillen eines Fisches?',
     'What task does the rod have when playing a fish?',
     'Qual é a função da vara ao brigar com um peixe?'],
    [['Sie federt und schont die Schnur durch ihre Biegsamkeit', 'It flexes and protects the line through its resilience', 'Ela flexiona e protege a linha por sua elasticidade'],
     ['Sie speichert die gefangenen Fische', 'It stores the caught fish', 'Ela armazena os peixes capturados'],
     ['Sie dient nur zum Werfen, nicht zum Drillen', 'It is only for casting, not for playing fish', 'Ela serve apenas para lançar, não para brigar com o peixe']],
    0,
    ['Die Biegsamkeit der Rute dämpft ruckartige Züge des Fisches und verhindert so Schnurrisse. Je weicher die Rute, desto mehr federt sie.',
     'The flexibility of the rod dampens sudden pulls of the fish and thus prevents line breaks. The softer the rod, the more it flexes.',
     'A flexibilidade da vara amortece os puxões súbitos do peixe e evita quebras de linha. Quanto mais flexível a vara, mais ela amortece.'],
    ['rute', 'technik'], ['hecht', 'karpfen']],

  ['bbg-124', 'fanggeraete_und_deren_gebrauch',
    ['Wofür ist eine Stationärrolle besonders geeignet?',
     'What is a fixed-spool (spinning) reel especially suitable for?',
     'Para que um molinete de carretel fixo é especialmente adequado?'],
    [['Für vielseitiges Angeln mit leichten bis mittleren Ködern', 'For versatile fishing with light to medium lures and baits', 'Para pesca versátil com iscas leves a médias'],
     ['Nur für das Angeln im Meer', 'Only for sea fishing', 'Somente para a pesca no mar'],
     ['Nur für das Speerfischen', 'Only for spearfishing', 'Somente para a pesca submarina']],
    0,
    ['Stationärrollen sind leicht, vielseitig und einfach zu bedienen. Sie eignen sich für Spinn-, Posen- und Grundangeln in vielen Einsatzbereichen.',
     'Fixed-spool reels are light, versatile and easy to use. They suit spinning, float and bottom fishing in many applications.',
     'Os molinetes de carretel fixo são leves, versáteis e fáceis de usar. Servem para pesca de arremesso, com boia e de fundo em muitas situações.'],
    ['rolle', 'geraete'], ['hecht', 'barsch', 'karpfen']],

  ['bbg-125', 'fanggeraete_und_deren_gebrauch',
    ['Was ist eine Baitcast-Rolle (Multirolle)?',
     'What is a baitcasting reel?',
     'O que é um carretilha (molinete de baitcasting)?'],
    [['Eine Rolle mit drehender Spule, die auf der Rute aufliegt und sich für schwere Köder eignet', 'A reel with a rotating spool that rests on top of the rod and suits heavy lures', 'Um molinete com carretel rotativo que fica sobre a vara e serve para iscas pesadas'],
     ['Eine Rolle ohne Schnur', 'A reel without line', 'Um molinete sem linha'],
     ['Ein Netz zum Fangen von Fischen', 'A net for catching fish', 'Uma rede para capturar peixes']],
    0,
    ['Die Baitcast-Rolle sitzt auf der Rutenoberseite und hat eine drehende Spule. Sie eignet sich für kräftige Schnüre und schwere Köder, erfordert aber Übung im Wurf.',
     'The baitcasting reel sits on top of the rod and has a rotating spool. It suits strong lines and heavy lures but requires practice in casting.',
     'A carretilha fica sobre a vara e tem carretel rotativo. Serve para linhas fortes e iscas pesadas, mas exige prática no lançamento.'],
    ['rolle', 'geraete'], ['hecht', 'zander', 'wels']],

  ['bbg-126', 'fanggeraete_und_deren_gebrauch',
    ['Wofür ist die Bremse einer Rolle da?',
     'What is the drag of a reel for?',
     'Para que serve o freio de um molinete?'],
    [['Sie gibt bei starkem Zug des Fisches Schnur ab und verhindert so Schnurrisse', 'It releases line under a strong pull of the fish and thus prevents line breaks', 'Ele libera linha sob puxão forte do peixe e assim evita quebras'],
     ['Sie zieht die Schnur automatisch ein', 'It automatically winds in the line', 'Ele recolhe a linha automaticamente'],
     ['Sie hält den Haken fest', 'It holds the hook firmly', 'Ele segura o anzol firmemente']],
    0,
    ['Die Bremse erlaubt dem Fisch, bei zu starkem Zug Schnur von der Rolle zu ziehen. Das schont die Schnur und ermüdet den Fisch gleichmäßig.',
     'The drag allows the fish to pull line from the reel under too much tension. This protects the line and tires the fish evenly.',
     'O freio permite que o peixe puxe linha do molinete sob tensão excessiva. Isso protege a linha e cansa o peixe de forma uniforme.'],
    ['rolle', 'technik'], ['karpfen', 'hecht', 'wels']],

  ['bbg-127', 'fanggeraete_und_deren_gebrauch',
    ['Woraus bestehen moderne Angelschnüre meistens?',
     'What are modern fishing lines mostly made of?',
     'Do que as linhas de pesca modernas geralmente são feitas?'],
    [['Aus Kunststoffen wie Nylon (Monofil), Fluorocarbon oder Geflecht', 'From plastics such as nylon (monofilament), fluorocarbon or braid', 'De plásticos como nylon (monofilamento), fluorocarbono ou trançado'],
     ['Aus Metallstahl ohne Ausnahme', 'From steel without exception', 'De aço, sem exceção'],
     ['Aus pflanzlichen Fasern wie Baumwolle', 'From plant fibres such as cotton', 'De fibras vegetais como algodão']],
    0,
    ['Moderne Schnüre bestehen überwiegend aus Kunststoff. Nylon ist dehnbar und knotig, Fluorocarbon fast unsichtbar, Geflecht sehr reißfest und kaum dehnbar.',
     'Modern lines are mostly made of plastic. Nylon is stretchy and knots well, fluorocarbon is nearly invisible, braid is very strong and barely stretches.',
     'As linhas modernas são feitas principalmente de plástico. O nylon é elástico e dá bons nós, o fluorocarbono é quase invisível e o trançado é muito resistente e quase não estica.'],
    ['schnur', 'geraete'], ['hecht', 'karpfen']],

  ['bbg-128', 'fanggeraete_und_deren_gebrauch',
    ['Welche Eigenschaft hat eine geflochtene Schnur?',
     'What property does a braided line have?',
     'Qual é a propriedade de uma linha trançada?'],
    [['Sie ist sehr reißfest und hat kaum Dehnung', 'It is very strong and has almost no stretch', 'Ela é muito resistente e quase não estica'],
     ['Sie dehnt sich stark und ist unsichtbar', 'It stretches a lot and is invisible', 'Ela estica muito e é invisível'],
     ['Sie schwimmt immer an der Oberfläche', 'It always floats on the surface', 'Ela sempre flutua na superfície']],
    0,
    ['Geflochtene Schnüre bestehen aus mehreren verflochtenen Fasern. Sie sind dünner und reißfester als Monofil und übertragen Bisse direkt, haben aber kaum Dehnung.',
     'Braided lines consist of several interwoven fibres. They are thinner and stronger than monofilament and transmit bites directly, but have almost no stretch.',
     'As linhas trançadas consistem em várias fibras entrelaçadas. São mais finas e resistentes que o monofilamento e transmitem as mordidas diretamente, mas quase não esticam.'],
    ['schnur', 'geraete'], ['zander', 'hecht']],

  ['bbg-129', 'fanggeraete_und_deren_gebrauch',
    ['Welche Eigenschaft hat Fluorocarbon-Schnur?',
     'What property does fluorocarbon line have?',
     'Qual é a propriedade da linha de fluorocarbono?'],
    [['Sie ist unter Wasser nahezu unsichtbar und sinkt', 'It is almost invisible underwater and sinks', 'Ela é quase invisível debaixo d\u2019água e afunda'],
     ['Sie ist sehr dehnbar und schwimmt', 'It is very stretchy and floats', 'Ela é muito elástica e flutua'],
     ['Sie leuchtet nachts', 'It glows at night', 'Ela brilha à noite']],
    0,
    ['Fluorocarbon hat einen Brechungsindex, der dem Wasser sehr ähnlich ist, und ist daher kaum sichtbar. Zudem sinkt es, was es als Vorfach beliebt macht.',
     'Fluorocarbon has a refractive index very similar to water and is therefore hardly visible. It also sinks, which makes it popular as a leader.',
     'O fluorocarbono tem índice de refração muito semelhante ao da água e, por isso, é quase invisível. Também afunda, o que o torna popular como líder.'],
    ['schnur', 'geraete'], ['zander', 'barsch']],

  ['bbg-130', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Vorfach?',
     'What is a leader (Vorfach)?',
     'O que é um líder (Vorfach)?'],
    [['Ein Verbindungsstück zwischen Hauptschnur und Haken beziehungsweise Köder', 'A connecting piece between the main line and the hook or bait', 'Um trecho de conexão entre a linha principal e o anzol ou a isca'],
     ['Ein Schwimmer zum Anzeigen von Bissen', 'A float for indicating bites', 'Uma boia para indicar mordidas'],
     ['Ein Behälter für Köder', 'A container for bait', 'Um recipiente para iscas']],
    0,
    ['Das Vorfach verbindet die Hauptschnur mit dem Haken oder Köder. Es tarnt die Montage, schützt vor Abrieb und kann bei starkem Zug als Sollbruchstelle dienen.',
     'The leader connects the main line with the hook or bait. It conceals the rig, protects against abrasion and can serve as a break point under strong tension.',
     'O líder conecta a linha principal ao anzol ou à isca. Ele camufla a montagem, protege contra o atrito e pode servir de ponto de ruptura sob forte tensão.'],
    ['schnur', 'montage'], ['hecht', 'zander']],

  ['bbg-131', 'fanggeraete_und_deren_gebrauch',
    ['Warum sollte man beim Raubfischangeln ein Vorfach verwenden?',
     'Why should one use a leader when fishing for predatory fish?',
     'Por que se deve usar um líder na pesca de peixes predadores?'],
    [['Weil Raubfische wie Hecht und Zander scharfe Zähne haben und die Schnur durchbeißen können', 'Because predatory fish such as pike and pikeperch have sharp teeth and can bite through the line', 'Porque predadores como lúcio e lúcio-perca têm dentes afiados e podem cortar a linha'],
     ['Weil die Schnur sonst zu schwer wird', 'Because the line would otherwise be too heavy', 'Porque senão a linha fica pesada demais'],
     ['Weil das Vorfach den Köder vergrößert', 'Because the leader enlarges the bait', 'Porque o líder aumenta a isca']],
    0,
    ['Ein Stahl- oder Fluorocarbonvorfach schützt die Hauptschnur vor den Zähnen der Raubfische und vor Abrieb an Hindernissen im Wasser.',
     'A steel or fluorocarbon leader protects the main line from the teeth of predatory fish and from abrasion on underwater obstacles.',
     'Um líder de aço ou fluorocarbono protege a linha principal dos dentes dos predadores e do atrito com obstáculos subaquáticos.'],
    ['schnur', 'montage'], ['hecht', 'zander', 'wels']],

  // --- hooks ---
  ['bbg-132', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Drilling?',
     'What is a treble hook?',
     'O que é um anzol triplo?'],
    [['Ein Haken mit drei Hakenpunkten, der oft an Kunstködern sitzt', 'A hook with three hook points that is often attached to artificial lures', 'Um anzol com três pontas, frequentemente preso a iscas artificiais'],
     ['Ein Haken ohne Widerhaken', 'A barbless hook', 'Um anzol sem farpa'],
     ['Eine Rolle mit drei Spulen', 'A reel with three spools', 'Um molinete com três carretéis']],
    0,
    ['Drillinge besitzen drei Hakenpunkte an einem gemeinsamen Schaft. Sie werden besonders an Blinkern, Wobblern und Köderfischmontagen verwendet.',
     'Treble hooks have three hook points on a common shank. They are especially used on spoons, wobblers and bait fish rigs.',
     'Os anzóis triplos têm três pontas em uma haste comum. São usados especialmente em colheres, wobblers e montagens com peixe-isca.'],
    ['haken', 'geraete'], ['hecht', 'zander']],

  ['bbg-133', 'fanggeraete_und_deren_gebrauch',
    ['Welche Funktion hat der Widerhaken am Angelhaken?',
     'What function does the barb on a fishing hook have?',
     'Qual é a função da farpa no anzol?'],
    [['Er verhindert, dass sich der Haken leicht aus dem Fischmaul löst', 'It prevents the hook from coming out of the fish\u2019s mouth easily', 'Ela impede que o anzol se solte facilmente da boca do peixe'],
     ['Er dient als Bissanzeiger', 'It serves as a bite indicator', 'Ela serve como indicador de mordida'],
     ['Er macht den Köder attraktiver', 'It makes the bait more attractive', 'Ela torna a isca mais atraente']],
    0,
    ['Der Widerhaken hält den Haken im Fisch. Nachteil: Das Lösen des Hakens ist schwieriger, was beim Zurücksetzen von Fischen mehr Zeit und Vorsicht erfordert.',
     'The barb holds the hook in the fish. Disadvantage: removing the hook is harder, which takes more time and care when releasing fish.',
     'A farpa mantém o anzol no peixe. Desvantagem: remover o anzol é mais difícil, o que exige mais tempo e cuidado ao soltar os peixes.'],
    ['haken', 'geraete'], ['karpfen', 'hecht']],

  ['bbg-134', 'fanggeraete_und_deren_gebrauch',
    ['Warum sind widerhakenlose Haken beim Fangen und Freilassen von Vorteil?',
     'Why are barbless hooks advantageous for catch and release?',
     'Por que anzóis sem farpa são vantajosos na pesca de captura e soltura?'],
    [['Weil sich der Haken schneller und schonender lösen lässt', 'Because the hook can be removed faster and more gently', 'Porque o anzol pode ser removido mais rápido e com menos dano'],
     ['Weil sie die Fische automatisch größer machen', 'Because they automatically make the fish larger', 'Porque eles automaticamente deixam os peixes maiores'],
     ['Weil sie ohne Köder fangen', 'Because they catch without bait', 'Porque eles capturam sem isca']],
    0,
    ['Widerhakenlose Haken verletzen das Fischmaul weniger und lassen sich schnell lösen. Sie sind ideal, wenn Fische schonend zurückgesetzt werden sollen.',
     'Barbless hooks injure the fish\u2019s mouth less and can be removed quickly. They are ideal when fish should be released gently.',
     'Anzóis sem farpa ferem menos a boca do peixe e podem ser removidos rapidamente. São ideais quando os peixes devem ser soltos com cuidado.'],
    ['haken', 'fangen-und-freilassen'], ['hecht', 'zander', 'barsch']],

  ['bbg-135', 'fanggeraete_und_deren_gebrauch',
    ['Welche Hakenform erleichtert das Lösen des Hakens beim Friedfischangeln?',
     'Which hook shape makes removing the hook easier when coarse fishing?',
     'Qual formato de anzol facilita a remoção do anzol na pesca de peixes não predadores?'],
    [['Ein Haken mit langem Schaft', 'A hook with a long shank', 'Um anzol com haste longa'],
     ['Ein Haken ohne Öhr', 'A hook without an eye', 'Um anzol sem olhal'],
     ['Ein Haken aus Blei', 'A hook made of lead', 'Um anzol feito de chumbo']],
    0,
    ['Haken mit langem Schaft lassen sich auch bei tief geschluckten Ködern leichter fassen und lösen. Das schont den Fisch und erleichtert die Arbeit des Anglers.',
     'Hooks with a long shank are easier to grasp and remove even when the bait is swallowed deeply. This protects the fish and makes the angler\u2019s work easier.',
     'Anzóis com haste longa são mais fáceis de segurar e remover mesmo com a isca engolida fundo. Isso protege o peixe e facilita o trabalho do pescador.'],
    ['haken', 'geraete'], ['karpfen', 'plotze']],

  // --- floats / sinkers / rigs ---
  ['bbg-136', 'fanggeraete_und_deren_gebrauch',
    ['Wozu dient die Pose (Schwimmer) beim Angeln?',
     'What is the float used for when fishing?',
     'Para que serve a boia na pesca?'],
    [['Sie hält den Köder in der gewünschten Tiefe und zeigt Bisse an', 'It keeps the bait at the desired depth and indicates bites', 'Ela mantém a isca na profundidade desejada e indica as mordidas'],
     ['Sie beschwert die Schnur', 'It weights the line', 'Ela dá peso à linha'],
     ['Sie dient als Köder', 'It serves as bait', 'Ela serve de isca']],
    0,
    ['Die Pose hält den Haken mit dem Köder in der gewählten Wassertiefe. Sobald ein Fisch beißt, bewegt sich die Pose und zeigt den Biss an.',
     'The float keeps the hook with the bait at the chosen depth. As soon as a fish bites, the float moves and indicates the bite.',
     'A boia mantém o anzol com a isca na profundidade escolhida. Assim que um peixe morde, a boia se move e indica a mordida.'],
    ['pose', 'montage'], ['plotze', 'karpfen']],

  ['bbg-137', 'fanggeraete_und_deren_gebrauch',
    ['Was ist eine Posenmontage?',
     'What is a float rig?',
     'O que é uma montagem com boia?'],
    [['Eine Angelmontage mit Schwimmer, bei der der Köder in einer bestimmten Tiefe angeboten wird', 'A fishing rig with a float in which the bait is presented at a certain depth', 'Uma montagem de pesca com boia, na qual a isca é apresentada em certa profundidade'],
     ['Eine Montage ohne Schnur', 'A rig without line', 'Uma montagem sem linha'],
     ['Eine Montage ausschließlich für das Meeresangeln', 'A rig exclusively for sea fishing', 'Uma montagem exclusivamente para pesca no mar']],
    0,
    ['Bei der Posenmontage trägt ein Schwimmer die Schnur, sodass der Köder in der eingestellten Tiefe schwebt. Sie eignet sich besonders für Friedfische.',
     'In a float rig a float supports the line so that the bait hovers at the set depth. It is especially suitable for coarse fish.',
     'Na montagem com boia, uma boia sustenta a linha para que a isca flutue na profundidade ajustada. É especialmente adequada para peixes não predadores.'],
    ['pose', 'montage'], ['plotze', 'karpfen', 'rotfeder']],

  ['bbg-138', 'fanggeraete_und_deren_gebrauch',
    ['Welche Funktion hat ein Blei (Senkblei) an der Montage?',
     'What function does a sinker (lead weight) have on the rig?',
     'Qual é a função de uma chumbada na montagem?'],
    [['Es beschwert die Montage und bringt den Köder in die gewünschte Tiefe', 'It weights the rig and takes the bait to the desired depth', 'Ela dá peso à montagem e leva a isca à profundidade desejada'],
     ['Es macht die Schnur sichtbar', 'It makes the line visible', 'Ela torna a linha visível'],
     ['Es dient als Köder', 'It serves as bait', 'Ela serve de isca']],
    0,
    ['Bleie beschweren die Montage, sodass der Köder absinkt oder am Grund liegt. Die Bleigröße wird an Strömung, Wind und Zielfisch angepasst.',
     'Sinkers weight the rig so that the bait sinks or lies on the bottom. The sinker size is adapted to current, wind and target fish.',
     'As chumbadas dão peso à montagem para que a isca afunde ou fique no fundo. O tamanho é ajustado à correnteza, ao vento e ao peixe alvo.'],
    ['blei', 'montage'], ['karpfen', 'barsch']],

  ['bbg-139', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter einer Grundmontage?',
     'What is meant by a bottom rig?',
     'O que se entende por montagem de fundo?'],
    [['Eine Montage, bei der der Köder am Gewässergrund liegt', 'A rig in which the bait lies on the bottom of the water', 'Uma montagem em que a isca fica no fundo da água'],
     ['Eine Montage ohne Haken', 'A rig without a hook', 'Uma montagem sem anzol'],
     ['Eine Montage an der Wasseroberfläche', 'A rig at the water surface', 'Uma montagem na superfície da água']],
    0,
    ['Bei der Grundmontage wird der Köder mit einem Blei am Grund gehalten. Sie eignet sich für Friedfische wie Karpfen und für Raubfische mit Köderfisch.',
     'In a bottom rig the bait is held on the bottom with a sinker. It suits coarse fish such as carp and predatory fish with bait fish.',
     'Na montagem de fundo, a isca é mantida no fundo com uma chumbada. Serve para não predadores como a carpa e para predadores com peixe-isca.'],
    ['montage', 'grundangeln'], ['karpfen', 'wels', 'hecht']],

  ['bbg-140', 'fanggeraete_und_deren_gebrauch',
    ['Welche Funktion hat ein Wirbel (Drehwirbel) am Vorfach?',
     'What function does a swivel have on the leader?',
     'Qual é a função de um girador (swivel) no líder?'],
    [['Er verhindert das Verdrehen der Schnur', 'It prevents the line from twisting', 'Ele evita o torcimento da linha'],
     ['Er vergrößert den Köder', 'It enlarges the bait', 'Ele aumenta a isca'],
     ['Er dient als Bissanzeiger', 'It serves as a bite indicator', 'Ele serve de indicador de mordida']],
    0,
    ['Der Wirbel verbindet zwei Schnurabschnitte drehbar miteinander. So wird die Verdrillung der Schnur durch sich drehende Köder verhindert.',
     'The swivel connects two line sections rotatably. This prevents the line from twisting caused by rotating lures.',
     'O girador conecta dois trechos de linha de forma giratória. Assim, evita-se o torcimento da linha causado por iscas que giram.'],
    ['montage', 'geraete'], ['hecht', 'barsch', 'zander']],

  ['bbg-141', 'fanggeraete_und_deren_gebrauch',
    ['Was versteht man unter einem Anschlag beim Angeln?',
     'What is meant by striking when fishing?',
     'O que se entende por fisgada (anzolada) na pesca?'],
    [['Das schnelle Einhaken des Fisches durch eine ruckartige Rutenbewegung', 'Quickly hooking the fish with a sharp rod movement', 'A fisgada rápida do peixe com um movimento brusco da vara'],
     ['Das Einholen der Schnur', 'Reeling in the line', 'O recolhimento da linha'],
     ['Das Auswerfen des Köders', 'Casting the bait', 'O lançamento da isca']],
    0,
    ['Beim Anschlag wird die Rute ruckartig angehoben, damit der Haken im Fischmaul sitzt. Er muss dem Köder und der Größe des Zielfisches angepasst sein.',
     'When striking, the rod is raised sharply so that the hook sits in the fish\u2019s mouth. It must be adapted to the bait and the size of the target fish.',
     'Na fisgada, a vara é levantada bruscamente para que o anzol se fixe na boca do peixe. Ela deve ser adequada à isca e ao tamanho do peixe alvo.'],
    ['technik'], ['barsch', 'plotze']],

  ['bbg-142', 'fanggeraete_und_deren_gebrauch',
    ['Was passiert bei einem zu starken Anschlag?',
     'What happens with too strong a strike?',
     'O que acontece com uma fisgada forte demais?'],
    [['Die Schnur kann reißen oder der Haken im Fischmaul ausreißen', 'The line can break or the hook can tear out of the fish\u2019s mouth', 'A linha pode arrebentar ou o anzol pode rasgar a boca do peixe'],
     ['Der Fisch wird immer größer', 'The fish always becomes larger', 'O peixe sempre fica maior'],
     ['Der Köder wird fester', 'The bait becomes firmer', 'A isca fica mais firme']],
    0,
    ['Ein zu heftiger Anschlag belastet Schnur und Haken stark. Besonders bei dünnen Schnüren droht ein Schnurriss, bei weichem Maul das Ausreißen des Hakens.',
     'Too violent a strike puts heavy strain on line and hook. Especially with thin lines there is a risk of breakage, and with soft mouths the hook tears out.',
     'Uma fisgada muito forte sobrecarrega linha e anzol. Especialmente com linhas finas há risco de arrebentamento e, em bocas moles, o anzol rasga.'],
    ['technik'], ['plotze', 'barsch']],

  ['bbg-143', 'fanggeraete_und_deren_gebrauch',
    ['Welche Rolle spielt die Schnurdehnung bei der Bisserkennung?',
     'What role does line stretch play in bite detection?',
     'Qual é o papel da elasticidade da linha na detecção de mordidas?'],
    [['Eine wenig dehnbare Schnur überträgt Bisse direkter', 'A line with little stretch transmits bites more directly', 'Uma linha pouco elástica transmite as mordidas de forma mais direta'],
     ['Eine stark dehnbare Schnur zeigt immer mehr Bisse', 'A highly stretchy line always shows more bites', 'Uma linha muito elástica sempre mostra mais mordidas'],
     ['Die Dehnung hat keinen Einfluss', 'The stretch has no influence', 'A elasticidade não tem influência']],
    0,
    ['Wenig dehnbare Schnüre wie Geflecht übertragen Bisse fast verzögerungsfrei. Dehnbare Monofilschnüre dämpfen dagegen die Übertragung, was die Bisserkennung erschwert.',
     'Lines with little stretch such as braid transmit bites almost without delay. Stretchy monofilament lines, on the other hand, dampen the transmission, which makes bite detection harder.',
     'Linhas pouco elásticas, como as trançadas, transmitem as mordidas quase sem atraso. Linhas elásticas de monofilamento, ao contrário, amortizam a transmissão, dificultando a detecção.'],
    ['schnur', 'technik'], ['zander', 'hecht']],

  ['bbg-144', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Bissanzeiger?',
     'What is a bite indicator?',
     'O que é um indicador de mordida?'],
    [['Ein Gerät oder eine Vorrichtung, die einen Biss sichtbar oder hörbar macht', 'A device or arrangement that makes a bite visible or audible', 'Um aparelho ou dispositivo que torna uma mordida visível ou audível'],
     ['Ein Köder für große Fische', 'A bait for large fish', 'Uma isca para peixes grandes'],
     ['Ein Werkzeug zum Hakenlösen', 'A tool for removing hooks', 'Uma ferramenta para remover anzóis']],
    0,
    ['Bissanzeiger wie Posen, Quiver-Tips, elektronische Bissanzeiger oder Glöckchen melden, dass ein Fisch den Köder genommen hat.',
     'Bite indicators such as floats, quiver tips, electronic bite alarms or bells report that a fish has taken the bait.',
     'Indicadores de mordida como boias, ponteiras quiver, alarmes eletrônicos ou sininhos avisam que um peixe pegou a isca.'],
    ['technik', 'geraete'], ['karpfen', 'wels']],

  ['bbg-145', 'fanggeraete_und_deren_gebrauch',
    ['Was ist ein Quiver-Tip?',
     'What is a quiver tip?',
     'O que é uma ponteira quiver?'],
    [['Eine weiche, austauschbare Ruten spitze als empfindlicher Bissanzeiger', 'A soft, interchangeable rod tip serving as a sensitive bite indicator', 'Uma ponteira de vara macia e intercambiável que serve de indicador sensível de mordida'],
     ['Ein schweres Blei für die Grundmontage', 'A heavy sinker for the bottom rig', 'Uma chumbada pesada para a montagem de fundo'],
     ['Ein Haken mit Widerhaken', 'A hook with a barb', 'Um anzol com farpa']],
    0,
    ['Der Quiver-Tip ist eine sehr weiche Ruten spitze, die bei jedem Biss zittert. Er wird besonders beim Grundangeln auf Friedfische eingesetzt.',
     'The quiver tip is a very soft rod tip that trembles at every bite. It is especially used when bottom fishing for coarse fish.',
     'A ponteira quiver é uma ponta de vara muito macia que treme a cada mordida. É usada especialmente na pesca de fundo para peixes não predadores.'],
    ['technik', 'geraete'], ['karpfen', 'plotze']],
]
