// Category: behandlung_der_gefangenen_fische — Handling of caught fish (1/2)
export const questions = [
  // --- killing / stunning ---
  ['bbg-181', 'behandlung_der_gefangenen_fische',
    ['Wie wird ein gefangener Fisch tierschutzgerecht getötet?',
     'How is a caught fish killed in an animal-welfare-compliant way?',
     'Como um peixe capturado é abatido de forma respeitosa com os animais?'],
    [['Durch Betäubung mit einem kräftigen Schlag auf den Kopf und anschließendes Ausbluten', 'By stunning with a firm blow to the head and subsequent bleeding out', 'Atordoando com um golpe firme na cabeça e em seguida sangrando o peixe'],
     ['Durch langes Liegenlassen an der Luft', 'By leaving it on the land for a long time', 'Deixando-o por muito tempo fora da água'],
     ['Durch langsames Ersticken im Netz', 'By slow suffocation in the net', 'Pela asfixia lenta na rede']],
    0,
    ['Tierschutzgerecht ist die Betäubung mit einem kräftigen, gezielten Schlag auf den Schädel und das sofortige Ausbluten durch Trennen der Kiemengefäße. So leidet der Fisch nicht unnötig.',
     'Animal-friendly killing is stunning with a firm, targeted blow to the skull and immediate bleeding out by cutting the gill vessels. This way the fish does not suffer unnecessarily.',
     'O abate respeitoso é atordoar com um golpe firme e direcionado no crânio e sangrar imediatamente o peixe, cortando os vasos das brânquias. Assim o peixe não sofre desnecessariamente.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-182', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter der Betäubung eines Fisches?',
     'What is meant by stunning a fish?',
     'O que se entende por atordoamento de um peixe?'],
    [['Das schlagartige Herbeiführen von Bewusstlosigkeit vor dem Töten', 'Abruptly rendering the fish unconscious before killing it', 'Provocar subitamente a inconsciência antes de matar'],
     ['Das Füttern des Fisches', 'Feeding the fish', 'Alimentar o peixe'],
     ['Das Messen des Fisches', 'Measuring the fish', 'Medir o peixe']],
    0,
    ['Betäubung bedeutet, den Fisch schlagartig bewusstlos zu machen, damit er beim Töten keine Schmerzen empfindet. Sie erfolgt unmittelbar vor dem Ausbluten.',
     'Stunning means rendering the fish abruptly unconscious so that it feels no pain when killed. It happens immediately before bleeding out.',
     'Atordoar significa deixar o peixe subitamente inconsciente para que não sinta dor ao ser abatido. Isso ocorre imediatamente antes de sangrar.'],
    ['toeten', 'tierschutz'], ['karpfen', 'hecht']],

  ['bbg-183', 'behandlung_der_gefangenen_fische',
    ['Wohin muss der Betäubungsschlag beim Fisch treffen?',
     'Where must the stunning blow hit the fish?',
     'Onde deve atingir o golpe de atordoamento no peixe?'],
    [['Auf den Schädel, direkt hinter den Augen', 'On the skull, directly behind the eyes', 'No crânio, diretamente atrás dos olhos'],
     ['Auf den Schwanz', 'On the tail', 'Na cauda'],
     ['Auf die Bauchflosse', 'On the pelvic fin', 'Na nadadeira pélvica']],
    0,
    ['Der Schlag muss gezielt auf den Schädel hinter den Augen treffen, um das Gehirn zu treffen und sofortige Bewusstlosigkeit zu erreichen.',
     'The blow must hit the skull behind the eyes in a targeted way to reach the brain and cause immediate unconsciousness.',
     'O golpe deve atingir de forma direcionada o crânio atrás dos olhos para alcançar o cérebro e causar inconsciência imediata.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen', 'zander']],

  ['bbg-184', 'behandlung_der_gefangenen_fische',
    ['Warum ist das Ausbluten nach der Betäubung wichtig?',
     'Why is bleeding out after stunning important?',
     'Por que é importante sangrar o peixe após o atordoamento?'],
    [['Es führt schnell zum Tod und verbessert die Fleischqualität', 'It leads to death quickly and improves the meat quality', 'Ele leva rapidamente à morte e melhora a qualidade da carne'],
     ['Es macht den Fisch schwerer', 'It makes the fish heavier', 'Ele deixa o peixe mais pesado'],
     ['Es erhält die Schuppen', 'It preserves the scales', 'Ele preserva as escamas']],
    0,
    ['Beim Ausbluten werden die Kiemengefäße durchtrennt, der Fisch verblutet schnell und das Fleisch bleibt hell und gut haltbar.',
     'When bleeding out, the gill vessels are cut, the fish bleeds out quickly and the meat stays light and keeps well.',
     'Ao sangrar, os vasos das brânquias são cortados, o peixe sangra rapidamente e a carne permanece clara e bem conservada.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-185', 'behandlung_der_gefangenen_fische',
    ['Wie blutet man einen Fisch richtig aus?',
     'How does one properly bleed out a fish?',
     'Como se sangra corretamente um peixe?'],
    [['Durch das Durchtrennen der Kiemenbögen oder der Kiemengefäße', 'By cutting the gill arches or the gill vessels', 'Cortando os arcos ou os vasos das brânquias'],
     ['Durch das Einschneiden des Schwanzes', 'By cutting the tail', 'Cortando a cauda'],
     ['Durch das Ausnehmen des Bauches', 'By gutting the belly', 'Eviscerando a barriga']],
    0,
    ['Zum Ausbluten werden die Kiemen mit einem scharfen Messer durchtrennt. Das Blut fließt ab und der Fisch stirbt schnell.',
     'To bleed the fish, the gills are cut with a sharp knife. The blood drains and the fish dies quickly.',
     'Para sangrar, as brânquias são cortadas com uma faca afiada. O sangue escoa e o peixe morre rapidamente.'],
    ['toeten', 'tierschutz'], ['hecht', 'zander']],

  ['bbg-186', 'behandlung_der_gefangenen_fische',
    ['Darf man einen gefangenen Fisch lebend an Land liegen lassen?',
     'May one leave a caught fish alive on the land?',
     'Pode-se deixar um peixe capturado vivo em terra?'],
    [['Nein, das wäre tierschutzwidrig', 'No, that would violate animal welfare', 'Não, isso violaria o bem-estar animal'],
     ['Ja, das ist üblich', 'Yes, that is common', 'Sim, isso é comum'],
     ['Ja, aber nur im Winter', 'Yes, but only in winter', 'Sim, mas somente no inverno']],
    0,
    ['Fische, die nicht zurückgesetzt werden, müssen unmittelbar nach dem Fang getötet werden. Langes Liegenlassen in der Luft führt zu unnötigem Leiden.',
     'Fish that are not released must be killed immediately after being caught. Leaving them on the land for a long time causes unnecessary suffering.',
     'Peixes que não serão soltos devem ser abatidos imediatamente após a captura. Deixá-los por muito tempo em terra causa sofrimento desnecessário.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-187', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter \u201eschonender Behandlung\u201c eines Fisches?',
     'What is meant by \u201cgentle handling\u201c of a fish?',
     'O que se entende por \u201cmanuseio cuidadoso\u201d de um peixe?'],
    [['Stress zu vermeiden und die schützende Schleimschicht zu erhalten', 'Avoiding stress and preserving the protective slime layer', 'Evitar estresse e preservar a camada protetora de muco'],
     ['Den Fisch möglichst lange aus dem Wasser zu nehmen', 'Keeping the fish out of the water as long as possible', 'Manter o peixe fora da água o máximo possível'],
     ['Den Fisch kräftig zu drücken', 'Pressing the fish firmly', 'Apertar o peixe com força']],
    0,
    ['Schonende Behandlung bedeutet, den Fisch im Wasser zu lassen, feuchte Hände zu verwenden und ihn nicht zu quetschen. So bleibt die Schleimschicht intakt.',
     'Gentle handling means keeping the fish in the water, using wet hands and not squeezing it. This keeps the slime layer intact.',
     'Manuseio cuidadoso significa manter o peixe na água, usar mãos molhadas e não apertá-lo. Assim a camada de muco permanece intacta.'],
    ['tierschutz', 'handling'], ['hecht', 'karpfen', 'zander']],

  ['bbg-188', 'behandlung_der_gefangenen_fische',
    ['Warum sollte man einen gefangenen Fisch nicht längere Zeit im Kescher lassen?',
     'Why should a caught fish not be left in the landing net for a long time?',
     'Por que um peixe capturado não deve ficar muito tempo na rede de aterrissagem?'],
    [['Weil er Stress und Sauerstoffmangel erleidet und sich verletzen kann', 'Because it suffers stress and oxygen deficiency and can injure itself', 'Porque ele sofre estresse e falta de oxigênio e pode se machucar'],
     ['Weil er dann schwerer wird', 'Because it then becomes heavier', 'Porque então ele fica mais pesado'],
     ['Weil er dann schneller wächst', 'Because it then grows faster', 'Porque então ele cresce mais rápido']],
    0,
    ['Im Kescher eingeengt, bekommt der Fisch wenig Sauerstoff und verletzt sich an den Maschen. Er sollte schnell entnommen und behandelt werden.',
     'Cramped in the net, the fish gets little oxygen and injures itself on the mesh. It should be taken out and handled quickly.',
     'Apertado na rede, o peixe recebe pouco oxigênio e se machuca na malha. Deve ser retirado e manuseado rapidamente.'],
    ['tierschutz', 'handling'], ['hecht', 'karpfen']],

  ['bbg-189', 'behandlung_der_gefangenen_fische',
    ['Was ist ein Tötungsschlag?',
     'What is a killing blow (priest strike)?',
     'O que é um golpe de abate?'],
    [['Ein kräftiger Schlag auf den Kopf, der den Fisch betäubt und ihm das Leben nimmt', 'A firm blow to the head that stuns the fish and takes its life', 'Um golpe firme na cabeça que atordoa o peixe e tira sua vida'],
     ['Ein Schlag auf den Schwanz', 'A blow to the tail', 'Um golpe na cauda'],
     ['Ein Schlag auf die Flossen', 'A blow to the fins', 'Um golpe nas nadadeiras']],
    0,
    ['Der Tötungsschlag trifft gezielt den Schädel des Fisches und führt zur Bewusstlosigkeit. Anschließend wird der Fisch durch Ausbluten getötet.',
     'The killing blow targets the skull of the fish and causes unconsciousness. The fish is then killed by bleeding out.',
     'O golpe de abate atinge de forma direcionada o crânio do peixe e causa inconsciência. Em seguida, o peixe é abatido pelo sangramento.'],
    ['toeten', 'tierschutz'], ['hecht', 'zander']],

  ['bbg-190', 'behandlung_der_gefangenen_fische',
    ['Welche Ausrüstung eignet sich zum Betäuben von Fischen?',
     'Which equipment is suitable for stunning fish?',
     'Qual equipamento é adequado para atordoar peixes?'],
    [['Ein Betäubungsstock (Tötungsstock) oder ein geeigneter fester Gegenstand', 'A priest (fish baton) or a suitable firm object', 'Um bastão de atordoamento ou um objeto firme adequado'],
     ['Ein Schwamm', 'A sponge', 'Uma esponja'],
     ['Ein Bleistift', 'A pencil', 'Um lápis']],
    0,
    ['Ein Betäubungsstock ist ein speziell geformtes, festes Werkzeug, mit dem ein gezielter Schlag auf den Schädel des Fisches ausgeführt wird.',
     'A priest is a specially shaped, firm tool with which a targeted blow to the skull of the fish is carried out.',
     'O bastão de atordoamento é uma ferramenta firme e de formato especial, com a qual se executa um golpe direcionado no crânio do peixe.'],
    ['toeten', 'geraete'], ['hecht', 'karpfen', 'zander']],

  ['bbg-191', 'behandlung_der_gefangenen_fische',
    ['Warum muss die Betäubung unmittelbar vor dem Töten erfolgen?',
     'Why must stunning take place immediately before killing?',
     'Por que o atordoamento deve ocorrer imediatamente antes de matar?'],
    [['Damit der Fisch keinen unnötigen Schmerz erleidet', 'So that the fish does not suffer unnecessary pain', 'Para que o peixe não sinta dor desnecessária'],
     ['Damit das Fleisch besser schmeckt', 'So that the meat tastes better', 'Para que a carne fique com melhor sabor'],
     ['Weil es gesetzlich vorgeschrieben ist, eine Stunde zu warten', 'Because the law requires waiting for an hour', 'Porque a lei exige esperar uma hora']],
    0,
    ['Tierschutzgerecht ist die Betäubung erst unmittelbar vor dem Töten. Eine frühere Betäubung ließe den Fisch sonst wieder aufwachen und unnötig leiden.',
     'Animal-friendly practice is stunning only immediately before killing. Otherwise the fish would wake up again and suffer unnecessarily.',
     'A prática respeitosa é atordoar apenas imediatamente antes de matar. Caso contrário, o peixe acordaria de novo e sofreria desnecessariamente.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  // --- storage / transport ---
  ['bbg-192', 'behandlung_der_gefangenen_fische',
    ['Wie transportiert man gefangene Fische richtig?',
     'How does one transport caught fish correctly?',
     'Como se transporta corretamente os peixes capturados?'],
    [['Kühl und feucht gehalten, zum Beispiel in einer Kühltasche mit feuchten Tüchern', 'Kept cool and moist, for example in a cool box with wet cloths', 'Mantidos frios e úmidos, por exemplo em uma bolsa térmica com panos molhados'],
     ['In der prallen Sonne auf dem Autodach', 'In full sun on the car roof', 'Sob sol forte no teto do carro'],
     ['Ungekühlt im Kofferraum über mehrere Stunden', 'Uncooled in the boot for several hours', 'Sem refrigeração no porta-malas por várias horas']],
    0,
    ['Gefangene Fische müssen schnell gekühlt und feucht gehalten werden. So bleibt die Qualität erhalten und der Verderb wird verlangsamt.',
     'Caught fish must be cooled quickly and kept moist. This preserves the quality and slows down spoilage.',
     'Os peixes capturados devem ser resfriados rapidamente e mantidos úmidos. Assim a qualidade é preservada e a deterioração é retardada.'],
    ['transport', 'lagerung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-193', 'behandlung_der_gefangenen_fische',
    ['Warum sollte man Fische nicht in der prallen Sonne liegen lassen?',
     'Why should fish not be left in full sun?',
     'Por que os peixes não devem ficar sob sol forte?'],
    [['Weil sie schnell verderben und die Qualität leidet', 'Because they spoil quickly and the quality suffers', 'Porque eles se deterioram rapidamente e a qualidade sofre'],
     ['Weil sie dann lebendig werden', 'Because they then come alive again', 'Porque então eles voltam à vida'],
     ['Weil sie dann leichter werden', 'Because they then become lighter', 'Porque então eles ficam mais leves']],
    0,
    ['Wärme beschleunigt den Verderb von Fischfleisch. Gefangene Fische gehören daher schnell an einen kühlen, schattigen Ort.',
     'Heat accelerates the spoilage of fish meat. Caught fish therefore belong quickly in a cool, shady place.',
     'O calor acelera a deterioração da carne de peixe. Os peixes capturados, portanto, devem ir rapidamente para um local fresco e sombreado.'],
    ['transport', 'lagerung'], ['hecht', 'karpfen']],

  ['bbg-194', 'behandlung_der_gefangenen_fische',
    ['Was ist bei der Lagerung von Fischen im Kühlschrank zu beachten?',
     'What should be observed when storing fish in the refrigerator?',
     'O que se deve observar ao guardar peixes na geladeira?'],
    [['Sie sollten abgedeckt und bei niedriger Temperatur gelagert werden', 'They should be stored covered and at a low temperature', 'Eles devem ser guardados cobertos e em temperatura baixa'],
     ['Sie sollten offen bei Zimmertemperatur liegen', 'They should lie open at room temperature', 'Eles devem ficar abertos em temperatura ambiente'],
     ['Sie sollten in der Tür des Kühlschranks stehen', 'They should stand in the refrigerator door', 'Eles devem ficar na porta da geladeira']],
    0,
    ['Fisch wird bei niedriger Kühlschranktemperatur und abgedeckt gelagert, damit er nicht austrocknet und sich kein Fremdgeruch überträgt.',
     'Fish is stored at a low refrigerator temperature and covered so that it does not dry out and no foreign odours are transferred.',
     'O peixe é guardado em temperatura baixa da geladeira e coberto, para não ressecar e não absorver odores.'],
    ['lagerung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-195', 'behandlung_der_gefangenen_fische',
    ['Wie lange ist ein frisch gefangener, gekühlter Fisch in der Regel haltbar?',
     'How long does a freshly caught, chilled fish usually keep?',
     'Por quanto tempo um peixe recém-capturado e refrigerado geralmente dura?'],
    [['Ein bis zwei Tage bei durchgehender Kühlung', 'One to two days with continuous cooling', 'Um a dois dias com refrigeração contínua'],
     ['Zwei Wochen bei Zimmertemperatur', 'Two weeks at room temperature', 'Duas semanas em temperatura ambiente'],
     ['Einen Monat ungekühlt', 'One month uncooled', 'Um mês sem refrigeração']],
    0,
    ['Frischer Fisch ist bei durchgehender Kühlung etwa ein bis zwei Tage haltbar. Danach nimmt die Qualität deutlich ab und es besteht Verderbgefahr.',
     'Fresh fish keeps for about one to two days with continuous cooling. Afterwards the quality drops noticeably and there is a risk of spoilage.',
     'O peixe fresco dura cerca de um a dois dias com refrigeração contínua. Depois, a qualidade cai visivelmente e há risco de deterioração.'],
    ['lagerung'], ['hecht', 'zander']],

  ['bbg-196', 'behandlung_der_gefangenen_fische',
    ['Woran erkennt man einen frischen Fisch?',
     'How does one recognise a fresh fish?',
     'Como se reconhece um peixe fresco?'],
    [['An klaren Augen, roten Kiemen und festem Fleisch', 'By clear eyes, red gills and firm flesh', 'Por olhos claros, brânquias vermelhas e carne firme'],
     ['An trüben Augen und grauen Kiemen', 'By cloudy eyes and grey gills', 'Por olhos turvos e brânquias cinzentas'],
     ['An einem starken, stechenden Geruch', 'By a strong, pungent smell', 'Por um odor forte e pungente']],
    0,
    ['Frische Fische haben klare, glänzende Augen, leuchtend rote Kiemen und festes, elastisches Fleisch. Trübe Augen und starker Geruch deuten auf Verderb hin.',
     'Fresh fish have clear, shiny eyes, bright red gills and firm, elastic flesh. Cloudy eyes and a strong smell indicate spoilage.',
     'Peixes frescos têm olhos claros e brilhantes, brânquias vermelho-vivas e carne firme e elástica. Olhos turvos e cheiro forte indicam deterioração.'],
    ['lagerung', 'qualitaet'], ['hecht', 'karpfen']],

  ['bbg-197', 'behandlung_der_gefangenen_fische',
    ['Wie kühlt man Fische nach dem Fang am schnellsten?',
     'How does one cool fish fastest after catching?',
     'Como se resfria os peixes mais rápido após a captura?'],
    [['Indem man sie in Eiswasser oder auf Eis legt', 'By putting them in ice water or on ice', 'Colocando-os em água com gelo ou sobre gelo'],
     ['Indem man sie in die Sonne legt', 'By putting them in the sun', 'Colocando-os no sol'],
     ['Indem man sie in ein warmes Tuch wickelt', 'By wrapping them in a warm cloth', 'Envolvendo-os em um pano quente']],
    0,
    ['Eis und Eiswasser entziehen dem Fisch schnell Wärme. Schnelle Kühlung verlangsamt den Verderb und erhält die Fleischqualität.',
     'Ice and ice water quickly remove heat from the fish. Fast cooling slows spoilage and preserves the meat quality.',
     'O gelo e a água com gelo retiram rapidamente o calor do peixe. O resfriamento rápido retarda a deterioração e preserva a qualidade da carne.'],
    ['transport', 'lagerung'], ['hecht', 'karpfen', 'zander']],

  ['bbg-198', 'behandlung_der_gefangenen_fische',
    ['Warum ist eine schnelle Kühlung der Fische wichtig?',
     'Why is quick cooling of the fish important?',
     'Por que o resfriamento rápido dos peixes é importante?'],
    [['Weil sie den Verderb verlangsamt und die Qualität erhält', 'Because it slows spoilage and preserves quality', 'Porque retarda a deterioração e preserva a qualidade'],
     ['Weil sie die Fische größer macht', 'Because it makes the fish larger', 'Porque deixa os peixes maiores'],
     ['Weil sie die Schuppen entfernt', 'Because it removes the scales', 'Porque remove as escamas']],
    0,
    ['Kälte verlangsamt die Aktivität von Bakterien und Enzymen im Fischgewebe. Schnelles Kühlen erhält daher Frische und Haltbarkeit.',
     'Cold slows the activity of bacteria and enzymes in the fish tissue. Quick cooling therefore preserves freshness and shelf life.',
     'O frio retarda a atividade de bactérias e enzimas no tecido do peixe. O resfriamento rápido, portanto, preserva o frescor e a validade.'],
    ['transport', 'lagerung'], ['hecht', 'karpfen']],

  ['bbg-199', 'behandlung_der_gefangenen_fische',
    ['Wie viele Fische sollte man für den Eigenbedarf entnehmen?',
     'How many fish should one take for one\u2019s own use?',
     'Quantos peixes se deve levar para consumo próprio?'],
    [['Nur so viele, wie gesetzlich erlaubt sind und tatsächlich verwendet werden', 'Only as many as are legally permitted and actually used', 'Somente os permitidos por lei e que serão realmente usados'],
     ['So viele wie möglich, um den Bestand zu verringern', 'As many as possible to reduce the stock', 'O máximo possível, para reduzir o estoque'],
     ['Immer den gesamten Fang', 'Always the entire catch', 'Sempre toda a captura']],
    0,
    ['Angler sollten nur so viele Fische entnehmen, wie sie verwerten und wie es die Regeln erlauben. Überschüssige Fische werden schonend zurückgesetzt.',
     'Anglers should only take as many fish as they can use and as the rules allow. Excess fish are released gently.',
     'Os pescadores devem levar apenas os peixes que conseguirem aproveitar e que as regras permitam. Peixes excedentes são soltos com cuidado.'],
    ['entnahme', 'verantwortung'], ['hecht', 'karpfen']],

  ['bbg-200', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter einer Entnahmebegrenzung?',
     'What is meant by a catch limit (take limit)?',
     'O que se entende por limite de captura (cota)?'],
    [['Eine Regel, die die Höchstmenge an entnehmbaren Fischen festlegt', 'A rule that sets the maximum amount of fish that may be taken', 'Uma regra que define a quantidade máxima de peixes que podem ser levados'],
     ['Eine Regel, die das Angeln ganz verbietet', 'A rule that completely prohibits fishing', 'Uma regra que proíbe totalmente a pesca'],
     ['Eine Regel, die den Köder begrenzt', 'A rule that limits the bait', 'Uma regra que limita a isca']],
    0,
    ['Entnahmebegrenzungen schützen die Bestände vor Überfischung. Sie sind in der Angelkarte, in Vereinsregeln oder in Verordnungen festgelegt.',
     'Take limits protect the stocks from overfishing. They are set out in the fishing permit, in club rules or in regulations.',
     'Os limites de captura protegem os estoques da sobrepesca. Eles constam na permissão de pesca, nas regras dos clubes ou em regulamentos.'],
    ['entnahme', 'recht'], ['hecht', 'zander']],

  ['bbg-201', 'behandlung_der_gefangenen_fische',
    ['Was macht man mit Fischen, die man nicht behalten will?',
     'What does one do with fish one does not want to keep?',
     'O que se faz com os peixes que não se quer guardar?'],
    [['Man setzt sie sofort und schonend zurück', 'One releases them immediately and gently', 'Solta-se imediatamente e com cuidado'],
     ['Man lässt sie am Ufer liegen', 'One leaves them on the bank', 'Deixa-se na margem'],
     ['Man wirft sie ins Gebüsch', 'One throws them into the bushes', 'Joga-se no mato']],
    0,
    ['Fische, die nicht entnommen werden, gehören sofort schonend zurück ins Wasser. Zurückgesetzte Fische dürfen nicht unnötig leiden.',
     'Fish that are not taken belong back in the water immediately and gently. Released fish must not suffer unnecessarily.',
     'Peixes que não serão levados devem voltar imediatamente e com cuidado à água. Peixes soltos não podem sofrer desnecessariamente.'],
    ['fangen-und-freilassen', 'tierschutz'], ['hecht', 'karpfen', 'zander']],

  ['bbg-202', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter \u201cFangen und Freilassen\u201c (catch and release)?',
     'What is meant by catch and release?',
     'O que se entende por captura e soltura?'],
    [['Gefangene Fische schonend zurückzusetzen statt sie zu entnehmen', 'Gently releasing caught fish instead of taking them', 'Soltar com cuidado os peixes capturados em vez de levá-los'],
     ['Fische nur zu fangen, um sie zu verkaufen', 'Only catching fish to sell them', 'Capturar peixes apenas para vendê-los'],
     ['Fische mit Netzen zu fangen', 'Catching fish with nets', 'Capturar peixes com redes']],
    0,
    ['Catch and release bedeutet, gefangene Fische nach dem Hakenlösen schonend wieder freizulassen. Voraussetzung sind widerhakenlose Haken oder sorgfältiges Lösen und feuchte Hände.',
     'Catch and release means gently releasing caught fish again after unhooking. Prerequisites are barbless hooks or careful unhooking and wet hands.',
     'Captura e soltura significa soltar com cuidado os peixes capturados após remover o anzol. Pré-requisitos são anzóis sem farpa ou remoção cuidadosa e mãos molhadas.'],
    ['fangen-und-freilassen', 'tierschutz'], ['hecht', 'zander', 'barsch']],

  ['bbg-203', 'behandlung_der_gefangenen_fische',
    ['Wann sollte man Fische zurück- statt mitnehmen?',
     'When should one release fish instead of taking them?',
     'Quando se deve soltar os peixes em vez de levá-los?'],
    [['Bei untermaßigen oder geschonten Fischen und wenn man sie nicht verwerten will', 'With undersized or protected fish and when one does not want to use them', 'Com peixes abaixo do tamanho mínimo, protegidos, ou quando não se quer aproveitá-los'],
     ['Niemals, jeder Fisch wird mitgenommen', 'Never, every fish is taken', 'Nunca, todo peixe é levado'],
     ['Nur kranke Fische', 'Only sick fish', 'Somente peixes doentes']],
    0,
    ['Untermaßige und geschonte Fische müssen sofort zurückgesetzt werden. Auch Fische, die man nicht verwerten will, sollten schonend freigelassen werden.',
     'Undersized and protected fish must be released immediately. Fish that one does not want to use should also be released gently.',
     'Peixes abaixo do tamanho mínimo e protegidos devem ser soltos imediatamente. Peixes que não serão aproveitados também devem ser soltos com cuidado.'],
    ['fangen-und-freilassen', 'recht'], ['hecht', 'karpfen']],

  ['bbg-204', 'behandlung_der_gefangenen_fische',
    ['Wie setzt man einen Fisch richtig zurück?',
     'How does one release a fish correctly?',
     'Como se solta corretamente um peixe?'],
    [['Ihn im Wasser vorsichtig halten, bis er von selbst davonschwimmt', 'Holding it carefully in the water until it swims away on its own', 'Segurá-lo com cuidado na água até que nade sozinho'],
     ['Ihn aus großer Höhe ins Wasser werfen', 'Throwing it into the water from a great height', 'Jogá-lo na água de grande altura'],
     ['Ihn am Schwanz auf das Ufer legen', 'Placing it on the bank by the tail', 'Colocá-lo na margem pela cauda']],
    0,
    ['Zum Zurücksetzen wird der Fisch im Wasser an Schwanz und Brustflosse gehalten und leicht hin und her bewegt, bis er selbstständig wegschwimmt.',
     'To release, the fish is held in the water by the tail and pectoral fin and gently moved back and forth until it swims away on its own.',
     'Para soltar, o peixe é segurado na água pela cauda e pela nadadeira peitoral e movido suavemente para frente e para trás até nadar sozinho.'],
    ['fangen-und-freilassen', 'tierschutz'], ['hecht', 'zander', 'barsch']],

  ['bbg-205', 'behandlung_der_gefangenen_fische',
    ['Warum darf man Fische nicht mit trockenen Händen anfassen?',
     'Why must fish not be touched with dry hands?',
     'Por que os peixes não devem ser tocados com mãos secas?'],
    [['Weil die schützende Schleimschicht beschädigt wird', 'Because the protective slime layer is damaged', 'Porque a camada protetora de muco é danificada'],
     ['Weil sie dann schneller wachsen', 'Because they then grow faster', 'Porque então eles crescem mais rápido'],
     ['Weil sie dann schwerer werden', 'Because they then become heavier', 'Porque então eles ficam mais pesados']],
    0,
    ['Trockene Hände reißen die Schleimschicht und die Schuppen auf. Der Fisch verliert so seinen Schutz gegen Krankheitserreger.',
     'Dry hands tear the slime layer and the scales. The fish thus loses its protection against pathogens.',
     'Mãos secas rasgam a camada de muco e as escamas. O peixe perde assim sua proteção contra agentes patogênicos.'],
    ['fangen-und-freilassen', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-206', 'behandlung_der_gefangenen_fische',
    ['Was ist ein Hakenlöser?',
     'What is a hook remover?',
     'O que é um removedor de anzol?'],
    [['Ein Werkzeug zum schonenden Entfernen tief sitzender Haken', 'A tool for gently removing deeply set hooks', 'Uma ferramenta para remover com cuidado anzóis profundos'],
     ['Ein Werkzeug zum Schärfen der Haken', 'A tool for sharpening hooks', 'Uma ferramenta para afiar anzóis'],
     ['Ein Behälter für Köder', 'A container for bait', 'Um recipiente para iscas']],
    0,
    ['Mit dem Hakenlöser wird ein tief geschluckter Haken ohne Ziehen und ohne Verletzung des Fisches aus dem Maul geholt.',
     'With the hook remover, a deeply swallowed hook is taken out of the mouth without pulling and without injuring the fish.',
     'Com o removedor de anzol, um anzol engolido profundamente é retirado da boca sem puxar e sem ferir o peixe.'],
    ['geraete', 'fangen-und-freilassen'], ['hecht', 'zander']],

  ['bbg-207', 'behandlung_der_gefangenen_fische',
    ['Wie löst man einen tief geschluckten Haken richtig?',
     'How does one correctly remove a deeply swallowed hook?',
     'Como se remove corretamente um anzol engolido profundamente?'],
    [['Mit einem Hakenlöser, ohne am Haken zu ziehen', 'With a hook remover, without pulling on the hook', 'Com um removedor de anzol, sem puxar o anzol'],
     ['Durch kräftiges Ziehen an der Schnur', 'By pulling hard on the line', 'Puxando com força a linha'],
     ['Durch Drücken auf den Fischbauch', 'By pressing on the fish\u2019s belly', 'Apertando a barriga do peixe']],
    0,
    ['Tief sitzende Haken werden mit dem Hakenlöser gedreht und gelöst, nicht herausgerissen. So werden innere Verletzungen vermieden.',
     'Deeply set hooks are turned and released with the hook remover, not ripped out. This avoids internal injuries.',
     'Anzóis profundos são girados e soltos com o removedor, não arrancados. Assim, lesões internas são evitadas.'],
    ['geraete', 'fangen-und-freilassen'], ['hecht', 'zander', 'barsch']],

  ['bbg-208', 'behandlung_der_gefangenen_fische',
    ['Warum ist das Hantieren an den Kiemen gefährlich?',
     'Why is handling the gills dangerous?',
     'Por que manusear as brânquias é perigoso?'],
    [['Weil die empfindlichen Kiemen verletzt werden und der Fisch verbluten kann', 'Because the sensitive gills can be injured and the fish can bleed to death', 'Porque as brânquias sensíveis podem ser feridas e o peixe pode sangrar até morrer'],
     ['Weil die Kiemen sehr hart sind', 'Because the gills are very hard', 'Porque as brânquias são muito duras'],
     ['Weil die Kiemen giftig sind', 'Because the gills are poisonous', 'Porque as brânquias são venenosas']],
    0,
    ['Die Kiemen sind stark durchblutet und empfindlich. Werden sie verletzt, blutet der Fisch stark und kann sterben. Fische dürfen daher nie an den Kiemen aufgehängt werden.',
     'The gills are highly blooded and sensitive. If injured, the fish bleeds heavily and can die. Fish must therefore never be hung by the gills.',
     'As brânquias são muito vascularizadas e sensíveis. Se feridas, o peixe sangra muito e pode morrer. Por isso, peixes nunca devem ser pendurados pelas brânquias.'],
    ['tierschutz', 'handling'], ['hecht', 'zander']],

  ['bbg-209', 'behandlung_der_gefangenen_fische',
    ['Wie hält man einen Fisch beim Hakenlösen richtig fest?',
     'How does one hold a fish correctly when removing the hook?',
     'Como se segura corretamente um peixe ao remover o anzol?'],
    [['Mit feuchten Händen an Schwanz und Brustflosse, ohne zu quetschen', 'With wet hands by the tail and pectoral fin, without squeezing', 'Com mãos molhadas pela cauda e pela nadadeira peitoral, sem apertar'],
     ['Mit trockenen Händen fest um den Bauch', 'Firmly around the belly with dry hands', 'Firmemente em volta da barriga com mãos secas'],
     ['An den Kiemen aufgehängt', 'Hung by the gills', 'Pendurado pelas brânquias']],
    0,
    ['Feuchte Hände schonen die Schleimhaut. Der Fisch wird fest, aber nicht quetschend gehalten, damit er nicht entgleitet und nicht verletzt wird.',
     'Wet hands protect the slime layer. The fish is held firmly but without squeezing so that it neither slips away nor is injured.',
     'Mãos molhadas protegem o muco. O peixe é segurado com firmeza, mas sem apertar, para não escapar nem se ferir.'],
    ['handling', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-210', 'behandlung_der_gefangenen_fische',
    ['Welche Fische sollte man wegen ihrer Zähne besonders vorsichtig behandeln?',
     'Which fish should be handled with particular care because of their teeth?',
     'Quais peixes devem ser manuseados com cuidado especial por causa dos dentes?'],
    [['Hecht, Zander und Wels', 'Pike, pikeperch and catfish', 'Lúcio, lúcio-perca e siluro'],
     ['Karpfen, Schleie und Plötze', 'Carp, tench and roach', 'Carpa, tenca e barata'],
     ['Blei, Rotfeder und Güster', 'Bream, rudd and white bream', 'Brema, rudinho e brema-branca']],
    0,
    ['Raubfische wie Hecht, Zander und Wels haben scharfe Zähne beziehungsweise Zahnleisten. Sie werden mit Maulschutz oder fest hinter dem Kiemendeckel gehalten.',
     'Predatory fish such as pike, pikeperch and catfish have sharp teeth or tooth pads. They are held with a mouth guard or firmly behind the gill cover.',
     'Predadores como lúcio, lúcio-perca e siluro têm dentes afiados ou placas dentárias. Eles são segurados com protetor de boca ou firmemente atrás do opérculo.'],
    ['handling', 'sicherheit'], ['hecht', 'zander', 'wels']],
]
