// Category: behandlung_der_gefangenen_fische — Handling of caught fish (2/2)
export const questions = [
  ['bbg-211', 'behandlung_der_gefangenen_fische',
    ['Wie kann man einen Hecht sicher am Maul halten?',
     'How can one hold a pike safely by the mouth?',
     'Como se pode segurar com segurança um lúcio pela boca?'],
    [['Fest hinter dem Kiemendeckel greifen, nicht in die Kiemen', 'Grip firmly behind the gill cover, not into the gills', 'Agarrar firmemente atrás do opérculo, não nas brânquias'],
     ['Mit den Fingern in die Augen drücken', 'Press the fingers into the eyes', 'Apertar os dedos nos olhos'],
     ['Mit bloßer Hand ins geöffnete Maul fassen', 'Reach into the open mouth with a bare hand', 'Enfiar a mão nua na boca aberta']],
    0,
    ['Beim Hecht wird fest hinter dem Kiemendeckel zugegriffen, ohne die Kiemen zu verletzen. So ist der Fisch sicher kontrolliert und der Angler vor den Zähnen geschützt.',
     'With the pike, grip firmly behind the gill cover without injuring the gills. This way the fish is safely controlled and the angler is protected from the teeth.',
     'No lúcio, agarra-se firmemente atrás do opérculo, sem ferir as brânquias. Assim o peixe fica sob controle seguro e o pescador fica protegido dos dentes.'],
    ['handling', 'sicherheit'], ['hecht']],

  ['bbg-212', 'behandlung_der_gefangenen_fische',
    ['Was ist ein Maulschutz?',
     'What is a mouth guard?',
     'O que é um protetor de boca?'],
    [['Ein Schutzelement, das das Maul von Raubfischen abdeckt', 'A protective element that covers the mouth of predatory fish', 'Um elemento protetor que cobre a boca dos peixes predadores'],
     ['Ein Köder in Form eines Fisches', 'A bait shaped like a fish', 'Uma isca em forma de peixe'],
     ['Ein Netz zum Landen von Fischen', 'A net for landing fish', 'Uma rede para aterrissar peixes']],
    0,
    ['Der Maulschutz wird um das Maul von Raubfischen wie Hecht oder Zander gelegt. Er verhindert Verletzungen beim Hakenlösen und beim Handhaben.',
     'The mouth guard is placed around the mouth of predatory fish such as pike or pikeperch. It prevents injuries when unhooking and handling.',
     'O protetor de boca é colocado ao redor da boca de predadores como lúcio ou lúcio-perca. Ele evita ferimentos ao remover o anzol e manusear.'],
    ['geraete', 'sicherheit'], ['hecht', 'zander']],

  ['bbg-213', 'behandlung_der_gefangenen_fische',
    ['Welche Verletzungen kann ein Angelhaken verursachen?',
     'What injuries can a fishing hook cause?',
     'Quais lesões um anzol pode causar?'],
    [['Verletzungen an Maul, Kiemen, Augen und Schlund', 'Injuries to the mouth, gills, eyes and throat', 'Lesões na boca, brânquias, olhos e garganta'],
     ['Verletzungen nur an der Schwanzflosse', 'Injuries only to the tail fin', 'Lesões apenas na nadadeira caudal'],
     ['Verletzungen an den Schuppen des Rückens', 'Injuries to the scales of the back', 'Lesões nas escamas do dorso']],
    0,
    ['Haken können das Maul, die Kiemen, die Augen oder den Schlund verletzen. Durch schonendes Hakenlösen werden diese Verletzungen minimiert.',
     'Hooks can injure the mouth, the gills, the eyes or the throat. Gentle unhooking minimises these injuries.',
     'Anzóis podem ferir a boca, as brânquias, os olhos ou a garganta. A remoção cuidadosa minimiza essas lesões.'],
    ['handling', 'tierschutz'], ['hecht', 'zander']],

  ['bbg-214', 'behandlung_der_gefangenen_fische',
    ['Was ist beim Umgang mit einem verletzten Fisch zu tun?',
     'What should be done when dealing with an injured fish?',
     'O que se deve fazer ao lidar com um peixe ferido?'],
    [['Ihn schonend behandeln und je nach Zustand zurücksetzen oder töten', 'Handle it gently and either release or kill it depending on its condition', 'Manuseá-lo com cuidado e, conforme o estado, soltá-lo ou abatê-lo'],
     ['Ihn immer verletzt zurückwerfen', 'Always throw it back injured', 'Sempre jogá-lo ferido de volta'],
     ['Ihn am Ufer liegen lassen', 'Leave it on the bank', 'Deixá-lo na margem']],
    0,
    ['Leicht verletzte Fische können schonend zurückgesetzt werden. Schwer verletzte Fische, die nicht überleben würden, werden tierschutzgerecht getötet.',
     'Slightly injured fish can be released gently. Heavily injured fish that would not survive are killed in an animal-friendly way.',
     'Peixes levemente feridos podem ser soltos com cuidado. Peixes gravemente feridos, que não sobreviveriam, são abatidos de forma respeitosa.'],
    ['tierschutz', 'handling'], ['hecht', 'zander']],

  ['bbg-215', 'behandlung_der_gefangenen_fische',
    ['Warum sollten Fische beim Hakenlösen möglichst im Wasser bleiben?',
     'Why should fish stay in the water as much as possible when unhooking?',
     'Por que os peixes devem permanecer na água o máximo possível ao remover o anzol?'],
    [['Weil sie dort weniger Stress erleiden und die Schleimschicht geschont wird', 'Because they suffer less stress there and the slime layer is protected', 'Porque ali sofrem menos estresse e a camada de muco é preservada'],
     ['Weil sie dort schneller wachsen', 'Because they grow faster there', 'Porque ali crescem mais rápido'],
     ['Weil sie dort schwerer werden', 'Because they become heavier there', 'Porque ali ficam mais pesados']],
    0,
    ['Im Wasser bleibt die Kiemenatmung erhalten und der Fisch wird nicht durch Trockenheit gestresst. Das verbessert die Überlebenschance zurückgesetzter Fische.',
     'In the water, gill breathing continues and the fish is not stressed by dryness. This improves the survival chance of released fish.',
     'Na água, a respiração pelas brânquias continua e o peixe não é estressado pelo ressecamento. Isso melhora a chance de sobrevivência dos peixes soltos.'],
    ['fangen-und-freilassen', 'tierschutz'], ['hecht', 'zander', 'barsch']],

  ['bbg-216', 'behandlung_der_gefangenen_fische',
    ['Welche Werkzeuge gehören zur Ausrüstung für die Behandlung gefangener Fische?',
     'Which tools belong to the equipment for handling caught fish?',
     'Quais ferramentas fazem parte do equipamento para o manuseio de peixes capturados?'],
    [['Hakenlöser, Maulschutz, Betäubungsstock, Messer und feuchtes Tuch', 'Hook remover, mouth guard, priest, knife and a wet cloth', 'Removedor de anzol, protetor de boca, bastão de atordoamento, faca e pano molhado'],
     ['Nur ein Spaten', 'Only a spade', 'Apenas uma pá'],
     ['Nur eine Taschenlampe', 'Only a torch', 'Apenas uma lanterna']],
    0,
    ['Zur fischschonenden Ausrüstung gehören Hakenlöser, Maulschutz, Betäubungsstock, ein scharfes Messer und ein feuchtes Tuch. Sie ermöglichen schonende Behandlung und tierschutzgerechtes Töten.',
     'Fish-friendly equipment includes a hook remover, mouth guard, priest, a sharp knife and a wet cloth. They enable gentle handling and animal-friendly killing.',
     'O equipamento que respeita os peixes inclui removedor de anzol, protetor de boca, bastão de atordoamento, faca afiada e pano molhado. Eles permitem manuseio cuidadoso e abate respeitoso.'],
    ['geraete', 'tierschutz'], ['hecht', 'zander', 'karpfen']],

  ['bbg-217', 'behandlung_der_gefangenen_fische',
    ['Warum sollte der Betäubungsschlag gezielt und kräftig ausgeführt werden?',
     'Why should the stunning blow be carried out in a targeted and firm way?',
     'Por que o golpe de atordoamento deve ser direcionado e firme?'],
    [['Damit der Fisch sofort bewusstlos wird und nicht wieder aufwacht', 'So that the fish becomes unconscious immediately and does not wake up again', 'Para que o peixe perca a consciência imediatamente e não acorde de novo'],
     ['Damit der Fisch größer erscheint', 'So that the fish appears larger', 'Para que o peixe pareça maior'],
     ['Damit die Schuppen glänzen', 'So that the scales shine', 'Para que as escamas brilhem']],
    0,
    ['Ein gezielter, kräftiger Schlag auf den Schädel betäubt den Fisch zuverlässig. Schwache Schläge führen zu unnötigem Leiden.',
     'A targeted, firm blow to the skull stuns the fish reliably. Weak blows cause unnecessary suffering.',
     'Um golpe direcionado e firme no crânio atordoa o peixe de forma confiável. Golpes fracos causam sofrimento desnecessário.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-218', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter \u201eAusnehmen\u201c eines Fisches?',
     'What is meant by gutting a fish?',
     'O que se entende por eviscerar um peixe?'],
    [['Das Entfernen der Innereien aus der Bauchhöhle', 'Removing the innards from the abdominal cavity', 'A remoção das vísceras da cavidade abdominal'],
     ['Das Entfernen der Schuppen', 'Removing the scales', 'A remoção das escamas'],
     ['Das Entfernen der Flossen', 'Removing the fins', 'A remoção das nadadeiras']],
    0,
    ['Beim Ausnehmen wird der Bauch aufgeschnitten und die Innereien werden entfernt. Das geschieht möglichst bald nach dem Fang, um die Qualität zu erhalten.',
     'When gutting, the belly is cut open and the innards are removed. This is done as soon as possible after the catch to preserve quality.',
     'Ao eviscerar, a barriga é aberta e as vísceras são removidas. Isso é feito o quanto antes após a captura, para preservar a qualidade.'],
    ['zubereitung', 'hygiene'], ['hecht', 'karpfen']],

  ['bbg-219', 'behandlung_der_gefangenen_fische',
    ['Wann sollte man Fische ausnehmen?',
     'When should one gut fish?',
     'Quando se deve eviscerar os peixes?'],
    [['Möglichst bald nach dem Fang', 'As soon as possible after the catch', 'O quanto antes após a captura'],
     ['Erst nach einer Woche', 'Only after a week', 'Somente depois de uma semana'],
     ['Erst unmittelbar vor dem Verzehr in der Küche', 'Only immediately before eating in the kitchen', 'Somente imediatamente antes de comer, na cozinha']],
    0,
    ['Je früher der Fisch ausgenommen wird, desto besser bleiben Geschmack und Haltbarkeit. Die Innereien können den Verderb beschleunigen.',
     'The earlier the fish is gutted, the better the taste and shelf life remain. The innards can accelerate spoilage.',
     'Quanto antes o peixe for eviscerado, melhor se mantêm o sabor e a validade. As vísceras podem acelerar a deterioração.'],
    ['zubereitung', 'hygiene'], ['hecht', 'karpfen', 'zander']],

  ['bbg-220', 'behandlung_der_gefangenen_fische',
    ['Warum darf die Gallenblase beim Ausnehmen nicht verletzt werden?',
     'Why must the gallbladder not be injured when gutting?',
     'Por que a vesícula biliar não pode ser ferida ao eviscerar?'],
    [['Weil die austretende Galle das Fleisch bitter macht', 'Because the escaping bile makes the meat bitter', 'Porque a bile que vaza deixa a carne amarga'],
     ['Weil die Galle giftig ist', 'Because the bile is poisonous', 'Porque a bile é venenosa'],
     ['Weil die Galle das Fleisch süß macht', 'Because the bile makes the meat sweet', 'Porque a bile deixa a carne doce']],
    0,
    ['Wird die Gallenblase verletzt, läuft Galle aus und verfärbt sowie verbittert das Fleisch. Beim Ausnehmen wird sie daher vorsichtig entfernt.',
     'If the gallbladder is injured, bile leaks out and discolours and embitters the meat. When gutting it is therefore removed carefully.',
     'Se a vesícula biliar for ferida, a bile vaza e descolore e amarga a carne. Por isso, ela é removida com cuidado na evisceração.'],
    ['zubereitung', 'hygiene'], ['hecht', 'karpfen']],

  ['bbg-221', 'behandlung_der_gefangenen_fische',
    ['Welche Teile werden beim Ausnehmen entfernt?',
     'Which parts are removed when gutting?',
     'Quais partes são removidas ao eviscerar?'],
    [['Die Innereien und in der Regel die Kiemen', 'The innards and usually the gills', 'As vísceras e, normalmente, as brânquias'],
     ['Nur die Augen', 'Only the eyes', 'Somente os olhos'],
     ['Nur die Schuppen', 'Only the scales', 'Somente as escamas']],
    0,
    ['Beim Ausnehmen werden die Innereien entfernt, und meist werden auch die Kiemen herausgeschnitten. Schuppen werden separat entfernt.',
     'When gutting, the innards are removed and usually the gills are cut out too. Scales are removed separately.',
     'Ao eviscerar, as vísceras são removidas e, normalmente, as brânquias também são cortadas. As escamas são removidas separadamente.'],
    ['zubereitung', 'hygiene'], ['hecht', 'karpfen']],

  ['bbg-222', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter \u201eTagesfang\u201c?',
     'What is meant by \u201csame-day catch\u201c?',
     'O que se entende por \u201cpeixe do dia\u201d?'],
    [['Fische, die am selben Tag gefangen und frisch verarbeitet werden', 'Fish caught on the same day and processed fresh', 'Peixes capturados no mesmo dia e processados frescos'],
     ['Fische, die eine Woche gelagert wurden', 'Fish stored for a week', 'Peixes armazenados por uma semana'],
     ['Fische, die nachts gefangen wurden', 'Fish caught at night', 'Peixes capturados à noite']],
    0,
    ['Ein Tagesfang ist ein Fang, der am selben Tag verwendet wird. Er hat die beste Qualität, weil der Verderb noch nicht eingesetzt hat.',
     'A same-day catch is a catch that is used on the same day. It has the best quality because spoilage has not yet begun.',
     'Um peixe do dia é uma captura usada no mesmo dia. Ele tem a melhor qualidade porque a deterioração ainda não começou.'],
    ['zubereitung', 'lagerung'], ['hecht', 'zander']],

  ['bbg-223', 'behandlung_der_gefangenen_fische',
    ['Warum ist es wichtig, Fische nach dem Fang schnell zu kühlen?',
     'Why is it important to cool fish quickly after catching?',
     'Por que é importante resfriar rapidamente os peixes após a captura?'],
    [['Weil Kälte den Verderb verlangsamt und die Qualität erhält', 'Because cold slows spoilage and preserves quality', 'Porque o frio retarda a deterioração e preserva a qualidade'],
     ['Weil Kälte die Fische wachsen lässt', 'Because cold makes the fish grow', 'Porque o frio faz os peixes crescerem'],
     ['Weil Kälte den Geschmack verändert', 'Because cold changes the taste', 'Porque o frio altera o sabor']],
    0,
    ['Bakterien und Enzyme arbeiten bei Kälte langsamer. Schnelles Kühlen erhält daher Frische, Geschmack und Haltbarkeit des Fisches.',
     'Bacteria and enzymes work more slowly in the cold. Quick cooling therefore preserves the freshness, taste and shelf life of the fish.',
     'Bactérias e enzimas trabalham mais devagar no frio. O resfriamento rápido, portanto, preserva o frescor, o sabor e a validade do peixe.'],
    ['lagerung', 'qualitaet'], ['hecht', 'karpfen']],

  ['bbg-224', 'behandlung_der_gefangenen_fische',
    ['Was sollte man tun, wenn man einen Fisch entnimmt, den man nicht sofort verarbeitet?',
     'What should one do when taking a fish that one does not process immediately?',
     'O que se deve fazer ao levar um peixe que não será processado imediatamente?'],
    [['Ihn sofort töten, ausnehmen und kühl lagern', 'Kill, gut and cool it immediately', 'Abatê-lo imediatamente, eviscerá-lo e refrigerá-lo'],
     ['Ihn lebend in den Kühlschrank legen', 'Put it alive in the refrigerator', 'Colocá-lo vivo na geladeira'],
     ['Ihn im Eimer ohne Wasser lassen', 'Leave it in a bucket without water', 'Deixá-lo em um balde sem água']],
    0,
    ['Entnommene Fische werden sofort getötet, ausgenommen und gekühlt. Lebende Fische gehören nicht in den Kühlschrank, da das Tierschutzgesetz dies verbietet.',
     'Taken fish are killed, gutted and cooled immediately. Live fish do not belong in the refrigerator, as animal welfare law prohibits this.',
     'Peixes levados são abatidos, eviscerados e refrigerados imediatamente. Peixes vivos não devem ir à geladeira, pois a lei de bem-estar animal proíbe isso.'],
    ['tierschutz', 'lagerung'], ['hecht', 'karpfen']],

  ['bbg-225', 'behandlung_der_gefangenen_fische',
    ['Warum darf man Fische nicht an den Kiemen aufhängen?',
     'Why must fish not be hung by the gills?',
     'Por que os peixes não devem ser pendurados pelas brânquias?'],
    [['Weil die Kiemen schwer verletzt werden und der Fisch unnötig leidet', 'Because the gills are severely injured and the fish suffers unnecessarily', 'Porque as brânquias são gravemente feridas e o peixe sofre desnecessariamente'],
     ['Weil das Fleisch dadurch süßer wird', 'Because the meat becomes sweeter that way', 'Porque a carne fica mais doce assim'],
     ['Weil die Schuppen abfallen', 'Because the scales fall off', 'Porque as escamas caem']],
    0,
    ['Das Aufhängen an den Kiemen zerreißt empfindliches Gewebe und ist tierschutzwidrig. Tote Fische werden nicht aufgehängt, sondern liegend behandelt.',
     'Hanging by the gills tears sensitive tissue and violates animal welfare. Dead fish are not hung but handled lying down.',
     'Pendurar pelas brânquias rasga tecidos sensíveis e viola o bem-estar animal. Peixes mortos não são pendurados, mas manuseados deitados.'],
    ['tierschutz', 'handling'], ['hecht', 'zander']],

  ['bbg-226', 'behandlung_der_gefangenen_fische',
    ['Wie erkennt man, dass ein Fisch sicher tot ist?',
     'How does one recognise that a fish is certainly dead?',
     'Como se reconhece que um peixe está certamente morto?'],
    [['An fehlender Kiemenbewegung und fehlender Reaktion auf Berührung', 'By the absence of gill movement and the absence of a reaction to touch', 'Pela ausência de movimento das brânquias e de reação ao toque'],
     ['An geöffneten Augen', 'By open eyes', 'Por olhos abertos'],
     ['An einer dunklen Färbung', 'By a dark colouring', 'Por uma coloração escura']],
    0,
    ['Ein toter Fisch bewegt die Kiemendeckel nicht mehr und reagiert nicht auf Berührung. Erst nach sicherer Tötung wird der Fisch weiterverarbeitet.',
     'A dead fish no longer moves its gill covers and does not react to touch. Only after certain death is the fish further processed.',
     'Um peixe morto não move mais os opérculos e não reage ao toque. Somente após a morte certa o peixe é processado.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-227', 'behandlung_der_gefangenen_fische',
    ['Was versteht man unter der Schleimhaut (Cuticula) beim Fisch?',
     'What is meant by the slime coat (cuticle) of the fish?',
     'O que se entende por camada de muco (cutícula) do peixe?'],
    [['Die schützende Schleimschicht auf den Schuppen', 'The protective slime layer on the scales', 'A camada protetora de muco sobre as escamas'],
     ['Die Schwimmblase', 'The swim bladder', 'A bexiga natatória'],
     ['Die äußere Hautschicht der Flossen', 'The outer skin layer of the fins', 'A camada externa da pele das nadadeiras']],
    0,
    ['Die Cuticula ist die dünne Schleimschicht, die den Fisch vor Krankheitserregern schützt. Sie wird durch trockene Hände und raue Netze beschädigt.',
     'The cuticle is the thin slime layer that protects the fish from pathogens. It is damaged by dry hands and rough nets.',
     'A cutícula é a fina camada de muco que protege o peixe contra agentes patogênicos. Ela é danificada por mãos secas e redes ásperas.'],
    ['handling', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-228', 'behandlung_der_gefangenen_fische',
    ['Warum ist der Schleim auf der Fischhaut wichtig?',
     'Why is the slime on the fish skin important?',
     'Por que o muco na pele do peixe é importante?'],
    [['Er schützt vor Krankheiten und verringert den Wasserwiderstand', 'It protects against diseases and reduces water resistance', 'Ele protege contra doenças e reduz a resistência da água'],
     ['Er dient als Nahrung', 'It serves as food', 'Ele serve de alimento'],
     ['Er macht den Fisch schwerer', 'It makes the fish heavier', 'Ele deixa o peixe mais pesado']],
    0,
    ['Der Schleim bildet eine Schutzbarriere gegen Bakterien und Pilze und erleichtert das Gleiten im Wasser. Seine Zerstörung gefährdet die Gesundheit des Fisches.',
     'The slime forms a protective barrier against bacteria and fungi and makes gliding through water easier. Destroying it endangers the health of the fish.',
     'O muco forma uma barreira protetora contra bactérias e fungos e facilita o deslize na água. Sua destruição ameaça a saúde do peixe.'],
    ['handling', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-229', 'behandlung_der_gefangenen_fische',
    ['Welche Folgen hat das Werfen von Fischen auf den Boden?',
     'What are the consequences of throwing fish onto the ground?',
     'Quais são as consequências de jogar peixes no chão?'],
    [['Verletzungen, Verlust der Schleimhaut und unnötiger Stress', 'Injuries, loss of the slime coat and unnecessary stress', 'Ferimentos, perda do muco e estresse desnecessário'],
     ['Eine bessere Fleischqualität', 'Better meat quality', 'Uma melhor qualidade da carne'],
     ['Ein schnelleres Wachstum', 'Faster growth', 'Um crescimento mais rápido']],
    0,
    ['Auf den Boden geworfene Fische verlieren Schleim und Schuppen, verletzen sich und erleiden unnötigen Stress. Fische werden daher nie geworfen, sondern schonend behandelt.',
     'Fish thrown on the ground lose slime and scales, injure themselves and suffer unnecessary stress. Fish are therefore never thrown but handled gently.',
     'Peixes jogados no chão perdem muco e escamas, se ferem e sofrem estresse desnecessário. Por isso, peixes nunca são jogados, mas manuseados com cuidado.'],
    ['tierschutz', 'handling'], ['hecht', 'karpfen']],

  ['bbg-230', 'behandlung_der_gefangenen_fische',
    ['Welche Konsequenz kann die Nichteinhaltung der Tierschutzregeln beim Angeln haben?',
     'What consequence can the violation of animal welfare rules when fishing have?',
     'Qual consequência a violação das regras de bem-estar animal na pesca pode ter?'],
    [['Sie kann als Ordnungswidrigkeit oder Straftat geahndet werden', 'It can be punished as an administrative offence or a crime', 'Ela pode ser punida como infração administrativa ou crime'],
     ['Sie hat keinerlei Folgen', 'It has no consequences at all', 'Ela não tem nenhuma consequência'],
     ['Sie führt nur zu einer Verwarnung durch andere Angler', 'It only leads to a warning by other anglers', 'Ela gera apenas uma advertência de outros pescadores']],
    0,
    ['Tierschutzverstöße wie unnötiges Töten oder Quälen von Fischen können nach dem Tierschutzgesetz als Ordnungswidrigkeit oder Straftat geahndet werden.',
     'Animal welfare violations such as unnecessary killing or tormenting of fish can be punished under the Animal Welfare Act as an administrative offence or a crime.',
     'Violações do bem-estar animal, como matar ou atormentar peixes desnecessariamente, podem ser punidas pela Lei de Bem-Estar Animal como infração administrativa ou crime.'],
    ['recht', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-231', 'behandlung_der_gefangenen_fische',
    ['Darf man lebende Fische in den Kühlschrank legen?',
     'May one put live fish in the refrigerator?',
     'Pode-se colocar peixes vivos na geladeira?'],
    [['Nein, Fische müssen vor dem Kühlen getötet werden', 'No, fish must be killed before cooling', 'Não, os peixes devem ser abatidos antes de refrigerar'],
     ['Ja, das ist die übliche Methode', 'Yes, that is the usual method', 'Sim, esse é o método usual'],
     ['Ja, aber nur für eine Stunde', 'Yes, but only for an hour', 'Sim, mas somente por uma hora']],
    0,
    ['Lebende Fische dürfen nicht in den Kühlschrank gelegt werden, da sie dort langsam ersticken und unnötig leiden. Zuerst wird der Fisch getötet, dann gekühlt.',
     'Live fish must not be put in the refrigerator because they suffocate slowly there and suffer unnecessarily. First the fish is killed, then cooled.',
     'Peixes vivos não devem ser colocados na geladeira, pois sufocam lentamente ali e sofrem desnecessariamente. Primeiro o peixe é abatido, depois refrigerado.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-232', 'behandlung_der_gefangenen_fische',
    ['Warum sollte ein Angler ein feuchtes Tuch mitführen?',
     'Why should an angler carry a wet cloth?',
     'Por que um pescador deve levar um pano molhado?'],
    [['Zum schonenden Festhalten und Transport von Fischen', 'For gently holding and transporting fish', 'Para segurar e transportar peixes com cuidado'],
     ['Zum Reinigen der Rute', 'For cleaning the rod', 'Para limpar a vara'],
     ['Zum Anzünden eines Feuers', 'For lighting a fire', 'Para acender uma fogueira']],
    0,
    ['Ein feuchtes Tuch schützt die Schleimhaut des Fisches beim Festhalten und hält ihn beim Transport feucht. Das verringert Stress und Verletzungen.',
     'A wet cloth protects the slime layer of the fish when holding it and keeps it moist during transport. This reduces stress and injuries.',
     'Um pano molhado protege o muco do peixe ao segurá-lo e o mantém úmido no transporte. Isso reduz estresse e ferimentos.'],
    ['geraete', 'handling'], ['hecht', 'karpfen']],

  ['bbg-233', 'behandlung_der_gefangenen_fische',
    ['Was ist beim Messen eines gefangenen Fisches zu beachten?',
     'What should be observed when measuring a caught fish?',
     'O que se deve observar ao medir um peixe capturado?'],
    [['Der Fisch wird vom Maul bis zum Ende der Schwanzflosse gemessen', 'The fish is measured from the mouth to the end of the tail fin', 'O peixe é medido da boca até o fim da nadadeira caudal'],
     ['Nur der Kopf wird gemessen', 'Only the head is measured', 'Somente a cabeça é medida'],
     ['Die Messung ist völlig unwichtig', 'Measuring is completely unimportant', 'A medição é totalmente desnecessária']],
    0,
    ['Die Gesamtlänge wird vom Maul bis zum äußersten Ende der Schwanzflosse gemessen. Sie entscheidet, ob das Mindestmaß eingehalten wird.',
     'The total length is measured from the mouth to the outermost end of the tail fin. It decides whether the minimum size is respected.',
     'O comprimento total é medido da boca até a extremidade mais externa da nadadeira caudal. Ele decide se o tamanho mínimo é respeitado.'],
    ['handling', 'recht'], ['hecht', 'zander']],

  ['bbg-234', 'behandlung_der_gefangenen_fische',
    ['Was macht man mit einem untermaßigen Fisch?',
     'What does one do with an undersized fish?',
     'O que se faz com um peixe abaixo do tamanho mínimo?'],
    [['Man setzt ihn sofort und schonend zurück', 'One releases it immediately and gently', 'Solta-se imediatamente e com cuidado'],
     ['Man nimmt ihn trotzdem mit', 'One takes it anyway', 'Leva-se mesmo assim'],
     ['Man legt ihn ins Gras', 'One places it in the grass', 'Coloca-se na grama']],
    0,
    ['Untermaßige Fische müssen sofort und schonend zurückgesetzt werden. Ihre Entnahme wäre eine Ordnungswidrigkeit.',
     'Undersized fish must be released immediately and gently. Taking them would be an administrative offence.',
     'Peixes abaixo do tamanho mínimo devem ser soltos imediatamente e com cuidado. Levá-los seria infração administrativa.'],
    ['recht', 'fangen-und-freilassen'], ['hecht', 'zander', 'barsch']],

  ['bbg-235', 'behandlung_der_gefangenen_fische',
    ['Warum sollte man beim Hakenlösen nicht im Fischmaul wühlen?',
     'Why should one not rummage in the fish\u2019s mouth when removing the hook?',
     'Por que não se deve remexer na boca do peixe ao remover o anzol?'],
    [['Weil Kiemen, Augen und empfindliches Gewebe verletzt werden können', 'Because gills, eyes and sensitive tissue can be injured', 'Porque brânquias, olhos e tecidos sensíveis podem ser feridos'],
     ['Weil der Haken dann schneller sitzt', 'Because the hook then sits faster', 'Porque então o anzol fisga mais rápido'],
     ['Weil das den Fisch größer macht', 'Because that makes the fish larger', 'Porque isso deixa o peixe maior']],
    0,
    ['Unkontrolliertes Wühlen verletzt den Fisch unnötig. Mit Hakenlöser und gezielten Griffen wird der Haken schnell und schonend entfernt.',
     'Uncontrolled rummaging injures the fish unnecessarily. With a hook remover and targeted grips the hook is removed quickly and gently.',
     'Remexer sem controle fere o peixe desnecessariamente. Com o removedor de anzol e pegadas direcionadas, o anzol é removido rápido e com cuidado.'],
    ['handling', 'tierschutz'], ['hecht', 'zander']],

  ['bbg-236', 'behandlung_der_gefangenen_fische',
    ['Welche Fehler führen beim Angeln zu unnötigem Leiden der Fische?',
     'Which mistakes cause unnecessary suffering of fish when fishing?',
     'Quais erros causam sofrimento desnecessário aos peixes na pesca?'],
    [['Langes Liegenlassen an Land, Trockenfassen und Aufhängen an den Kiemen', 'Leaving fish on the land for long, dry-handling and hanging them by the gills', 'Deixá-los muito tempo em terra, manuseá-los secos e pendurá-los pelas brânquias'],
     ['Schnelles Töten und sofortiges Zurücksetzen', 'Quick killing and immediate release', 'Abater rapidamente e soltar imediatamente'],
     ['Die Verwendung feuchter Hände', 'The use of wet hands', 'O uso de mãos molhadas']],
    0,
    ['Langes Landliegen, Anfassen mit trockenen Händen und das Aufhängen an den Kiemen verursachen unnötiges Leiden. Schonende Techniken sind dagegen tierschutzgerecht.',
     'Leaving fish on the land for long, handling them with dry hands and hanging them by the gills cause unnecessary suffering. Gentle techniques, by contrast, are animal-friendly.',
     'Deixá-los muito tempo em terra, tocá-los com mãos secas e pendurá-los pelas brânquias causam sofrimento desnecessário. Técnicas cuidadosas, ao contrário, respeitam os animais.'],
    ['tierschutz', 'handling'], ['hecht', 'karpfen']],

  ['bbg-237', 'behandlung_der_gefangenen_fische',
    ['Warum sollte man den Fisch vor dem Töten nicht längere Zeit außerhalb des Wassers lassen?',
     'Why should one not keep the fish out of the water for a long time before killing?',
     'Por que não se deve manter o peixe fora da água por muito tempo antes de abatê-lo?'],
    [['Weil er dabei unnötig leidet und Stress erleidet', 'Because it suffers unnecessarily and is stressed', 'Porque ele sofre e fica estressado desnecessariamente'],
     ['Weil er dann schwerer wird', 'Because it then becomes heavier', 'Porque então ele fica mais pesado'],
     ['Weil er dann besser schmeckt', 'Because it then tastes better', 'Porque então ele tem melhor sabor']],
    0,
    ['Fische, die nicht zurückgesetzt werden, werden unmittelbar nach dem Fang getötet. Langes Warten an der Luft verursacht unnötiges Leiden.',
     'Fish that are not released are killed immediately after the catch. Waiting long in the air causes unnecessary suffering.',
     'Peixes que não serão soltos são abatidos imediatamente após a captura. Esperar muito no ar causa sofrimento desnecessário.'],
    ['toeten', 'tierschutz'], ['hecht', 'karpfen']],

  ['bbg-238', 'behandlung_der_gefangenen_fische',
    ['Welche Rolle spielt die richtige Wahl der Haken beim Zurücksetzen von Fischen?',
     'What role does the right choice of hook play when releasing fish?',
     'Qual é o papel da escolha certa do anzol na soltura de peixes?'],
    [['Widerhakenlose oder kleine Haken verringern Verletzungen und erleichtern das Lösen', 'Barbless or small hooks reduce injuries and make unhooking easier', 'Anzóis sem farpa ou pequenos reduzem ferimentos e facilitam a remoção'],
     ['Die Hakenwahl spielt keine Rolle', 'The hook choice does not matter', 'A escolha do anzol não importa'],
     ['Große Drillinge sind am schonendsten', 'Large treble hooks are the gentlest', 'Anzóis triplos grandes são os mais cuidadosos']],
    0,
    ['Beim Fangen und Freilassen schonen widerhakenlose Haken das Fischmaul. Sie lassen sich schnell lösen und verringern die Verletzungsgefahr.',
     'When catching and releasing, barbless hooks protect the fish\u2019s mouth. They can be removed quickly and reduce the risk of injury.',
     'Na captura e soltura, anzóis sem farpa protegem a boca do peixe. Eles podem ser removidos rapidamente e reduzem o risco de ferimentos.'],
    ['fangen-und-freilassen', 'haken'], ['hecht', 'zander', 'barsch']],

  ['bbg-239', 'behandlung_der_gefangenen_fische',
    ['Was ist beim Transport von Fischen im Sommer besonders wichtig?',
     'What is especially important when transporting fish in summer?',
     'O que é especialmente importante ao transportar peixes no verão?'],
    [['Eine schnelle Kühlung und Schutz vor direkter Sonne', 'Fast cooling and protection from direct sun', 'Resfriamento rápido e proteção contra o sol direto'],
     ['Eine lange Fahrt ohne Kühlung', 'A long drive without cooling', 'Uma viagem longa sem refrigeração'],
     ['Das Offenlassen im Kofferraum', 'Leaving them open in the boot', 'Deixá-los abertos no porta-malas']],
    0,
    ['Hohe Außentemperaturen beschleunigen den Verderb. Im Sommer werden Fische daher sofort gekühlt, abgedeckt und vor Sonne geschützt transportiert.',
     'High outside temperatures accelerate spoilage. In summer, fish are therefore cooled immediately, covered and transported protected from the sun.',
     'As altas temperaturas externas aceleram a deterioração. No verão, os peixes são resfriados imediatamente, cobertos e transportados protegidos do sol.'],
    ['transport', 'lagerung'], ['hecht', 'zander']],

  ['bbg-240', 'behandlung_der_gefangenen_fische',
    ['Wie sollte man mit einem sehr großen Fisch beim Landen umgehen?',
     'How should one deal with a very large fish when landing it?',
     'Como se deve lidar com um peixe muito grande ao aterrissá-lo?'],
    [['Den Drill fortsetzen, bis der Fisch ermüdet ist, und dann mit einem großen Kescher landen', 'Continue playing until the fish is tired and then land it with a large net', 'Continuar a brigar até o peixe se cansar e então aterrissá-lo com uma rede grande'],
     ['Den Fisch sofort am Haken hochreißen', 'Yank the fish up immediately on the hook', 'Arrancar o peixe imediatamente pelo anzol'],
     ['Den Fisch ans Ufer ziehen, solange er noch kämpft', 'Pull the fish to the bank while it still fights', 'Puxar o peixe até a margem enquanto ainda luta']],
    0,
    ['Große Fische werden geduldig gedrillt, bis sie ermüden, und dann mit einem ausreichend großen, knotenlosen Kescher gelandet. So bleiben Fisch und Schnur heil.',
     'Large fish are played patiently until they tire and are then landed with a sufficiently large, knotless net. This keeps fish and line intact.',
     'Peixes grandes são brincados com paciência até se cansarem e então aterrissados com uma rede grande e sem nós. Assim, peixe e linha permanecem intactos.'],
    ['technik', 'tierschutz'], ['karpfen', 'hecht', 'wels']],
]
