// Category: einschlaegige_rechtsvorschriften — Legal regulations (2/2)
export const questions = [
  // --- Schonzeiten / Mindestmasse ---
  ['bbg-271', 'einschlaegige_rechtsvorschriften',
    ['Was versteht man unter einer Schonzeit?',
     'What is meant by a closed season?',
     'O que se entende por época de defeso?'],
    [['Den Zeitraum, in dem bestimmte Fische nicht entnommen werden dürfen', 'The period in which certain fish may not be taken', 'O período em que certos peixes não podem ser capturados'],
     ['Die Zeit, in der die Fische am besten beißen', 'The time when the fish bite best', 'O tempo em que os peixes mordem melhor'],
     ['Die Zeit, in der das Angeln kostenlos ist', 'The time when fishing is free', 'O tempo em que a pesca é gratuita']],
    0,
    ['Schonzeiten schützen die Fische während der Laichzeit. In dieser Zeit dürfen die betreffenden Arten nicht entnommen werden (§2 BbgFischO).',
     'Closed seasons protect the fish during their spawning time. During this period the species concerned may not be taken (section 2 BbgFischO).',
     'Os defesos protegem os peixes durante a época de desova. Nesse período, as espécies em questão não podem ser capturadas (§2 BbgFischO).'],
    ['schonzeit', 'recht'], ['hecht', 'zander']],

  ['bbg-272', 'einschlaegige_rechtsvorschriften',
    ['Warum gibt es Schonzeiten für Fische?',
     'Why do closed seasons exist for fish?',
     'Por que existem defesos para os peixes?'],
    [['Um die Fische während der Laichzeit zu schützen und den Bestand zu erhalten', 'To protect the fish during the spawning season and preserve the stock', 'Para proteger os peixes durante a desova e preservar o estoque'],
     ['Um den Anglern eine Pause zu gönnen', 'To give the anglers a break', 'Para dar um descanso aos pescadores'],
     ['Um den Fischen das Fressen zu erleichtern', 'To make feeding easier for the fish', 'Para facilitar a alimentação dos peixes']],
    0,
    ['In der Laichzeit sind die Fische besonders empfindlich und wichtig für den Nachwuchs. Schonzeiten sichern die natürliche Vermehrung (§2 BbgFischO).',
     'During the spawning season the fish are especially sensitive and important for the offspring. Closed seasons secure natural reproduction (section 2 BbgFischO).',
     'Na desova, os peixes estão especialmente sensíveis e são importantes para a prole. Os defesos asseguram a reprodução natural (§2 BbgFischO).'],
    ['schonzeit', 'recht'], ['hecht', 'zander']],

  ['bbg-273', 'einschlaegige_rechtsvorschriften',
    ['Welche Schonzeit hat der Hecht in Brandenburg?',
     'What closed season does the pike have in Brandenburg?',
     'Qual é o defeso do lúcio em Brandemburgo?'],
    [['Vom 1. Februar bis 31. März', 'From 1 February to 31 March', 'De 1º de fevereiro a 31 de março'],
     ['Vom 1. Juni bis 31. Juli', 'From 1 June to 31 July', 'De 1º de junho a 31 de julho'],
     ['Vom 1. Oktober bis 30. November', 'From 1 October to 30 November', 'De 1º de outubro a 30 de novembro']],
    0,
    ['Der Hecht hat in Brandenburg Schonzeit vom 1. Februar bis zum 31. März. In dieser Zeit dürfen Hechte nicht entnommen werden (§2 BbgFischO).',
     'The pike has a closed season in Brandenburg from 1 February to 31 March. During this time pike may not be taken (section 2 BbgFischO).',
     'O lúcio tem defeso em Brandemburgo de 1º de fevereiro a 31 de março. Nesse período, lúcios não podem ser capturados (§2 BbgFischO).'],
    ['schonzeit', 'recht'], ['hecht']],

  ['bbg-274', 'einschlaegige_rechtsvorschriften',
    ['Welche Schonzeit hat der Zander in Brandenburg?',
     'What closed season does the pikeperch have in Brandenburg?',
     'Qual é o defeso do lúcio-perca em Brandemburgo?'],
    [['Vom 1. April bis 31. Mai', 'From 1 April to 31 May', 'De 1º de abril a 31 de maio'],
     ['Vom 1. Januar bis 28. Februar', 'From 1 January to 28 February', 'De 1º de janeiro a 28 de fevereiro'],
     ['Vom 1. September bis 31. Oktober', 'From 1 September to 31 October', 'De 1º de setembro a 31 de outubro']],
    0,
    ['Der Zander hat in Brandenburg Schonzeit vom 1. April bis zum 31. Mai. In dieser Zeit dürfen Zander nicht entnommen werden (§2 BbgFischO).',
     'The pikeperch has a closed season in Brandenburg from 1 April to 31 May. During this time pikeperch may not be taken (section 2 BbgFischO).',
     'O lúcio-perca tem defeso em Brandemburgo de 1º de abril a 31 de maio. Nesse período, lúcios-perca não podem ser capturados (§2 BbgFischO).'],
    ['schonzeit', 'recht'], ['zander']],

  ['bbg-275', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat der Hecht in Brandenburg?',
     'What is the minimum size of the pike in Brandenburg?',
     'Qual é o tamanho mínimo do lúcio em Brandemburgo?'],
    [['45 Zentimeter', '45 centimetres', '45 centímetros'],
     ['35 Zentimeter', '35 centimetres', '35 centímetros'],
     ['60 Zentimeter', '60 centimetres', '60 centímetros']],
    0,
    ['Für den Hecht gilt in Brandenburg ein Mindestmaß von 45 cm. Untermaßige Hechte müssen sofort zurückgesetzt werden (§2 BbgFischO).',
     'The pike has a minimum size of 45 cm in Brandenburg. Undersized pike must be released immediately (section 2 BbgFischO).',
     'O lúcio tem tamanho mínimo de 45 cm em Brandemburgo. Lúcios abaixo do mínimo devem ser soltos imediatamente (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['hecht']],

  ['bbg-276', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat der Zander in Brandenburg?',
     'What is the minimum size of the pikeperch in Brandenburg?',
     'Qual é o tamanho mínimo do lúcio-perca em Brandemburgo?'],
    [['45 Zentimeter', '45 centimetres', '45 centímetros'],
     ['30 Zentimeter', '30 centimetres', '30 centímetros'],
     ['50 Zentimeter', '50 centimetres', '50 centímetros']],
    0,
    ['Für den Zander gilt in Brandenburg ein Mindestmaß von 45 cm. Untermaßige Zander müssen sofort zurückgesetzt werden (§2 BbgFischO).',
     'The pikeperch has a minimum size of 45 cm in Brandenburg. Undersized pikeperch must be released immediately (section 2 BbgFischO).',
     'O lúcio-perca tem tamanho mínimo de 45 cm em Brandemburgo. Lúcios-perca abaixo do mínimo devem ser soltos imediatamente (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['zander']],

  ['bbg-277', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat der Karpfen in Brandenburg?',
     'What is the minimum size of the carp in Brandenburg?',
     'Qual é o tamanho mínimo da carpa em Brandemburgo?'],
    [['35 Zentimeter', '35 centimetres', '35 centímetros'],
     ['25 Zentimeter', '25 centimetres', '25 centímetros'],
     ['50 Zentimeter', '50 centimetres', '50 centímetros']],
    0,
    ['Für den Karpfen gilt in Brandenburg ein Mindestmaß von 35 cm. Eine Schonzeit besteht für den Karpfen nicht (§2 BbgFischO).',
     'The carp has a minimum size of 35 cm in Brandenburg. There is no closed season for the carp (section 2 BbgFischO).',
     'A carpa tem tamanho mínimo de 35 cm em Brandemburgo. Não há defeso para a carpa (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['karpfen']],

  ['bbg-278', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat der Aal in Brandenburg?',
     'What is the minimum size of the eel in Brandenburg?',
     'Qual é o tamanho mínimo da enguia em Brandemburgo?'],
    [['50 Zentimeter', '50 centimetres', '50 centímetros'],
     ['40 Zentimeter', '40 centimetres', '40 centímetros'],
     ['60 Zentimeter', '60 centimetres', '60 centímetros']],
    0,
    ['Für den Aal gilt in Brandenburg ein Mindestmaß von 50 cm. Untermaßige Aale müssen sofort zurückgesetzt werden (§2 BbgFischO).',
     'The eel has a minimum size of 50 cm in Brandenburg. Undersized eels must be released immediately (section 2 BbgFischO).',
     'A enguia tem tamanho mínimo de 50 cm em Brandemburgo. Enguias abaixo do mínimo devem ser soltas imediatamente (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['aal']],

  ['bbg-279', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat die Schleie in Brandenburg?',
     'What is the minimum size of the tench in Brandenburg?',
     'Qual é o tamanho mínimo da tenca em Brandemburgo?'],
    [['25 Zentimeter', '25 centimetres', '25 centímetros'],
     ['20 Zentimeter', '20 centimetres', '20 centímetros'],
     ['35 Zentimeter', '35 centimetres', '35 centímetros']],
    0,
    ['Für die Schleie gilt in Brandenburg ein Mindestmaß von 25 cm. Untermaßige Schleien müssen sofort zurückgesetzt werden (§2 BbgFischO).',
     'The tench has a minimum size of 25 cm in Brandenburg. Undersized tench must be released immediately (section 2 BbgFischO).',
     'A tenca tem tamanho mínimo de 25 cm em Brandemburgo. Tencas abaixo do mínimo devem ser soltas imediatamente (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['schleie']],

  ['bbg-280', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat die Quappe in Brandenburg?',
     'What is the minimum size of the burbot in Brandenburg?',
     'Qual é o tamanho mínimo da lota em Brandemburgo?'],
    [['30 Zentimeter', '30 centimetres', '30 centímetros'],
     ['20 Zentimeter', '20 centimetres', '20 centímetros'],
     ['45 Zentimeter', '45 centimetres', '45 centímetros']],
    0,
    ['Für die Quappe gilt in Brandenburg ein Mindestmaß von 30 cm. Sie laicht im Winter und ist durch besondere Regeln geschützt (§2 BbgFischO).',
     'The burbot has a minimum size of 30 cm in Brandenburg. It spawns in winter and is protected by special rules (section 2 BbgFischO).',
     'A lota tem tamanho mínimo de 30 cm em Brandemburgo. Ela desova no inverno e é protegida por regras especiais (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['quappe']],

  ['bbg-281', 'einschlaegige_rechtsvorschriften',
    ['Was versteht man unter dem Mindestmaß eines Fisches?',
     'What is meant by the minimum size of a fish?',
     'O que se entende por tamanho mínimo de um peixe?'],
    [['Die Mindestgröße, unter der Fische nicht entnommen werden dürfen', 'The minimum size below which fish may not be taken', 'O tamanho mínimo abaixo do qual os peixes não podem ser capturados'],
     ['Die größte erlaubte Fanggröße', 'The largest permitted catch size', 'O maior tamanho de captura permitido'],
     ['Die Länge, ab der Fische geschont werden', 'The length from which fish are protected', 'O comprimento a partir do qual os peixes são protegidos']],
    0,
    ['Das Mindestmaß legt fest, ab welcher Größe ein Fisch entnommen werden darf. Fische unterhalb des Mindestmaßes müssen sofort zurückgesetzt werden (§2 BbgFischO).',
     'The minimum size defines from which size a fish may be taken. Fish below the minimum size must be released immediately (section 2 BbgFischO).',
     'O tamanho mínimo define a partir de qual tamanho um peixe pode ser levado. Peixes abaixo do mínimo devem ser soltos imediatamente (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['hecht', 'zander', 'karpfen']],

  ['bbg-282', 'einschlaegige_rechtsvorschriften',
    ['Wo sind die Schonzeiten und Mindestmaße in Brandenburg festgelegt?',
     'Where are the closed seasons and minimum sizes set out in Brandenburg?',
     'Onde estão definidos os defesos e tamanhos mínimos em Brandemburgo?'],
    [['In der Brandenburgischen Fischereiordnung (BbgFischO)', 'In the Brandenburg Fisheries Ordinance (BbgFischO)', 'Na Ordenança de Pesca de Brandemburgo (BbgFischO)'],
     ['Im BGB', 'In the German Civil Code (BGB)', 'No Código Civil alemão (BGB)'],
     ['In der Straßenverkehrsordnung', 'In the road traffic regulations', 'No Código de Trânsito']],
    0,
    ['Schonzeiten und Mindestmaße sind in der BbgFischO festgelegt, insbesondere in §2 und seiner Anlage. Die aktuelle Fassung ist maßgeblich.',
     'Closed seasons and minimum sizes are set out in the BbgFischO, in particular in section 2 and its annex. The current version is authoritative.',
     'Defesos e tamanhos mínimos estão definidos na BbgFischO, especialmente no §2 e seu anexo. Vale a versão vigente.'],
    ['schonzeit', 'mindestmass', 'recht'], ['hecht', 'zander']],

  ['bbg-283', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Fang eines geschonten Fisches zu tun?',
     'What should be done when catching a fish during its closed season?',
     'O que se deve fazer ao capturar um peixe em defeso?'],
    [['Ihn sofort und schonend zurücksetzen', 'Release it immediately and gently', 'Soltá-lo imediatamente e com cuidado'],
     ['Ihn trotzdem mitnehmen', 'Take it anyway', 'Levá-lo mesmo assim'],
     ['Ihn bis zum Abend aufbewahren', 'Keep it until evening', 'Guardá-lo até a noite']],
    0,
    ['Geschonte Fische dürfen nicht entnommen werden. Sie sind sofort und möglichst unverletzt zurückzusetzen (§2 BbgFischO).',
     'Fish in their closed season may not be taken. They must be released immediately and as uninjured as possible (section 2 BbgFischO).',
     'Peixes em defeso não podem ser capturados. Eles devem ser soltos imediatamente e o mais ilesos possível (§2 BbgFischO).'],
    ['schonzeit', 'recht'], ['hecht', 'zander']],

  ['bbg-284', 'einschlaegige_rechtsvorschriften',
    ['Gibt es eine Schonzeit für den Karpfen?',
     'Is there a closed season for the carp?',
     'Existe defeso para a carpa?'],
    [['Nein, für den Karpfen besteht keine Schonzeit, aber ein Mindestmaß von 35 cm', 'No, there is no closed season for the carp, but a minimum size of 35 cm', 'Não, não há defeso para a carpa, mas há tamanho mínimo de 35 cm'],
     ['Ja, vom 1. April bis 31. Mai', 'Yes, from 1 April to 31 May', 'Sim, de 1º de abril a 31 de maio'],
     ['Ja, das ganze Jahr', 'Yes, all year round', 'Sim, o ano todo']],
    0,
    ['Für den Karpfen besteht keine Schonzeit, wohl aber ein Mindestmaß von 35 cm. Untermaßige Karpfen müssen zurückgesetzt werden (§2 BbgFischO).',
     'There is no closed season for the carp, but there is a minimum size of 35 cm. Undersized carp must be released (section 2 BbgFischO).',
     'Não há defeso para a carpa, mas há tamanho mínimo de 35 cm. Carpas abaixo do mínimo devem ser soltas (§2 BbgFischO).'],
    ['schonzeit', 'mindestmass', 'recht'], ['karpfen']],

  ['bbg-285', 'einschlaegige_rechtsvorschriften',
    ['Welche Schonzeit hat die Bachforelle in Brandenburg?',
     'What closed season does the brown trout have in Brandenburg?',
     'Qual é o defeso da truta-marrom em Brandemburgo?'],
    [['Vom 1. Oktober bis 30. November', 'From 1 October to 30 November', 'De 1º de outubro a 30 de novembro'],
     ['Vom 1. Februar bis 31. März', 'From 1 February to 31 March', 'De 1º de fevereiro a 31 de março'],
     ['Vom 1. Juni bis 31. Juli', 'From 1 June to 31 July', 'De 1º de junho a 31 de julho']],
    0,
    ['Die Bachforelle hat in Brandenburg Schonzeit vom 1. Oktober bis 30. November. Ihr Mindestmaß beträgt 25 cm (§2 BbgFischO).',
     'The brown trout has a closed season in Brandenburg from 1 October to 30 November. Its minimum size is 25 cm (section 2 BbgFischO).',
     'A truta-marrom tem defeso em Brandemburgo de 1º de outubro a 30 de novembro. Seu tamanho mínimo é de 25 cm (§2 BbgFischO).'],
    ['schonzeit', 'mindestmass', 'recht'], ['forelle']],

  ['bbg-286', 'einschlaegige_rechtsvorschriften',
    ['Welches Mindestmaß hat die Bachforelle in Brandenburg?',
     'What is the minimum size of the brown trout in Brandenburg?',
     'Qual é o tamanho mínimo da truta-marrom em Brandemburgo?'],
    [['25 Zentimeter', '25 centimetres', '25 centímetros'],
     ['30 Zentimeter', '30 centimetres', '30 centímetros'],
     ['40 Zentimeter', '40 centimetres', '40 centímetros']],
    0,
    ['Für die Bachforelle gilt in Brandenburg ein Mindestmaß von 25 cm. Sie hat zudem Schonzeit vom 1. Oktober bis 30. November (§2 BbgFischO).',
     'The brown trout has a minimum size of 25 cm in Brandenburg. It also has a closed season from 1 October to 30 November (section 2 BbgFischO).',
     'A truta-marrom tem tamanho mínimo de 25 cm em Brandemburgo. Ela também tem defeso de 1º de outubro a 30 de novembro (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['forelle']],

  ['bbg-287', 'einschlaegige_rechtsvorschriften',
    ['Darf man zur Laichzeit des Hechts gezielt auf Hecht angeln?',
     'May one fish deliberately for pike during the pike spawning season?',
     'Pode-se pescar deliberadamente o lúcio durante a época de desova dele?'],
    [['Nein, der Hecht hat vom 1. Februar bis 31. März Schonzeit', 'No, the pike has a closed season from 1 February to 31 March', 'Não, o lúcio tem defeso de 1º de fevereiro a 31 de março'],
     ['Ja, zu jeder Zeit', 'Yes, at any time', 'Sim, a qualquer momento'],
     ['Ja, aber nur mit Kunstködern', 'Yes, but only with artificial lures', 'Sim, mas somente com iscas artificiais']],
    0,
    ['In der Schonzeit vom 1. Februar bis 31. März dürfen Hechte nicht entnommen werden. Das gezielte Angeln auf Hecht ist in dieser Zeit unzulässig (§2 BbgFischO).',
     'During the closed season from 1 February to 31 March pike may not be taken. Deliberate fishing for pike is not permitted during this time (section 2 BbgFischO).',
     'No defeso de 1º de fevereiro a 31 de março, lúcios não podem ser capturados. A pesca deliberada do lúcio não é permitida nesse período (§2 BbgFischO).'],
    ['schonzeit', 'recht'], ['hecht']],

  ['bbg-288', 'einschlaegige_rechtsvorschriften',
    ['Was gilt für Jungfische, die unter dem Mindestmaß liegen?',
     'What applies to young fish that are below the minimum size?',
     'O que vale para peixes jovens abaixo do tamanho mínimo?'],
    [['Sie müssen sofort und schonend zurückgesetzt werden', 'They must be released immediately and gently', 'Eles devem ser soltos imediatamente e com cuidado'],
     ['Sie dürfen als Köder verwendet werden', 'They may be used as bait', 'Eles podem ser usados como isca'],
     ['Sie dürfen aufbewahrt und später gemessen werden', 'They may be kept and measured later', 'Eles podem ser guardados e medidos depois']],
    0,
    ['Untermaßige Fische dürfen nicht entnommen werden. Sie sind sofort, ohne Beschädigung, zurückzusetzen (§2 BbgFischO).',
     'Undersized fish may not be taken. They must be released immediately, without damage (section 2 BbgFischO).',
     'Peixes abaixo do mínimo não podem ser capturados. Eles devem ser soltos imediatamente, sem danos (§2 BbgFischO).'],
    ['mindestmass', 'recht'], ['hecht', 'zander']],

  // --- gear restrictions / misc ---
  ['bbg-289', 'einschlaegige_rechtsvorschriften',
    ['Welche Fangmethoden sind dem Angler in Brandenburg verboten?',
     'Which fishing methods are prohibited for anglers in Brandenburg?',
     'Quais métodos de pesca são proibidos para pescadores em Brandemburgo?'],
    [['Das Angeln mit lebenden Fischen als Köder und das Fischen mit Netzen oder Reusen', 'Fishing with live fish as bait and fishing with nets or traps', 'Pescar com peixes vivos como isca e pescar com redes ou covos'],
     ['Das Angeln mit einer Handangel', 'Fishing with a hand line rod', 'Pescar com uma vara de mão'],
     ['Das Angeln mit Kunstködern', 'Fishing with artificial lures', 'Pescar com iscas artificiais']],
    0,
    ['Nach §4 BbgFischO sind unter anderem das Angeln mit lebenden Fischen als Köder sowie nicht zugelassene Fanggeräte wie Netze und Reusen verboten.',
     'Under section 4 of the BbgFischO, fishing with live fish as bait and non-approved gear such as nets and traps are prohibited among other things.',
     'Pelo §4 da BbgFischO, são proibidas, entre outras, a pesca com peixes vivos como isca e o uso de equipamentos não autorizados, como redes e covos.'],
    ['recht', 'geraete'], ['hecht', 'zander']],

  ['bbg-290', 'einschlaegige_rechtsvorschriften',
    ['Was regelt §4 BbgFischO?',
     'What does section 4 of the BbgFischO regulate?',
     'O que regula o §4 da BbgFischO?'],
    [['Verbotene Fangmethoden und nicht zugelassene Fanggeräte', 'Prohibited fishing methods and non-approved fishing gear', 'Métodos de pesca proibidos e equipamentos não autorizados'],
     ['Die Höhe der Fischereiabgabe', 'The amount of the fishing levy', 'O valor da taxa de pesca'],
     ['Die Öffnungszeiten der Angelgeschäfte', 'The opening hours of fishing shops', 'O horário de funcionamento das lojas de pesca']],
    0,
    ['§4 BbgFischO regelt die verbotenen Fangmethoden, zum Beispiel das Angeln mit lebenden Köderfischen. Verstöße sind Ordnungswidrigkeiten.',
     'Section 4 of the BbgFischO regulates prohibited fishing methods, for example fishing with live bait fish. Violations are administrative offences.',
     'O §4 da BbgFischO regula os métodos de pesca proibidos, por exemplo a pesca com peixes-isca vivos. Violações são infrações administrativas.'],
    ['recht', 'geraete'], ['hecht', 'zander']],

  ['bbg-291', 'einschlaegige_rechtsvorschriften',
    ['Dürfen tote Köderfische beim Angeln verwendet werden?',
     'May dead bait fish be used when fishing?',
     'Pode-se usar peixes-isca mortos na pesca?'],
    [['Ja, grundsätzlich ist das Angeln mit toten Köderfischen erlaubt', 'Yes, fishing with dead bait fish is basically permitted', 'Sim, a pesca com peixes-isca mortos é basicamente permitida'],
     ['Nein, alle Köderfische sind verboten', 'No, all bait fish are prohibited', 'Não, todos os peixes-isca são proibidos'],
     ['Nur in der Schonzeit des Zielfisches', 'Only during the closed season of the target fish', 'Somente no defeso do peixe alvo']],
    0,
    ['Tote Köderfische sind in Brandenburg grundsätzlich erlaubt. Lebende Fische als Köder sind dagegen nach §4 BbgFischO verboten.',
     'Dead bait fish are basically permitted in Brandenburg. Live fish as bait, on the other hand, are prohibited under section 4 of the BbgFischO.',
     'Peixes-isca mortos são basicamente permitidos em Brandemburgo. Peixes vivos como isca, ao contrário, são proibidos pelo §4 da BbgFischO.'],
    ['recht', 'koeder'], ['hecht', 'zander']],

  ['bbg-292', 'einschlaegige_rechtsvorschriften',
    ['Darf man gefangene Fische als Lebendköder verwenden?',
     'May one use caught fish as live bait?',
     'Pode-se usar peixes capturados como isca viva?'],
    [['Nein, lebende Fische als Köder sind verboten', 'No, live fish as bait are prohibited', 'Não, peixes vivos como isca são proibidos'],
     ['Ja, wenn sie selbst gefangen wurden', 'Yes, if they were caught by oneself', 'Sim, se foram capturados por si mesmo'],
     ['Ja, aber nur untermaßige Fische', 'Yes, but only undersized fish', 'Sim, mas somente peixes abaixo do mínimo']],
    0,
    ['Nach §4 BbgFischO ist das Angeln mit lebenden Fischen als Köder verboten. Als Köder dürfen nur tote Fische verwendet werden.',
     'Under section 4 of the BbgFischO, fishing with live fish as bait is prohibited. Only dead fish may be used as bait.',
     'Pelo §4 da BbgFischO, a pesca com peixes vivos como isca é proibida. Como isca, somente peixes mortos podem ser usados.'],
    ['recht', 'koeder'], ['hecht', 'zander']],

  ['bbg-293', 'einschlaegige_rechtsvorschriften',
    ['Was ist bei der Verwendung von toten Köderfischen hinsichtlich der Herkunft zu beachten?',
     'What should be observed regarding the origin when using dead bait fish?',
     'O que se deve observar quanto à origem ao usar peixes-isca mortos?'],
    [['Die Köderfische müssen aus erlaubten Quellen stammen, geschützte Arten dürfen nicht verwendet werden', 'The bait fish must come from permitted sources and protected species must not be used', 'Os peixes-isca devem vir de fontes permitidas e espécies protegidas não podem ser usadas'],
     ['Die Herkunft ist völlig egal', 'The origin does not matter at all', 'A origem não importa em nada'],
     ['Es dürfen nur Fische aus Aquarien verwendet werden', 'Only aquarium fish may be used', 'Somente peixes de aquário podem ser usados']],
    0,
    ['Als Köderfische dürfen keine geschützten Arten und keine Fische unter dem Mindestmaß verwendet werden. Die Entnahme ist nur aus erlaubten Gewässern zulässig.',
     'Protected species and fish below the minimum size must not be used as bait fish. Taking them is only permitted from allowed waters.',
     'Espécies protegidas e peixes abaixo do tamanho mínimo não podem ser usados como isca. A retirada só é permitida em águas autorizadas.'],
    ['recht', 'koeder'], ['hecht', 'zander']],

  ['bbg-294', 'einschlaegige_rechtsvorschriften',
    ['Wie viele Fische darf man in der Regel pro Angeltag entnehmen?',
     'How many fish may one usually take per fishing day?',
     'Quantos peixes normalmente se pode levar por dia de pesca?'],
    [['Es gelten die Begrenzungen der Angelkarte und die gesetzlichen Regeln', 'The limits of the fishing permit and the legal rules apply', 'Valem os limites da permissão de pesca e as regras legais'],
     ['Unbegrenzt viele', 'An unlimited number', 'Um número ilimitado'],
     ['Genau zehn Fische', 'Exactly ten fish', 'Exatamente dez peixes']],
    0,
    ['Entnahmebegrenzungen sind in der Angelkarte, in Vereinsregeln oder in Verordnungen festgelegt. Sie sind vor dem Angeln zu beachten.',
     'Take limits are set out in the fishing permit, in club rules or in regulations. They must be respected before fishing.',
     'Os limites de captura constam na permissão de pesca, nas regras dos clubes ou em regulamentos. Eles devem ser respeitados antes de pescar.'],
    ['recht', 'entnahme'], ['hecht', 'zander']],

  ['bbg-295', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Angeln mit Kunstlicht in der Nacht zu beachten?',
     'What should be observed when fishing with artificial light at night?',
     'O que se deve observar ao pescar com luz artificial à noite?'],
    [['Das Anlocken von Fischen mit Licht ist nicht gestattet, Nachtangeln selbst ist grundsätzlich erlaubt', 'Attracting fish with light is not permitted; night fishing itself is basically allowed', 'Atrair peixes com luz não é permitido; a pesca noturna em si é basicamente permitida'],
     ['Nachtangeln ist immer verboten', 'Night fishing is always prohibited', 'A pesca noturna é sempre proibida'],
     ['Es darf jede Art von Licht verwendet werden', 'Any kind of light may be used', 'Pode-se usar qualquer tipo de luz']],
    0,
    ['Nachtangeln ist in Brandenburg grundsätzlich erlaubt. Das Anlocken der Fische durch künstliche Lichtquellen ist jedoch nicht zulässig.',
     'Night fishing is basically permitted in Brandenburg. Attracting fish with artificial light sources, however, is not permitted.',
     'A pesca noturna é basicamente permitida em Brandemburgo. Atrair os peixes com fontes de luz artificial, porém, não é permitido.'],
    ['nachtangeln', 'recht'], ['hecht', 'zander', 'wels']],

  ['bbg-296', 'einschlaegige_rechtsvorschriften',
    ['Was ist ein Fischereirecht?',
     'What is a fishing right?',
     'O que é o direito de pesca?'],
    [['Das Recht, in einem Gewässer Fischerei auszuüben', 'The right to exercise fishing in a water body', 'O direito de exercer a pesca em um corpo d\u2019água'],
     ['Das Recht, Fische zu verkaufen', 'The right to sell fish', 'O direito de vender peixes'],
     ['Das Recht, ein Boot zu führen', 'The right to operate a boat', 'O direito de conduzir um barco']],
    0,
    ['Das Fischereirecht ist das Recht zur Ausübung der Fischerei in einem Gewässer. Es steht in Brandenburg dem Eigentümer des Gewässers zu.',
     'The fishing right is the right to exercise fishing in a water body. In Brandenburg it belongs to the owner of the water.',
     'O direito de pesca é o direito de exercer a pesca em um corpo d\u2019água. Em Brandemburgo, ele cabe ao proprietário da água.'],
    ['recht', 'fischereirecht'], ['hecht', 'zander']],

  ['bbg-297', 'einschlaegige_rechtsvorschriften',
    ['Wem steht das Fischereirecht an einem Gewässer zu?',
     'Who holds the fishing right at a water body?',
     'A quem cabe o direito de pesca em um corpo d\u2019água?'],
    [['Dem Eigentümer des Gewässers', 'The owner of the water', 'Ao proprietário da água'],
     ['Jedem Angler', 'Every angler', 'A todo pescador'],
     ['Dem Staat immer', 'Always the state', 'Sempre ao estado']],
    0,
    ['Das Fischereirecht ist an das Gewässereigentum gekoppelt. Der Eigentümer kann es verpachten und Angelkarten ausgeben.',
     'The fishing right is tied to the ownership of the water. The owner can lease it out and issue fishing permits.',
     'O direito de pesca está vinculado à propriedade da água. O proprietário pode arrendá-lo e emitir permissões de pesca.'],
    ['recht', 'fischereirecht'], ['hecht', 'zander']],

  ['bbg-298', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Fang eines Fisches während der Schonzeit einer anderen Art zu beachten?',
     'What should be observed when catching a fish during the closed season of another species?',
     'O que se deve observar ao capturar um peixe durante o defeso de outra espécie?'],
    [['Es gelten die Schonzeiten und Mindestmaße der jeweiligen Art, die gezielt befischt wird', 'The closed seasons and minimum sizes of the respective species that is deliberately fished apply', 'Valem os defesos e tamanhos mínimos da respectiva espécie alvo'],
     ['Es gelten keine Regeln', 'No rules apply', 'Não valem regras'],
     ['Alle Fische dürfen das ganze Jahr entnommen werden', 'All fish may be taken all year round', 'Todos os peixes podem ser levados o ano todo']],
    0,
    ['Beim Angeln ist für jede entnommene Art die eigene Schonzeit und das eigene Mindestmaß zu beachten. Beifänge geschonter Arten werden zurückgesetzt (§2 BbgFischO).',
     'When fishing, the closed season and minimum size of each species taken must be respected. By-catches of species in their closed season are released (section 2 BbgFischO).',
     'Ao pescar, devem ser respeitados o defeso e o tamanho mínimo de cada espécie capturada. Capturas acidentais de espécies em defeso são soltas (§2 BbgFischO).'],
    ['schonzeit', 'mindestmass', 'recht'], ['hecht', 'zander', 'karpfen']],

  ['bbg-299', 'einschlaegige_rechtsvorschriften',
    ['Wo kann man sich über die aktuellen Schonzeiten und Mindestmaße informieren?',
     'Where can one find out about the current closed seasons and minimum sizes?',
     'Onde se pode informar sobre os defesos e tamanhos mínimos vigentes?'],
    [['In der BbgFischO sowie in den Aushängen und Unterlagen der Angelkarten', 'In the BbgFischO and in the notices and documents of the fishing permits', 'Na BbgFischO e nos avisos e documentos das permissões de pesca'],
     ['Nur in ausländischen Gesetzen', 'Only in foreign laws', 'Somente em leis estrangeiras'],
     ['Gar nicht', 'Not at all', 'Em lugar nenhum']],
    0,
    ['Die gültigen Schonzeiten und Mindestmaße stehen in der BbgFischO und werden auf den Angelkarten oder in Gewässeraushängen bekannt gegeben.',
     'The valid closed seasons and minimum sizes are set out in the BbgFischO and are announced on the fishing permits or in water notices.',
     'Os defesos e tamanhos mínimos vigentes constam na BbgFischO e são divulgados nas permissões de pesca ou em avisos nas águas.'],
    ['schonzeit', 'mindestmass', 'recht'], ['hecht', 'zander']],

  ['bbg-300', 'einschlaegige_rechtsvorschriften',
    ['Warum ist die Einhaltung der Fischereivorschriften für den Bestand wichtig?',
     'Why is compliance with the fisheries regulations important for the stocks?',
     'Por que o cumprimento dos regulamentos de pesca é importante para os estoques?'],
    [['Weil Schonzeiten, Mindestmaße und Entnahmebegrenzungen die Bestände schützen', 'Because closed seasons, minimum sizes and take limits protect the stocks', 'Porque defesos, tamanhos mínimos e limites de captura protegem os estoques'],
     ['Weil sie den Anglern mehr Fang erlauben', 'Because they allow anglers to catch more', 'Porque permitem aos pescadores capturar mais'],
     ['Weil sie den Fischhandel regeln', 'Because they regulate the fish trade', 'Porque regulam o comércio de peixes']],
    0,
    ['Die Vorschriften der BbgFischG und BbgFischO sichern die natürliche Vermehrung und die nachhaltige Nutzung der Fischbestände. Ihre Einhaltung ist Pflicht jedes Anglers.',
     'The regulations of the BbgFischG and BbgFischO secure the natural reproduction and sustainable use of the fish stocks. Complying with them is the duty of every angler.',
     'Os regulamentos da BbgFischG e da BbgFischO asseguram a reprodução natural e o uso sustentável dos estoques de peixes. Cumpri-los é dever de todo pescador.'],
    ['recht', 'hege'], ['hecht', 'zander', 'karpfen']],
]
