// Category: einschlaegige_rechtsvorschriften — Legal regulations (1/2)
export const questions = [
  // --- Fischereischein / Anglerpruefung / Angelkarte ---
  ['bbg-241', 'einschlaegige_rechtsvorschriften',
    ['Wer darf in Brandenburg grundsätzlich angeln?',
     'Who is basically allowed to fish in Brandenburg?',
     'Quem pode basicamente pescar em Brandemburgo?'],
    [['Personen mit gültigem Fischereischein und Angelkarte', 'People with a valid fishing licence and fishing permit', 'Pessoas com licença de pesca e permissão de pesca válidas'],
     ['Jeder, der eine Rute besitzt', 'Anyone who owns a rod', 'Qualquer pessoa que tenha uma vara'],
     ['Nur Gewässereigentümer', 'Only water owners', 'Somente proprietários de águas']],
    0,
    ['Zum Angeln in Brandenburg sind ein gültiger Fischereischein und eine Angelkarte des Gewässereigentümers erforderlich (§17 BbgFischG).',
     'Fishing in Brandenburg requires a valid fishing licence and a fishing permit from the water owner (section 17 BbgFischG).',
     'Para pescar em Brandemburgo são necessários uma licença de pesca válida e uma permissão de pesca do proprietário da água (§17 BbgFischG).'],
    ['fischereischein', 'angelkarte'], ['hecht', 'karpfen']],

  ['bbg-242', 'einschlaegige_rechtsvorschriften',
    ['Was ist der Fischereischein?',
     'What is the fishing licence?',
     'O que é a licença de pesca?'],
    [['Der amtliche Nachweis der fischereilichen Kenntnisse und der Erlaubnis zur Fischerei', 'The official proof of fishing knowledge and of the permission to fish', 'A comprovação oficial dos conhecimentos de pesca e da permissão para pescar'],
     ['Ein Ausweis für den Besuch von Angelgeschäften', 'An ID card for visiting fishing shops', 'Um documento para visitar lojas de pesca'],
     ['Ein Dokument für den Verkauf von Fischen', 'A document for selling fish', 'Um documento para vender peixes']],
    0,
    ['Der Fischereischein wird nach bestandener Fischerprüfung erteilt und bestätigt die erforderlichen Kenntnisse für die Fischereiausübung (§17 BbgFischG).',
     'The fishing licence is issued after passing the fishing examination and confirms the knowledge required for fishing (section 17 BbgFischG).',
     'A licença de pesca é emitida após a aprovação no exame de pesca e confirma os conhecimentos exigidos para a prática da pesca (§17 BbgFischG).'],
    ['fischereischein'], ['hecht', 'zander']],

  ['bbg-243', 'einschlaegige_rechtsvorschriften',
    ['Welche Voraussetzung muss man für den Fischereischein erfüllen?',
     'Which requirement must one meet for the fishing licence?',
     'Qual requisito se deve cumprir para obter a licença de pesca?'],
    [['Die Fischerprüfung (Anglerprüfung) bestehen und das Mindestalter erreichen', 'Pass the fishing examination and reach the minimum age', 'Passar no exame de pesca e atingir a idade mínima'],
     ['Einen Angelschein im Ausland kaufen', 'Buy a fishing certificate abroad', 'Comprar um certificado de pesca no exterior'],
     ['Mindestens 50 Fische gefangen haben', 'Have caught at least 50 fish', 'Ter capturado pelo menos 50 peixes']],
    0,
    ['Der Fischereischein wird auf Antrag erteilt, wenn die Fischerprüfung bestanden wurde und das gesetzliche Mindestalter erreicht ist (§17 und §19 BbgFischG).',
     'The fishing licence is issued on application once the fishing examination has been passed and the statutory minimum age is reached (sections 17 and 19 BbgFischG).',
     'A licença de pesca é emitida mediante pedido, quando o exame de pesca é aprovado e a idade mínima legal é atingida (§17 e §19 BbgFischG).'],
    ['fischereischein', 'pruefung'], ['hecht', 'zander']],

  ['bbg-244', 'einschlaegige_rechtsvorschriften',
    ['Was ist die Angelkarte?',
     'What is the fishing permit (Angelkarte)?',
     'O que é a permissão de pesca (Angelkarte)?'],
    [['Der Erlaubnisschein des Fischereiausübungsberechtigten zum Angeln in seinem Gewässer', 'The licence of the holder of the fishing right to fish in his water', 'A autorização do titular do direito de pesca para pescar em sua água'],
     ['Ein Ausweis mit Foto des Anglers', 'An ID card with a photo of the angler', 'Um documento com foto do pescador'],
     ['Ein Nachweis über gekaufte Ausrüstung', 'A proof of purchased equipment', 'Uma comprovação de equipamento comprado']],
    0,
    ['Die Angelkarte ist die Erlaubnis des Gewässereigentümers oder Pächters, in einem bestimmten Gewässer zu angeln. Sie ist zusätzlich zum Fischereischein erforderlich.',
     'The fishing permit is the permission of the water owner or tenant to fish in a specific water. It is required in addition to the fishing licence.',
     'A permissão de pesca é a autorização do proprietário ou arrendatário da água para pescar em um corpo d\u2019água específico. Ela é exigida além da licença de pesca.'],
    ['angelkarte'], ['hecht', 'karpfen']],

  ['bbg-245', 'einschlaegige_rechtsvorschriften',
    ['Wer stellt die Angelkarte aus?',
     'Who issues the fishing permit?',
     'Quem emite a permissão de pesca?'],
    [['Der Fischereiausübungsberechtigte, also Eigentümer oder Pächter des Gewässers', 'The holder of the fishing right, i.e. the owner or tenant of the water', 'O titular do direito de pesca, ou seja, o proprietário ou arrendatário da água'],
     ['Die örtliche Polizei', 'The local police', 'A polícia local'],
     ['Jedes Angelfachgeschäft', 'Any fishing shop', 'Qualquer loja de pesca']],
    0,
    ['Angelkarten werden vom Fischereiausübungsberechtigten ausgegeben, häufig über Vereine, Angelgeschäfte oder online. Sie gelten nur für das jeweilige Gewässer.',
     'Fishing permits are issued by the holder of the fishing right, often via clubs, fishing shops or online. They are valid only for the respective water.',
     'As permissões de pesca são emitidas pelo titular do direito de pesca, geralmente por clubes, lojas de pesca ou online. Valem somente para a respectiva água.'],
    ['angelkarte'], ['hecht', 'zander']],

  ['bbg-246', 'einschlaegige_rechtsvorschriften',
    ['Welche Dokumente muss man beim Angeln mitführen?',
     'Which documents must one carry when fishing?',
     'Quais documentos se deve portar ao pescar?'],
    [['Fischereischein, Angelkarte und einen Ausweis', 'Fishing licence, fishing permit and an ID', 'Licença de pesca, permissão de pesca e um documento de identidade'],
     ['Nur den Fischereischein', 'Only the fishing licence', 'Somente a licença de pesca'],
     ['Nur die Angelkarte', 'Only the fishing permit', 'Somente a permissão de pesca']],
    0,
    ['Beim Angeln sind Fischereischein, Angelkarte und ein Ausweisdokument mitzuführen und auf Verlangen der Fischereiaufsicht vorzuzeigen.',
     'When fishing, one must carry the fishing licence, fishing permit and an ID and present them on request to the fisheries control.',
     'Ao pescar, devem ser portadas a licença de pesca, a permissão de pesca e um documento de identidade, apresentados a pedido da fiscalização de pesca.'],
    ['fischereischein', 'angelkarte'], ['hecht', 'karpfen']],

  ['bbg-247', 'einschlaegige_rechtsvorschriften',
    ['Was droht, wenn man ohne Fischereischein angelt?',
     'What is the risk if one fishes without a fishing licence?',
     'O que se arrisca ao pescar sem licença de pesca?'],
    [['Ein Bußgeld als Ordnungswidrigkeit, in schweren Fällen eine Strafverfolgung', 'A fine as an administrative offence, in serious cases criminal prosecution', 'Multa como infração administrativa e, em casos graves, processo penal'],
     ['Nichts, das ist erlaubt', 'Nothing, that is permitted', 'Nada, isso é permitido'],
     ['Nur eine mündliche Ermahnung', 'Only a verbal warning', 'Apenas uma advertência verbal']],
    0,
    ['Das Angeln ohne Fischereischein ist eine Ordnungswidrigkeit nach dem BbgFischG. Bei gewerbs- oder gewohnheitsmäßigem Angeln ohne Berechtigung droht eine Strafverfolgung wegen Fischwilderei.',
     'Fishing without a fishing licence is an administrative offence under the BbgFischG. Commercial or habitual unauthorised fishing risks criminal prosecution for fish poaching.',
     'Pescar sem licença de pesca é infração administrativa conforme o BbgFischG. Pesca comercial ou habitual sem autorização arrisca processo penal por furto de pesca.'],
    ['fischereischein', 'recht'], ['hecht', 'zander']],

  ['bbg-248', 'einschlaegige_rechtsvorschriften',
    ['Was ist die Fischereiabgabe?',
     'What is the fishing levy (Fischereiabgabe)?',
     'O que é a taxa de pesca (Fischereiabgabe)?'],
    [['Eine jährliche Abgabe, die für die Fischereiausübung zu entrichten ist', 'An annual levy that must be paid for exercising fishing', 'Uma taxa anual que deve ser paga para o exercício da pesca'],
     ['Eine Gebühr für den Kauf einer Angelrute', 'A fee for buying a fishing rod', 'Uma taxa pela compra de uma vara'],
     ['Eine Strafe für unerlaubtes Angeln', 'A penalty for unauthorised fishing', 'Uma penalidade por pesca não autorizada']],
    0,
    ['Die Fischereiabgabe ist eine jährliche Abgabe, die neben dem Fischereischein zu entrichten ist. Sie fließt in Fischerei- und Gewässerschutzmaßnahmen.',
     'The fishing levy is an annual levy to be paid in addition to the fishing licence. It goes into fisheries and water protection measures.',
     'A taxa de pesca é uma taxa anual a ser paga além da licença de pesca. Ela é destinada a medidas de proteção da pesca e das águas.'],
    ['fischereiabgabe', 'recht'], ['hecht', 'zander']],

  ['bbg-249', 'einschlaegige_rechtsvorschriften',
    ['Wofür wird die Fischereiabgabe verwendet?',
     'What is the fishing levy used for?',
     'Para que é usada a taxa de pesca?'],
    [['Für Maßnahmen der Fischerei und des Gewässerschutzes', 'For fisheries and water protection measures', 'Para medidas de pesca e de proteção das águas'],
     ['Für den Bau von Angelgeschäften', 'For the construction of fishing shops', 'Para a construção de lojas de pesca'],
     ['Für die Bezahlung der Angler', 'For paying the anglers', 'Para pagar os pescadores']],
    0,
    ['Die Fischereiabgabe finanziert unter anderem Bestandsstützung, Gewässerpflege und Fischereiaufsicht. Sie kommt damit direkt dem Fischbestand zugute.',
     'The fishing levy funds, among other things, stock support, water care and fisheries control. It thus directly benefits the fish stocks.',
     'A taxa de pesca financia, entre outras coisas, a sustentação de estoques, o cuidado das águas e a fiscalização. Ela beneficia diretamente os estoques de peixes.'],
    ['fischereiabgabe', 'recht'], ['hecht', 'karpfen']],

  ['bbg-250', 'einschlaegige_rechtsvorschriften',
    ['Wer muss die Fischereiabgabe entrichten?',
     'Who must pay the fishing levy?',
     'Quem deve pagar a taxa de pesca?'],
    [['Alle Personen, die einen Fischereischein besitzen', 'All persons who hold a fishing licence', 'Todas as pessoas que possuem licença de pesca'],
     ['Nur Berufsfischer', 'Only commercial fishermen', 'Somente pescadores profissionais'],
     ['Nur Gewässereigentümer', 'Only water owners', 'Somente proprietários de águas']],
    0,
    ['Die Fischereiabgabe ist von allen Fischereischeininhabern zu entrichten, also auch von Freizeitanglern. Ohne entrichtete Abgabe ist der Fischereischein nicht wirksam.',
     'The fishing levy must be paid by all licence holders, including recreational anglers. Without the paid levy the fishing licence is not effective.',
     'A taxa de pesca deve ser paga por todos os titulares de licença, inclusive pescadores amadores. Sem o pagamento, a licença não é válida.'],
    ['fischereiabgabe', 'recht'], ['hecht', 'zander']],

  ['bbg-251', 'einschlaegige_rechtsvorschriften',
    ['Was ist die Anglerprüfung (Fischerprüfung)?',
     'What is the angling examination?',
     'O que é o exame de pesca?'],
    [['Eine Prüfung der erforderlichen Kenntnisse für die Fischereiausübung', 'An examination of the knowledge required for fishing', 'Um exame dos conhecimentos exigidos para a prática da pesca'],
     ['Ein praktischer Wurfwettbewerb', 'A practical casting competition', 'Uma competição prática de lançamento'],
     ['Eine Prüfung der Angelausrüstung', 'An inspection of the fishing equipment', 'Uma inspeção do equipamento de pesca']],
    0,
    ['Die Anglerprüfung stellt die fischereilichen Kenntnisse der Prüfungsteilnehmer fest (§19 BbgFischG). Sie ist Voraussetzung für den Erwerb des Fischereischeins.',
     'The angling examination establishes the fishing knowledge of the candidates (section 19 BbgFischG). It is a prerequisite for obtaining the fishing licence.',
     'O exame de pesca verifica os conhecimentos de pesca dos candidatos (§19 BbgFischG). Ele é pré-requisito para obter a licença de pesca.'],
    ['pruefung', 'fischereischein'], ['hecht', 'zander']],

  ['bbg-252', 'einschlaegige_rechtsvorschriften',
    ['Aus welchen Sachgebieten besteht die Anglerprüfung?',
     'Which subject areas does the angling examination consist of?',
     'De quais áreas temáticas o exame de pesca é composto?'],
    [['Fischkunde, Gewässerpflege, Gerätekunde, Fischbehandlung und Recht', 'Fish science, water care, gear knowledge, fish handling and law', 'Ciência dos peixes, cuidado das águas, equipamentos, manejo de peixes e direito'],
     ['Mathematik, Physik und Chemie', 'Mathematics, physics and chemistry', 'Matemática, física e química'],
     ['Sprachen, Kunst und Musik', 'Languages, art and music', 'Línguas, arte e música']],
    0,
    ['Die Prüfung umfasst die fünf Sachgebiete Fischkunde und Hege, Gewässerpflege, Fanggeräte, Behandlung gefangener Fische und Rechtsvorschriften.',
     'The examination covers the five subject areas of fish science and care, water care, fishing gear, handling of caught fish and legal regulations.',
     'O exame abrange as cinco áreas: ciência dos peixes e manejo, cuidado das águas, equipamentos de pesca, manejo de peixes capturados e regulamentos legais.'],
    ['pruefung'], ['hecht', 'zander']],

  ['bbg-253', 'einschlaegige_rechtsvorschriften',
    ['Wie viele Fragen hat die Anglerprüfung in Brandenburg?',
     'How many questions does the angling examination in Brandenburg have?',
     'Quantas questões tem o exame de pesca em Brandemburgo?'],
    [['60 Fragen', '60 questions', '60 questões'],
     ['30 Fragen', '30 questions', '30 questões'],
     ['100 Fragen', '100 questions', '100 questões']],
    0,
    ['Die Anglerprüfung in Brandenburg besteht aus 60 Fragen, zwölf aus jedem der fünf Sachgebiete (§19 BbgFischG).',
     'The angling examination in Brandenburg consists of 60 questions, twelve from each of the five subject areas (section 19 BbgFischG).',
     'O exame de pesca em Brandemburgo consiste em 60 questões, doze de cada uma das cinco áreas (§19 BbgFischG).'],
    ['pruefung'], ['hecht', 'zander']],

  ['bbg-254', 'einschlaegige_rechtsvorschriften',
    ['Wann gilt die Anglerprüfung als bestanden?',
     'When is the angling examination considered passed?',
     'Quando o exame de pesca é considerado aprovado?'],
    [['Bei mindestens 45 von 60 Punkten und mindestens 6 Punkten je Sachgebiet', 'With at least 45 of 60 points and at least 6 points in each subject area', 'Com pelo menos 45 de 60 pontos e pelo menos 6 pontos em cada área'],
     ['Bei 30 von 60 Punkten insgesamt', 'With 30 of 60 points in total', 'Com 30 de 60 pontos no total'],
     ['Bei 60 Punkten in einem einzigen Sachgebiet', 'With 60 points in a single subject area', 'Com 60 pontos em uma única área']],
    0,
    ['Bestanden ist die Prüfung, wenn insgesamt mindestens 45 Punkte und in jedem Sachgebiet mindestens 6 Punkte erreicht werden (§19 BbgFischG).',
     'The examination is passed when at least 45 points in total and at least 6 points in each subject area are achieved (section 19 BbgFischG).',
     'O exame é aprovado quando se alcançam pelo menos 45 pontos no total e pelo menos 6 pontos em cada área (§19 BbgFischG).'],
    ['pruefung'], ['hecht', 'zander']],

  ['bbg-255', 'einschlaegige_rechtsvorschriften',
    ['Wer nimmt die Anglerprüfung in der Regel ab?',
     'Who usually administers the angling examination?',
     'Quem normalmente aplica o exame de pesca?'],
    [['Die untere Fischereibehörde oder von ihr anerkannte Stellen', 'The lower fisheries authority or bodies recognised by it', 'A autoridade inferior de pesca ou entidades por ela reconhecidas'],
     ['Jeder Anglerverein ohne Prüfung', 'Any angling club without an examination', 'Qualquer clube de pesca, sem exame'],
     ['Die Polizei im Rahmen von Kontrollen', 'The police in the context of checks', 'A polícia, no âmbito de fiscalizações']],
    0,
    ['Die Prüfung wird von der zuständigen unteren Fischereibehörde oder anerkannten Prüfungsstellen abgenommen (§19 BbgFischG).',
     'The examination is administered by the competent lower fisheries authority or recognised examination bodies (section 19 BbgFischG).',
     'O exame é aplicado pela autoridade inferior de pesca competente ou por entidades examinadoras reconhecidas (§19 BbgFischG).'],
    ['pruefung'], ['hecht', 'zander']],

  ['bbg-256', 'einschlaegige_rechtsvorschriften',
    ['Ist die Anglerprüfung Voraussetzung für den Fischereischein?',
     'Is the angling examination a prerequisite for the fishing licence?',
     'O exame de pesca é pré-requisito para a licença de pesca?'],
    [['Ja, ohne bestandene Prüfung gibt es keinen Fischereischein', 'Yes, without passing the examination there is no fishing licence', 'Sim, sem aprovação no exame não há licença de pesca'],
     ['Nein, der Fischereischein ist käuflich erhältlich', 'No, the fishing licence can be bought', 'Não, a licença de pesca pode ser comprada'],
     ['Nein, er wird automatisch mit 18 Jahren erteilt', 'No, it is issued automatically at 18', 'Não, ela é emitida automaticamente aos 18 anos']],
    0,
    ['Der Fischereischein setzt die bestandene Anglerprüfung voraus (§17 und §19 BbgFischG). Er wird nicht ohne Prüfung erteilt.',
     'The fishing licence requires passing the angling examination (sections 17 and 19 BbgFischG). It is not issued without the examination.',
     'A licença de pesca exige a aprovação no exame de pesca (§17 e §19 BbgFischG). Ela não é emitida sem exame.'],
    ['pruefung', 'fischereischein'], ['hecht', 'zander']],

  ['bbg-257', 'einschlaegige_rechtsvorschriften',
    ['Ab welchem Alter können Jugendliche in Brandenburg einen Jugendfischereischein erhalten?',
     'From which age can young people in Brandenburg obtain a youth fishing licence?',
     'A partir de que idade os jovens podem obter a licença de pesca juvenil em Brandemburgo?'],
    [['Ab dem vollendeten 14. Lebensjahr', 'From the completed 14th year of age', 'A partir dos 14 anos completos'],
     ['Erst ab 18 Jahren', 'Only from 18 years', 'Somente a partir dos 18 anos'],
     ['Ab dem vollendeten 10. Lebensjahr', 'From the completed 10th year of age', 'A partir dos 10 anos completos']],
    0,
    ['Jugendliche können ab 14 Jahren nach bestandener Prüfung einen Jugendfischereischein erhalten. Er ist zeitlich begrenzt und unterscheidet sich vom Erwachsenenschein.',
     'Young people can obtain a youth fishing licence from 14 after passing the examination. It is limited in time and differs from the adult licence.',
     'Jovens a partir de 14 anos podem obter a licença juvenil após aprovação no exame. Ela tem validade limitada e difere da licença de adulto.'],
    ['fischereischein', 'pruefung'], ['hecht', 'zander']],

  ['bbg-258', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Verlust des Fischereischeins zu tun?',
     'What should be done if the fishing licence is lost?',
     'O que se deve fazer se a licença de pesca for perdida?'],
    [['Den Verlust melden und einen Ersatz beantragen', 'Report the loss and apply for a replacement', 'Comunicar a perda e solicitar uma segunda via'],
     ['Nichts, das ist nicht nötig', 'Nothing, that is not necessary', 'Nada, não é necessário'],
     ['Einfach weiterangeln', 'Simply keep fishing', 'Simplesmente continuar pescando']],
    0,
    ['Ein verlorener Fischereischein wird bei der ausstellenden Behörde gemeldet und auf Antrag ersetzt. Ohne gültigen Schein darf nicht geangelt werden.',
     'A lost fishing licence is reported to the issuing authority and replaced on application. Without a valid licence one must not fish.',
     'Uma licença perdida é comunicada à autoridade emissora e substituída mediante pedido. Sem licença válida, não se pode pescar.'],
    ['fischereischein'], ['hecht', 'zander']],

  ['bbg-259', 'einschlaegige_rechtsvorschriften',
    ['Wer kontrolliert die Einhaltung der Fischereivorschriften?',
     'Who controls compliance with the fisheries regulations?',
     'Quem fiscaliza o cumprimento dos regulamentos de pesca?'],
    [['Die Fischereiaufsicht, die Polizei und die Ordnungsbehörden', 'The fisheries control, the police and the regulatory authorities', 'A fiscalização de pesca, a polícia e as autoridades de ordenamento'],
     ['Niemand', 'No one', 'Ninguém'],
     ['Nur andere Angler', 'Only other anglers', 'Somente outros pescadores']],
    0,
    ['Die Einhaltung der Fischereivorschriften wird durch die Fischereiaufsicht, die Polizei und die zuständigen Ordnungsbehörden kontrolliert.',
     'Compliance with the fisheries regulations is controlled by the fisheries control, the police and the competent regulatory authorities.',
     'O cumprimento dos regulamentos de pesca é fiscalizado pela fiscalização de pesca, pela polícia e pelas autoridades competentes.'],
    ['recht', 'aufsicht'], ['hecht', 'zander']],

  ['bbg-260', 'einschlaegige_rechtsvorschriften',
    ['Was versteht man unter Fischwilderei?',
     'What is meant by fish poaching?',
     'O que se entende por furto de pesca (pesca ilegal)?'],
    [['Das unbefugte Fischen ohne Fischereischein oder ohne Angelkarte', 'Unauthorised fishing without a fishing licence or without a fishing permit', 'A pesca não autorizada, sem licença de pesca ou sem permissão'],
     ['Das Angeln mit erlaubten Mitteln', 'Fishing with permitted means', 'A pesca com meios permitidos'],
     ['Das Fangen von Fischen zum Eigenverzehr', 'Catching fish for one\u2019s own consumption', 'A captura de peixes para consumo próprio']],
    0,
    ['Fischwilderei ist das unbefugte Fischen, zum Beispiel ohne Fischereischein oder in fremden Gewässern. Sie kann als Straftat verfolgt werden.',
     'Fish poaching is unauthorised fishing, for example without a fishing licence or in foreign waters. It can be prosecuted as a crime.',
     'O furto de pesca é a pesca não autorizada, por exemplo sem licença ou em águas alheias. Ele pode ser processado como crime.'],
    ['recht'], ['hecht', 'zander']],

  ['bbg-261', 'einschlaegige_rechtsvorschriften',
    ['Darf man an einem fremden Privatgewässer ohne Erlaubnis angeln?',
     'May one fish in a foreign private water without permission?',
     'Pode-se pescar em uma água privada alheia sem permissão?'],
    [['Nein, das ist unzulässig und kann als Wilderei geahndet werden', 'No, that is not permitted and can be punished as poaching', 'Não, isso não é permitido e pode ser punido como furto de pesca'],
     ['Ja, wenn man eine Rute hat', 'Yes, if one has a rod', 'Sim, se tiver uma vara'],
     ['Ja, aber nur im Sommer', 'Yes, but only in summer', 'Sim, mas somente no verão']],
    0,
    ['Das Angeln in fremden Gewässern setzt die Erlaubnis des Fischereiausübungsberechtigten (Angelkarte) voraus. Ohne Erlaubnis liegt Fischwilderei vor.',
     'Fishing in foreign waters requires the permission of the holder of the fishing right (fishing permit). Without permission this constitutes fish poaching.',
     'Pescar em águas alheias exige a autorização do titular do direito de pesca (permissão de pesca). Sem autorização, há furto de pesca.'],
    ['recht', 'angelkarte'], ['hecht', 'zander']],

  ['bbg-262', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Angeln an einem Vereinsgewässer zu beachten?',
     'What should be observed when fishing at a club water?',
     'O que se deve observar ao pescar em uma água de clube?'],
    [['Die Vereinsregeln, die Angelkarte und die Satzungen des Vereins einhalten', 'Respect the club rules, the fishing permit and the club statutes', 'Respeitar as regras do clube, a permissão de pesca e os estatutos'],
     ['Nur die Größe der Rute beachten', 'Only pay attention to the size of the rod', 'Somente observar o tamanho da vara'],
     ['Es gelten keine besonderen Regeln', 'No special rules apply', 'Não valem regras especiais']],
    0,
    ['Vereinsgewässer haben oft eigene Regeln zu Angelzeiten, Entnahmebegrenzungen und Ködern. Diese sind neben den gesetzlichen Vorschriften zu beachten.',
     'Club waters often have their own rules on fishing times, take limits and baits. These must be respected alongside the legal regulations.',
     'Águas de clube costumam ter regras próprias sobre horários, limites de captura e iscas. Elas devem ser respeitadas além das normas legais.'],
    ['angelkarte', 'recht'], ['hecht', 'karpfen']],

  ['bbg-263', 'einschlaegige_rechtsvorschriften',
    ['Ist das Angeln in der Nacht in Brandenburg grundsätzlich erlaubt?',
     'Is night fishing basically permitted in Brandenburg?',
     'A pesca noturna é basicamente permitida em Brandemburgo?'],
    [['Ja, grundsätzlich ist Nachtangeln erlaubt', 'Yes, night fishing is basically permitted', 'Sim, a pesca noturna é basicamente permitida'],
     ['Nein, Nachtangeln ist immer verboten', 'No, night fishing is always prohibited', 'Não, a pesca noturna é sempre proibida'],
     ['Nur mit behördlicher Sondergenehmigung', 'Only with a special official permit', 'Somente com autorização especial oficial']],
    0,
    ['Nachtangeln ist in Brandenburg grundsätzlich erlaubt. Es können jedoch besondere Regelungen des Gewässereigentümers oder lokale Einschränkungen gelten.',
     'Night fishing is basically permitted in Brandenburg. However, special rules of the water owner or local restrictions may apply.',
     'A pesca noturna é basicamente permitida em Brandemburgo. Porém, podem valer regras especiais do proprietário da água ou restrições locais.'],
    ['nachtangeln', 'recht'], ['hecht', 'zander', 'wels']],

  ['bbg-264', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Angeln an einem Fließgewässer zu beachten?',
     'What should be observed when fishing at a running water?',
     'O que se deve observar ao pescar em um rio?'],
    [['Die Rechte des Ufereigentümers beachten und nur mit Erlaubnis auf fremde Ufer treten', 'Respect the rights of the bank owner and only step onto foreign banks with permission', 'Respeitar os direitos do proprietário da margem e pisar em margens alheias somente com permissão'],
     ['Das Ufer darf immer frei betreten werden', 'The bank may always be walked on freely', 'A margem pode ser sempre percorrida livremente'],
     ['Im Fluss darf nie geangelt werden', 'One may never fish in a river', 'Nunca se pode pescar em um rio']],
    0,
    ['Auch zum Angeln darf fremdes Ufer nur mit Erlaubnis des Eigentümers betreten werden. Es gelten zudem die Schonzeiten und Mindestmaße der BbgFischO.',
     'Even for fishing, foreign banks may only be entered with the permission of the owner. The closed seasons and minimum sizes of the BbgFischO also apply.',
     'Mesmo para pescar, margens alheias só podem ser pisadas com permissão do proprietário. Também valem os defesos e tamanhos mínimos da BbgFischO.'],
    ['recht', 'ufer'], ['hecht', 'zander']],

  ['bbg-265', 'einschlaegige_rechtsvorschriften',
    ['Welche Strafe droht bei der Entnahme untermaßiger Fische?',
     'What penalty threatens when taking undersized fish?',
     'Qual penalidade ameaça quem leva peixes abaixo do tamanho mínimo?'],
    [['Ein Bußgeld als Ordnungswidrigkeit', 'A fine as an administrative offence', 'Multa como infração administrativa'],
     ['Keine Strafe', 'No penalty', 'Nenhuma penalidade'],
     ['Nur ein Eintrag im Fangbuch', 'Only an entry in the catch book', 'Apenas um registro no livro de capturas']],
    0,
    ['Die Entnahme untermaßiger Fische verstößt gegen die Mindestmaßregeln der BbgFischO und wird als Ordnungswidrigkeit mit einem Bußgeld geahndet.',
     'Taking undersized fish violates the minimum size rules of the BbgFischO and is punished as an administrative offence with a fine.',
     'Levar peixes abaixo do tamanho mínimo viola as regras de tamanho mínimo da BbgFischO e é punido como infração administrativa com multa.'],
    ['recht', 'mindestmass'], ['hecht', 'zander', 'karpfen']],

  ['bbg-266', 'einschlaegige_rechtsvorschriften',
    ['Was ist beim Führen des Fischereischeins zu beachten?',
     'What should be observed when carrying the fishing licence?',
     'O que se deve observar ao portar a licença de pesca?'],
    [['Der Schein muss beim Angeln mitgeführt und auf Verlangen vorgezeigt werden', 'The licence must be carried when fishing and shown on request', 'A licença deve ser portada ao pescar e apresentada a pedido'],
     ['Der Schein bleibt zu Hause', 'The licence stays at home', 'A licença fica em casa'],
     ['Der Schein muss im Wasser aufbewahrt werden', 'The licence must be kept in the water', 'A licença deve ser guardada na água']],
    0,
    ['Der Fischereischein ist beim Angeln mitzuführen und den Kontrollorganen auf Verlangen vorzuzeigen. Gleiches gilt für die Angelkarte.',
     'The fishing licence must be carried when fishing and shown to the control authorities on request. The same applies to the fishing permit.',
     'A licença de pesca deve ser portada ao pescar e apresentada aos órgãos de controle a pedido. O mesmo vale para a permissão de pesca.'],
    ['fischereischein', 'recht'], ['hecht', 'zander']],

  ['bbg-267', 'einschlaegige_rechtsvorschriften',
    ['Wie viele Punkte muss man in der Anglerprüfung mindestens erreichen, um zu bestehen?',
     'How many points must one achieve at least in the angling examination to pass?',
     'Quantos pontos se deve alcançar no mínimo no exame de pesca para ser aprovado?'],
    [['45 von 60 Punkten', '45 of 60 points', '45 de 60 pontos'],
     ['30 von 60 Punkten', '30 of 60 points', '30 de 60 pontos'],
     ['60 von 60 Punkten', '60 of 60 points', '60 de 60 pontos']],
    0,
    ['Zum Bestehen sind mindestens 45 von 60 Punkten erforderlich, wobei in jedem Sachgebiet mindestens 6 Punkte erreicht werden müssen (§19 BbgFischG).',
     'To pass, at least 45 of 60 points are required, with at least 6 points needed in each subject area (section 19 BbgFischG).',
     'Para ser aprovado são necessários pelo menos 45 de 60 pontos, sendo que em cada área se deve alcançar pelo menos 6 pontos (§19 BbgFischG).'],
    ['pruefung'], ['hecht', 'zander']],

  ['bbg-268', 'einschlaegige_rechtsvorschriften',
    ['Wie viele Punkte müssen in jedem Sachgebiet der Anglerprüfung erreicht werden?',
     'How many points must be achieved in each subject area of the angling examination?',
     'Quantos pontos se deve alcançar em cada área do exame de pesca?'],
    [['Mindestens 6 Punkte', 'At least 6 points', 'Pelo menos 6 pontos'],
     ['Mindestens 10 Punkte', 'At least 10 points', 'Pelo menos 10 pontos'],
     ['Mindestens 12 Punkte', 'At least 12 points', 'Pelo menos 12 pontos']],
    0,
    ['In jedem der fünf Sachgebiete müssen mindestens 6 von 12 möglichen Punkten erreicht werden. Sonst gilt die Prüfung auch bei 45 Gesamtpunkten als nicht bestanden.',
     'In each of the five subject areas at least 6 of 12 possible points must be achieved. Otherwise the examination counts as failed even with 45 total points.',
     'Em cada uma das cinco áreas devem ser alcançados pelo menos 6 dos 12 pontos possíveis. Caso contrário, o exame é considerado reprovado mesmo com 45 pontos no total.'],
    ['pruefung'], ['hecht', 'zander']],

  ['bbg-269', 'einschlaegige_rechtsvorschriften',
    ['Was ist die untere Fischereibehörde?',
     'What is the lower fisheries authority?',
     'O que é a autoridade inferior de pesca?'],
    [['Die örtlich zuständige Behörde, die unter anderem die Anglerprüfung organisiert', 'The locally competent authority that organises the angling examination among other things', 'A autoridade local competente que, entre outras coisas, organiza o exame de pesca'],
     ['Ein Angelverein', 'An angling club', 'Um clube de pesca'],
     ['Ein Angelgeschäft', 'A fishing shop', 'Uma loja de pesca']],
    0,
    ['Die untere Fischereibehörde ist in der Regel der Landkreis oder die kreisfreie Stadt. Sie ist zuständig für Fischereischeine, Prüfungen und die Fischereiaufsicht.',
     'The lower fisheries authority is usually the district or the independent city. It is responsible for fishing licences, examinations and fisheries control.',
     'A autoridade inferior de pesca normalmente é o distrito ou a cidade independente. Ela é responsável por licenças, exames e fiscalização da pesca.'],
    ['recht', 'pruefung'], ['hecht', 'zander']],

  ['bbg-270', 'einschlaegige_rechtsvorschriften',
    ['Darf man in Brandenburg mit mehr als zwei Ruten angeln?',
     'May one fish with more than two rods in Brandenburg?',
     'Pode-se pescar com mais de duas varas em Brandemburgo?'],
    [['Nein, erlaubt sind höchstens zwei Handangeln je Person', 'No, at most two hand line rods per person are permitted', 'Não, permitidas no máximo duas varas de mão por pessoa'],
     ['Ja, bis zu fünf Ruten', 'Yes, up to five rods', 'Sim, até cinco varas'],
     ['Ja, die Anzahl ist nicht begrenzt', 'Yes, the number is not limited', 'Sim, o número não é limitado']],
    0,
    ['Nach §3 BbgFischO darf beim Angeln je Person höchstens mit zwei Handangeln gefischt werden. Weitere Ruten wären eine Ordnungswidrigkeit.',
     'Under section 3 of the BbgFischO a person may fish with at most two hand line rods. Additional rods would be an administrative offence.',
     'Pelo §3 da BbgFischO, cada pessoa pode pescar com no máximo duas varas de mão. Varas adicionais seriam infração administrativa.'],
    ['recht', 'geraete'], ['hecht', 'karpfen']],
]
